### DISCUSSION TITLE
Size Mismatch when loading XL models.

### DISCUSSION THREAD

**Discussion by CaptainKokomo** [vladmandic/sdnext#2061] [Q&A] [answered]
I just downloaded Vlad today.
Put it into Pinokio and aimed the paths at my normal SD web Ui models folder. (That is probably half the problem I bet).
Long story short, XL was working for first few days with normal install, update and stopped working. 
Tried different command line arguments
Tried rolling back the GPU drivers, was sitting on 3.1.7 I think it was for a while. Updated to latest drivers just before writing this.
Tried uninstalling extensions to eliminate variables.
Tried fresh install.
Tried Comfy and lost patience with it. 
Tried to teach myself coding on the fly to fix cuda errors. My wings caught fire.
Now we are at Vlad in Pinokio and I got the black image. Managed to fix that with some settings juggling.
BUT... whenever I try to load an XL model I get the long list of errors down below.
I am well aware that it is probably something really simple but I am out of my depth floundering around trying everything that I can google. I did search many places for similar problems but tried nearly everything I found. (thats how I fixed the black screen)

Windows 10
Using chrome (tried edge and didn't see any improvement)
2060 super 8gb
64gb on the motherboard
dual monitors if that makes a difference.
usually have a couple tabs on the other monitor with videos queued while I make my images. 
Anything else you need to know I will be happy to find out. 

Using VENV: D:\Pinokio\api\automatic.git\venv
20:56:22-825340 INFO     Starting SD.Next
20:56:22-830300 INFO     Python 3.10.11 on Windows
20:56:22-973644 INFO     Version: 863fa38c Wed Aug 23 00:31:43 2023 +0300
20:56:25-643969 INFO     Latest published version: 89a3994c30d4ab65d86f99395917ba9e20eeaff7 2023-08-23T09:12:13Z
20:56:25-649833 INFO     nVidia CUDA toolkit detected
20:56:26-196564 INFO     Disabled extensions: []
20:56:26-199044 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
20:56:26-206980 INFO     Enabled extensions: []
20:56:26-209956 INFO     No changes detected: Quick launch active
20:56:26-210948 INFO     Verifying requirements
20:56:26-229797 INFO     Verifying packages
20:56:26-234260 INFO     Disabled extensions: []
20:56:26-236244 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
20:56:26-245172 INFO     Enabled extensions: []
20:56:26-251124 INFO     Extension preload: 0.0s D:\Pinokio\api\automatic.git\extensions-builtin
20:56:26-253108 INFO     Extension preload: 0.0s extensions
20:56:26-286836 INFO     Server arguments: []
20:56:34-559124 INFO     Pipeline: Backend.ORIGINAL
20:56:35-454795 INFO     Libraries loaded
20:56:35-457771 INFO     Using data path:
20:56:35-464219 INFO     Available VAEs: D:\Pinokio\api\sd-webui.pinokio.git\automatic1111\models\VAE items=3
20:56:35-502183 INFO     Available models: D:\Pinokio\api\sd-webui.pinokio.git\automatic1111\models\stable-diffusion
                         items=77
20:56:39-065068 INFO     ControlNet v1.1.306
ControlNet v1.1.306
ControlNet preprocessor location: D:\Pinokio\api\automatic.git\extensions-builtin\sd-webui-controlnet\annotator\downloads
20:56:39-589382 INFO     ControlNet v1.1.306
ControlNet v1.1.306
20:56:43-546201 INFO     Loading UI theme: name=black-orange style=Auto
20:56:43-658826 INFO     Extra network created thumbnails: checkpoints 0
20:56:44-030793 INFO     Extra network created thumbnails: lora 0
20:56:44-043193 INFO     Extra network created thumbnails: lycoris 0
20:56:44-082874 INFO     Extra network created thumbnails: textual inversion 0
Running on local URL:  http://127.0.0.1:7860
20:56:50-108022 INFO     Local URL: http://127.0.0.1:7860/
20:56:50-110503 INFO     Initializing middleware
20:56:50-449767 INFO     [AgentScheduler] Task queue is empty
20:56:50-453238 INFO     [AgentScheduler] Registering APIs
Loading weights: D:\Pinokio\api\sd-webui.pinokio.git\automatic1111\models\stable-diffusion\xl6HEPHAISTOSSD10XLSFW_v21…
20:56:54-711919 INFO     Torch override dtype: no-half set
20:56:54-715392 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
20:57:01-892967 ERROR    Error loading model weights:
                         D:\Pinokio\api\sd-webui.pinokio.git\automatic1111\models\stable-diffusion\xl6HEPHAISTOSSD10XLS
                         FW_v21.safetensors Error(s) in loading state_dict for LatentDiffusion:
                                 size mismatch for model.diffusion_model.input_blocks.4.1.proj_in.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([640, 640, 1, 1]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: copying a param
                         with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([640, 768]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: copying a param
                         with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([640, 768]).
                                 size mismatch for model.diffusion_model.input_blocks.4.1.proj_out.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([640, 640, 1, 1]).
                                 size mismatch for model.diffusion_model.input_blocks.5.1.proj_in.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([640, 640, 1, 1]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: copying a param
                         with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([640, 768]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: copying a param
                         with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([640, 768]).
                                 size mismatch for model.diffusion_model.input_blocks.5.1.proj_out.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([640, 640, 1, 1]).
                                 size mismatch for model.diffusion_model.input_blocks.7.1.proj_in.weight: copying a
                         param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight: copying a param
                         with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight: copying a param
                         with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for model.diffusion_model.input_blocks.7.1.proj_out.weight: copying a
                         param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.input_blocks.8.1.proj_in.weight: copying a
                         param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight: copying a param
                         with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight: copying a param
                         with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for model.diffusion_model.input_blocks.8.1.proj_out.weight: copying a
                         param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.middle_block.1.proj_in.weight: copying a param
                         with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for
                         model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k.weight: copying a param
                         with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v.weight: copying a param
                         with shape torch.Size([1280, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for model.diffusion_model.middle_block.1.proj_out.weight: copying a
                         param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.2.0.in_layers.0.weight: copying
                         a param with shape torch.Size([1920]) from checkpoint, the shape in current model is
                         torch.Size([2560]).
                                 size mismatch for model.diffusion_model.output_blocks.2.0.in_layers.0.bias: copying a
                         param with shape torch.Size([1920]) from checkpoint, the shape in current model is
                         torch.Size([2560]).
                                 size mismatch for model.diffusion_model.output_blocks.2.0.in_layers.2.weight: copying
                         a param with shape torch.Size([1280, 1920, 3, 3]) from checkpoint, the shape in current model
                         is torch.Size([1280, 2560, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.2.0.skip_connection.weight:
                         copying a param with shape torch.Size([1280, 1920, 1, 1]) from checkpoint, the shape in
                         current model is torch.Size([1280, 2560, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.in_layers.0.weight: copying
                         a param with shape torch.Size([1920]) from checkpoint, the shape in current model is
                         torch.Size([2560]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.in_layers.0.bias: copying a
                         param with shape torch.Size([1920]) from checkpoint, the shape in current model is
                         torch.Size([2560]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.in_layers.2.weight: copying
                         a param with shape torch.Size([640, 1920, 3, 3]) from checkpoint, the shape in current model
                         is torch.Size([1280, 2560, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.in_layers.2.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.emb_layers.1.weight: copying
                         a param with shape torch.Size([640, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.emb_layers.1.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.out_layers.0.weight: copying
                         a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.out_layers.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.out_layers.3.weight: copying
                         a param with shape torch.Size([640, 640, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.out_layers.3.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.skip_connection.weight:
                         copying a param with shape torch.Size([640, 1920, 1, 1]) from checkpoint, the shape in current
                         model is torch.Size([1280, 2560, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.3.0.skip_connection.bias:
                         copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.1.norm.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.1.norm.bias: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.1.proj_in.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.3.1.proj_in.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_q.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_k.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_v.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.weight: copying a
                         param with shape torch.Size([5120, 640]) from checkpoint, the shape in current model is
                         torch.Size([10240, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.bias: copying a
                         param with shape torch.Size([5120]) from checkpoint, the shape in current model is
                         torch.Size([10240]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.weight: copying a param
                         with shape torch.Size([640, 2560]) from checkpoint, the shape in current model is
                         torch.Size([1280, 5120]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.bias: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_q.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_k.weight: copying a
                         param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_v.weight: copying a
                         param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.3.1.proj_out.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.3.1.proj_out.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.in_layers.0.weight: copying
                         a param with shape torch.Size([1280]) from checkpoint, the shape in current model is
                         torch.Size([2560]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.in_layers.0.bias: copying a
                         param with shape torch.Size([1280]) from checkpoint, the shape in current model is
                         torch.Size([2560]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.in_layers.2.weight: copying
                         a param with shape torch.Size([640, 1280, 3, 3]) from checkpoint, the shape in current model
                         is torch.Size([1280, 2560, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.in_layers.2.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.emb_layers.1.weight: copying
                         a param with shape torch.Size([640, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.emb_layers.1.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.out_layers.0.weight: copying
                         a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.out_layers.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.out_layers.3.weight: copying
                         a param with shape torch.Size([640, 640, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.out_layers.3.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.skip_connection.weight:
                         copying a param with shape torch.Size([640, 1280, 1, 1]) from checkpoint, the shape in current
                         model is torch.Size([1280, 2560, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.4.0.skip_connection.bias:
                         copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.1.norm.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.1.norm.bias: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.1.proj_in.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.4.1.proj_in.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_q.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_k.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_v.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight: copying a
                         param with shape torch.Size([5120, 640]) from checkpoint, the shape in current model is
                         torch.Size([10240, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias: copying a
                         param with shape torch.Size([5120]) from checkpoint, the shape in current model is
                         torch.Size([10240]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.weight: copying a param
                         with shape torch.Size([640, 2560]) from checkpoint, the shape in current model is
                         torch.Size([1280, 5120]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.bias: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_q.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: copying a
                         param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: copying a
                         param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.4.1.proj_out.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.4.1.proj_out.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.in_layers.0.weight: copying
                         a param with shape torch.Size([960]) from checkpoint, the shape in current model is
                         torch.Size([1920]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.in_layers.0.bias: copying a
                         param with shape torch.Size([960]) from checkpoint, the shape in current model is
                         torch.Size([1920]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.in_layers.2.weight: copying
                         a param with shape torch.Size([640, 960, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1920, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.in_layers.2.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.emb_layers.1.weight: copying
                         a param with shape torch.Size([640, 1280]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.emb_layers.1.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.out_layers.0.weight: copying
                         a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.out_layers.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.out_layers.3.weight: copying
                         a param with shape torch.Size([640, 640, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.out_layers.3.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.skip_connection.weight:
                         copying a param with shape torch.Size([640, 960, 1, 1]) from checkpoint, the shape in current
                         model is torch.Size([1280, 1920, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.5.0.skip_connection.bias:
                         copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.1.norm.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.1.norm.bias: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.1.proj_in.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.5.1.proj_in.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_q.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_k.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_v.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight: copying a
                         param with shape torch.Size([5120, 640]) from checkpoint, the shape in current model is
                         torch.Size([10240, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias: copying a
                         param with shape torch.Size([5120]) from checkpoint, the shape in current model is
                         torch.Size([10240]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.weight: copying a param
                         with shape torch.Size([640, 2560]) from checkpoint, the shape in current model is
                         torch.Size([1280, 5120]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.bias: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_q.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: copying a
                         param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: copying a
                         param with shape torch.Size([640, 2048]) from checkpoint, the shape in current model is
                         torch.Size([1280, 768]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.weight: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for
                         model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.bias: copying a param with
                         shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.1.proj_out.weight: copying a
                         param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.5.1.proj_out.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.5.2.conv.weight: copying a param
                         with shape torch.Size([640, 640, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.5.2.conv.bias: copying a param
                         with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.in_layers.0.weight: copying
                         a param with shape torch.Size([960]) from checkpoint, the shape in current model is
                         torch.Size([1920]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.in_layers.0.bias: copying a
                         param with shape torch.Size([960]) from checkpoint, the shape in current model is
                         torch.Size([1920]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.in_layers.2.weight: copying
                         a param with shape torch.Size([320, 960, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([640, 1920, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.in_layers.2.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.emb_layers.1.weight: copying
                         a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is
                         torch.Size([640, 1280]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.emb_layers.1.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.out_layers.0.weight: copying
                         a param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.out_layers.0.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.out_layers.3.weight: copying
                         a param with shape torch.Size([320, 320, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([640, 640, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.out_layers.3.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.skip_connection.weight:
                         copying a param with shape torch.Size([320, 960, 1, 1]) from checkpoint, the shape in current
                         model is torch.Size([640, 1920, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.6.0.skip_connection.bias:
                         copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.in_layers.0.weight: copying
                         a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.in_layers.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([1280]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.in_layers.2.weight: copying
                         a param with shape torch.Size([320, 640, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([640, 1280, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.in_layers.2.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.emb_layers.1.weight: copying
                         a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is
                         torch.Size([640, 1280]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.emb_layers.1.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.out_layers.0.weight: copying
                         a param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.out_layers.0.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.out_layers.3.weight: copying
                         a param with shape torch.Size([320, 320, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([640, 640, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.out_layers.3.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.skip_connection.weight:
                         copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current
                         model is torch.Size([640, 1280, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.7.0.skip_connection.bias:
                         copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.in_layers.0.weight: copying
                         a param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([960]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.in_layers.0.bias: copying a
                         param with shape torch.Size([640]) from checkpoint, the shape in current model is
                         torch.Size([960]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.in_layers.2.weight: copying
                         a param with shape torch.Size([320, 640, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([640, 960, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.in_layers.2.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.emb_layers.1.weight: copying
                         a param with shape torch.Size([320, 1280]) from checkpoint, the shape in current model is
                         torch.Size([640, 1280]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.emb_layers.1.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.out_layers.0.weight: copying
                         a param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.out_layers.0.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.out_layers.3.weight: copying
                         a param with shape torch.Size([320, 320, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([640, 640, 3, 3]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.out_layers.3.bias: copying a
                         param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.skip_connection.weight:
                         copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current
                         model is torch.Size([640, 960, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.skip_connection.bias:
                         copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
20:57:08-114286 INFO     Applying xformers cross attention optimization
20:57:21-284083 INFO     Embeddings: loaded=46 skipped=6
20:57:21-293945 INFO     Model loaded in 28.4s (load=1.7s config=0.1s create=6.0s apply=2.9s move=4.5s
                         embeddings=13.2s)
20:57:21-669912 INFO     Model load finished: {'ram': {'used': 1.96, 'total': 63.85}, 'gpu': {'used': 5.11, 'total':
                         8.0}, 'retries': 0, 'oom': 0} cached=0
20:57:22-102947 INFO     Startup time: 55.8s (torch=6.0s gradio=0.8s libraries=2.3s scripts=5.0s onchange=3.0s
                         ui-txt2img=0.6s ui-img2img=0.1s ui-settings=0.1s ui-extensions=5.2s ui-defaults=0.1s
                         launch=0.4s app-started=1.7s checkpoint=30.3s)

**Comment by vladmandic** [comment]
You are using wrong backend in settings.

**Reply by CaptainKokomo** [reply]
thanks for the quick reply I had heard that Vlad was so much better maintained than normal.

Easy fix I knew it lol
Just enabled attention slicing and error is gone. 
Thanks mate you're a legend :)

**Reply by CaptainKokomo** [reply]
My mistake... error popped up again. 
Any idea which back end settings I need to cast an eye on?
would the --safe thing help?

**Reply by vladmandic** [reply]
No, safe is not relevant here.
On very first page of settings, set backend to diffusers and restart.

**Reply by CaptainKokomo** [reply]
It's working now. I am generating images.
It's just taking a while. I have heard that one of the latest gpu drivers causes it to go slow.
and does this now.

22:26:54-999726 ERROR    Running script process batch:
                         extensions\sd-webui-additional-networks\scripts\additional_networks.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\Pinokio\api\automatic.git\modules\scripts.py:451 in process_batch                                                │
│                                                                                                                     │
│   450 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 451 │   │   │   │   script.process_batch(p, *args, **kwargs)                                                      │
│   452 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                     │
│                                                                                                                     │
│ D:\Pinokio\api\automatic.git\extensions\sd-webui-additional-networks\scripts\additional_networks.py:187 in          │
│ process_batch                                                                                                       │
│                                                                                                                     │
│   186 │   def process_batch(self, p, *args, **kwargs):                                                              │
│ > 187 │   │   unet = p.sd_model.model.diffusion_model                                                               │
│   188 │   │   text_encoder = p.sd_model.cond_stage_model                                                            │
│                                                                                                                     │
│ D:\Pinokio\api\automatic.git\venv\lib\site-packages\diffusers\configuration_utils.py:137 in __getattr__             │
│                                                                                                                     │
│   136 │   │                                                                                                         │
│ > 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                      │
│   138                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'model'
Progress ?it/s                                              0% 0/20 00:00 ? Base

**Reply by vladmandic** [reply, marked as answer]
Additional networks extension is obsolete.

**Comment by CaptainKokomo** [comment]
fuck me you are good mate.
Thank you for your patience I appreciate  you taking the time to give me a hand. 

All the best mate.
