### ISSUE TITLE
[Issue] Cannot Install with --Use-ZLUDA, Will Not Work

### ISSUE THREAD

**Issue by KhunDoug** [vladmandic/sdnext#3785]
### Issue Description

This is a clean install of SD.Next. The git pull works correctly and creates the SDNext folder inside my profile. I have Zluda installed and working correctly with Automatic1111 and ComfyUI.

The attempt to install with --use-zluda hit an error in the Python code and quits. I then tried to get things working with --use-directml. That gets as far as creating the VENV and looks correct. But then it bombs on an error that Torch is not compiled with CUDA support. At this point I tried using the --use-zluda and I get the webpage. I even have a model downloaded and installed. But trying to create a text to image  just produces multiples instances of this:

16:44:00-269879 DEBUG    Server: alive=True requests=459 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1692 elapsed=1687.23 eta=None progress=0

I know Zluda and Python are working as I am able to ComfyUI and Automatic1111 and those work correctly, This error is isolated to SD.Next.

### Version Platform Description

AMD Ryzen 5950X, XFX Radeon 6800XT, 64GB RAM, Windows 11 24H2

16:15:27-887166 INFO     Starting SD.Next
16:15:27-891181 INFO     Logger: file="C:\Users\Doug\sdnext\sdnext.log" level=DEBUG host="COLOSUSSUS5950AI" size=84
                         mode=create
16:15:27-893187 INFO     Python: version=3.11.2 platform=Windows bin="C:\Users\Doug\sdnext\venv\Scripts\python.exe"
                         venv="C:\Users\Doug\sdnext\venv"
16:15:28-058593 INFO     Version: app=sd.next updated=2025-02-24 hash=a1ab39bb branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master ui=main
16:15:28-390275 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.26100-SP0 python=3.11.2 locale=('English_United States', '1252')
                         docker=False
16:15:28-392281 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
16:15:28-392281 INFO     Args: ['--use-zluda', '--debug']
16:15:28-394304 DEBUG    Setting environment tuning
16:15:28-394304 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
16:15:28-398324 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
16:15:28-404354 INFO     ROCm: AMD toolkit detected
16:15:28-776869 INFO     ROCm: agents=['gfx1030']
16:15:28-776869 INFO     ROCm: version=5.7, using agent gfx1030
16:15:28-778877 INFO     Python: version=3.11.2 platform=Windows bin="C:\Users\Doug\sdnext\venv\Scripts\python.exe"
                         venv="C:\Users\Doug\sdnext\venv"
16:15:28-817119 INFO     Using ZLUDA in C:\Users\Doug\sdnext\.zluda
No ROCm runtime is found, using ROCM_HOME='C:\Program Files\AMD\ROCm\5.7'
16:15:30-482970 INFO     Install: verifying requirements
16:15:30-529767 DEBUG    Timestamp repository update time: Mon Feb 24 21:17:23 2025
16:15:30-531774 INFO     Startup: standard
16:15:30-531774 INFO     Verifying submodules
16:15:32-278719 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
16:15:32-357121 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
16:15:32-431777 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
16:15:32-544431 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
16:15:32-544431 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
16:15:32-618866 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
16:15:32-697250 DEBUG    Git submodule: modules/k-diffusion / master
16:15:32-771618 DEBUG    Git submodule: wiki / master
16:15:32-817874 DEBUG    Register paths
16:15:32-880187 DEBUG    Installed packages: 174
16:15:32-880187 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
16:15:33-057813 DEBUG    Extension installer:
                         C:\Users\Doug\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py
16:15:35-529987 DEBUG    Extension installer:
                         C:\Users\Doug\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py
16:15:44-264654 DEBUG    Extensions all: []
16:15:44-264654 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
16:15:44-266659 INFO     Install: verifying requirements
16:15:44-266659 DEBUG    Setup complete without errors: 1740518144

### Relevant log output

```shell
16:17:11-519634 INFO     Base: pipeline=StableDiffusionPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'guidance_scale': 6,
                         'generator': 'cpu:[1035819445]', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale':
                         0.7, 'output_type': 'latent', 'width': 512, 'height': 512, 'parser': 'native', 'prompt':
                         'embeds'}
Progress ?it/s                                              0% 0/20 00:00 ? Base16:17:59-780118 DEBUG    Server: alive=True requests=149 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=131 elapsed=126.74 eta=None progress=0
16:19:59-819638 DEBUG    Server: alive=True requests=173 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=251 elapsed=246.78 eta=None progress=0
16:21:59-858499 DEBUG    Server: alive=True requests=197 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=371 elapsed=366.82 eta=None progress=0
16:23:59-898537 DEBUG    Server: alive=True requests=221 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=491 elapsed=486.86 eta=None progress=0
16:25:59-937521 DEBUG    Server: alive=True requests=245 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=611 elapsed=606.89 eta=None progress=0
16:27:59-971670 DEBUG    Server: alive=True requests=269 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=731 elapsed=726.93 eta=None progress=0
16:30:00-010841 DEBUG    Server: alive=True requests=292 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=851 elapsed=846.97 eta=None progress=0
16:32:00-047393 DEBUG    Server: alive=True requests=316 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=971 elapsed=967.0 eta=None progress=0
16:34:00-083663 DEBUG    Server: alive=True requests=340 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1091 elapsed=1087.04 eta=None progress=0
16:36:00-119365 DEBUG    Server: alive=True requests=364 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1211 elapsed=1207.08 eta=None progress=0
16:38:00-160004 DEBUG    Server: alive=True requests=388 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1331 elapsed=1327.12 eta=None progress=0
16:40:00-198218 DEBUG    Server: alive=True requests=412 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1451 elapsed=1447.16 eta=None progress=0
16:42:00-231645 DEBUG    Server: alive=True requests=436 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1572 elapsed=1567.19 eta=None progress=0
16:44:00-269879 DEBUG    Server: alive=True requests=459 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1692 elapsed=1687.23 eta=None progress=0
16:46:00-308035 DEBUG    Server: alive=True requests=483 memory=0/0 status='running' task='Load'
                         timestamp='20250225161553' id='task(wu9kkj2maxn0d7i)' job=0 jobs=0 total=1 step=0 steps=0
                         queued=0 uptime=1812 elapsed=1807.27 eta=None progress=0
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by KhunDoug** [comment]
For whatever it is worth, if anyone else hits this error, I did this to coerce SD.Next to operate with ZLuda.

Open CMD/Terminal
CD SDNext
CD VENV
CD Scripts
Activate
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Once complete, exit this. Open Webui.bat with --Use-Zluda as the only parameter. The installer does not install the correct versions of pytorch. These steps got SD.Next operational on my setup.

**Comment by Disty0** [comment]
Zluda has up to 30 minutes of compile time for the first use. Getting stuck at the first start of generation is expected with Zluda.

Can't really debug further as the rest of the logs are cut-off.

**Comment by KhunDoug** [comment]
The odd thing is that once I manullay upgrade/install a pytorch that has CUDA support, I get the Compiling messages. And it works well from there. But it refuses to install from scratch. And I can get it to go so far if I use –use-directml. But then that also crashes with an error that pytorch has no CUDA support.

Would it helpful if I temporarily renamed the SDNEXT folder and did another fresh install? That would grab the original error message.

**Comment by mr44er** [comment]
https://forum.proxmox.com/threads/tutorial-run-llms-using-amd-gpu-and-rocm-in-unprivileged-lxc-container.157920/post-748367

There I wrote a quick snippet for usage in an unprivileged LXC, maybe you can pick something relevant from this thread. Tested with rocm and zluda.

**Comment by Disty0** [comment]
Torch not compiled with Cuda issue with DirectML is fixed.

As the CPU torch issue, DirectML uses CPU PyTorch version. You explicitly told SDNext to install DirectML at the start so that's why CPU PyTorch got installed.

**Comment by Disty0** [comment]
Closing as duplicate: https://github.com/vladmandic/sdnext/issues/3838
