### ISSUE TITLE
[Issue]: Does not work on ROG Ally

### ISSUE THREAD

**Issue by ZardashtKaya** [vladmandic/sdnext#3870]
### Issue Description

```
rocBLAS error: Could not load C:\Program Files\AMD\ROCm\6.2\bin\/rocblas/library/TensileLibrary_lazy_gfx1103.dat

rocBLAS error: Could not initialize Tensile library
```
this is what i'm getting.

### Relevant log output

```shell

```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
and what did you try? which install guide did you follow? where is installation log? single line error message is pretty much never sufficient.
we really cannot help without any information.

**Comment by Disty0** [comment]
Your GPU is unsupported by ROCm, follow the Zluda guide: https://github.com/vladmandic/sdnext/wiki/ZLUDA#replace-hip-sdk-library-files-for-unsupported-gpu-architectures

**Comment by shinra358** [comment]
I have Rog Ally Xtreme version. It's working for me. Well it keeps say cpu torch only. But I can get in. I can't use XL models though or it will disconnect

**Comment by shinra358** [comment]
python version incompatible when following that guide. please use 3.11. but when i try to install 3.11, it rolls back because a newer version is already installed.
