### ISSUE TITLE
[Issue]: Error during launch when using WSL with latest AMD Adrenaline drivers and latest ROCm

### ISSUE THREAD

**Issue by NaLogo** [vladmandic/sdnext#3973]
### Issue Description

When trying to launch SD.Next with WSL on the latest AMD Adrenaline drivers 25.6.1 and ROCm 6.4.1 the installation will work for the most part, but the script always error out when the webui.py module gets started.

The message is:
`python3: ./sources/wsl/libhsakmt/src/topology.cpp:613: HSAKMT_STATUS topology_sysfs_get_node_props(uint32_t, HsaNodeProperties&, bool&, uint32_t&): Assertion props.EngineId.ui32.Major && "HSA_OVERRIDE_GFX_VERSION may be needed"' failed.`

I'm not sure if a library or something is missing. I have installed the drivers with
`amdgpu-install -y --usecase=wsl,rocm,rocmdev,lrt,opencl,hip,hiplibsdk,mllib,mlsdk --no-dkms`

The output of rocminfo as well as the logs up until that point are attached. The logs cut off right when that error happens so it's not included in there.

[rocminfo_output.txt](https://github.com/user-attachments/files/20643084/rocminfo_output.txt)

[sdnext.log](https://github.com/user-attachments/files/20643086/sdnext.log)

![Image](https://github.com/user-attachments/assets/f6d9c77b-b239-40ad-8e1e-5a59e1690384)

### Version Platform Description

- Windows 11 w/ latest updates
- AMD Adrenaline Driver 25.6.1
- sdnext in dev branch at commit 894e15d3dc3771405e7943df1d94d067c5838342
- Python 3.11.13

### Relevant log output

```shell
python3: ./sources/wsl/libhsakmt/src/topology.cpp:613: HSAKMT_STATUS topology_sysfs_get_node_props(uint32_t, HsaNodeProperties&, bool&, uint32_t&): Assertion props.EngineId.ui32.Major && "HSA_OVERRIDE_GFX_VERSION may be needed"' failed.
```

### Backend

Diffusers

### Compute

AMD ROCm

### UI

Standard

### Branch

Dev

### Model

StableDiffusion 1.5

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
gfx1200 / RX 9000 requires nightly PyTorch with ROCm 6.4.1.  
Switch to dev branch and use `--use-rocm --use-nightly` when installing SDNext for the first time.  
PyTorch with ROCm 6.4 support isn't available on stable branch yet.

**Comment by Fire041992** [comment]
After install SDNext with dev branch and --use-rocm --use-nightly i get the same error

**Comment by Disty0** [comment]
What is the installed PyTorch version? It should be 2.8 +rocm6.4

**Comment by Fire041992** [comment]
Torch: torch==2.8.0 torchvision==0.23.0.dev20250609+rocm6.4

**Comment by Disty0** [comment]
Can you try running the webui with dev branch like this:

```
HSA_OVERRIDE_GFX_VERSION="12.0.1" ./webui.sh --use-rocm
```

**Comment by Fire041992** [comment]
Same error

**Comment by NaLogo** [comment]
It actually worked for me after updating to the preview driver 25.6.2 and performing a fresh setup in a new Ubuntu 22.04 instance.
This is with the most recent changes from the dev branch.

**Comment by Disty0** [comment]
Removed gfx overrides for rx 9000 in dev branch, this should also fix the issue caused by it.

**Comment by Fire041992** [comment]
Yes with the updates from the dev branch it works for me too
