### ISSUE TITLE
[Issue]: Using img to video + wan2.2, the console says I'm using 2 GPUs but I have disabled my iGPU and it gives an error

### ISSUE THREAD

**Issue by sgtsixpack** [vladmandic/sdnext#4141]
### Issue Description

I have a log from when I start SDNext till it errors.  I can't provide any more information above what the log says as its completely over my head.  

Not sure what "backend" I'm using, log should cover it.

https://www.reddit.com/r/ROCm/comments/1mq0lk0/comment/n8ue3nm/

ROCm 6.4 for windows is out in the wild.

### Version Platform Description

Using windows 11 24H2 latest version, using ROCm, AMD 9070xt, Zluda, Chrome and firefox.

ROCm: version=6.4, using agent gfx1201

### Relevant log output

```shell
J:\AItraining\SDNextFresh\sdnext>webui.bat --use-zluda --debug --update --autolaunch
Using VENV: J:\AItraining\SDNextFresh\sdnext\venv
21:26:23-805076 INFO     Starting SD.Next
21:26:23-807079 INFO     Logger: file="J:\AItraining\SDNextFresh\sdnext\sdnext.log" level=DEBUG host="9800x3d9070xt"
                         size=81 mode=create
21:26:23-808077 INFO     Python: version=3.11.9 platform=Windows
                         bin="J:\AItraining\SDNextFresh\sdnext\venv\Scripts\python.exe"
                         venv="J:\AItraining\SDNextFresh\sdnext\venv"
21:26:23-967260 INFO     Version: app=sd.next updated=2025-08-15 hash=419fad36 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master ui=main
21:26:24-467367 INFO     Updating main repository
21:26:27-090939 ERROR    Git: folder="." local changes detected
21:26:27-116430 INFO     Repository upgraded: 419fad36 Fri Aug 15 08:06:12 2025 -0400
21:26:27-121429 INFO     Platform: arch=AMD64 cpu=AMD64 Family 26 Model 68 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.26100-SP0 python=3.11.9 locale=('English_United Kingdom', '1252')
                         docker=False
21:26:27-121429 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
21:26:27-122497 INFO     Args: ['--use-zluda', '--debug', '--update', '--autolaunch']
21:26:27-123497 DEBUG    Setting environment tuning
21:26:27-124496 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
21:26:27-125497 INFO     Verifying torch installation
21:26:27-127497 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
21:26:27-131495 INFO     ROCm: AMD toolkit detected
21:26:27-507092 INFO     ROCm: agents=['gfx1201']
21:26:27-507092 INFO     ROCm: version=6.4, using agent gfx1201
21:26:27-538039 INFO     ZLUDA load: path='J:\AItraining\SDNextFresh\sdnext\.zluda' nightly=False
21:26:29-573441 INFO     Install: verifying requirements
21:26:29-575446 INFO     Startup: standard
21:26:29-576445 INFO     Verifying submodules
21:26:31-325086 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
21:26:31-789944 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
21:26:32-276668 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
21:26:32-771345 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
21:26:33-239915 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
21:26:33-727589 DEBUG    Git submodule: wiki / master
21:26:34-220994 DEBUG    Installed packages: 186
21:26:34-221993 DEBUG    Extensions all: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
21:26:34-268449 DEBUG    Git submodule: extensions-builtin\sd-extension-chainner / main
21:26:34-754637 DEBUG    Git submodule: extensions-builtin\sd-extension-system-info / main
21:26:35-234371 DEBUG    Git submodule: extensions-builtin\sd-webui-agent-scheduler / main
21:26:35-671983 DEBUG    Extension installer: builtin=True
                         file="J:\AItraining\SDNextFresh\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py"
21:26:35-742056 DEBUG    Git submodule: extensions-builtin\sdnext-modernui / main
21:26:36-229307 DEBUG    Git submodule: extensions-builtin\stable-diffusion-webui-rembg / master
21:26:36-655307 DEBUG    Extension installer: builtin=True
                         file="J:\AItraining\SDNextFresh\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.
                         py"
21:26:36-680469 DEBUG    Extensions all: []
21:26:36-680469 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
21:26:36-704745 INFO     Install: verifying requirements
21:26:36-706745 INFO     Updating Wiki
21:26:36-753759 DEBUG    Git submodule: J:\AItraining\SDNextFresh\sdnext\wiki / master
21:26:37-193808 WARNING  Setup complete with errors: ['git: .']
21:26:37-194813 WARNING  See log file for more details: J:\AItraining\SDNextFresh\sdnext\sdnext.log
21:26:37-198363 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
21:26:37-199368 INFO     Installer time: total=30.91 git=10.21 update=5.74 submodules=4.62 latest=3.31 torch=2.32
                         branch=0.67 amd=0.51 sd-webui-agent-scheduler=0.51 stable-diffusion-webui-rembg=0.50
                         sd-extension-chainner=0.49 wiki=0.49 sdnext-modernui=0.49 sd-extension-system-info=0.48
                         base=0.21 version=0.16 files=0.11
21:26:37-200367 INFO     Command line args: ['--use-zluda', '--debug', '--update', '--autolaunch'] autolaunch=True
                         upgrade=True use_zluda=True debug=True args=[]
21:26:37-201368 DEBUG    Env flags: []
21:26:37-201368 DEBUG    Starting module: <module 'webui' from 'J:\\AItraining\\SDNextFresh\\sdnext\\webui.py'>
21:26:48-166068 INFO     Torch: torch==2.7.1+cu118 torchvision==0.22.1+cu118
21:26:48-168066 INFO     Packages: diffusers==0.35.0.dev0 transformers==4.55.2 accelerate==1.10.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2
21:26:48-679237 DEBUG    ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']
21:26:48-740633 DEBUG    ONNX failed to initialize XL pipelines: module 'optimum.onnxruntime.modeling_diffusion' has no
                         attribute 'ORTPipelinePart'
21:26:48-835621 DEBUG    State initialized: id=2151572762512
21:26:49-358046 INFO     Device detect: memory=16.0 default=balanced
21:26:49-361778 DEBUG    Read: file="J:\AItraining\SDNextFresh\sdnext\config.json" json=14 bytes=735 time=0.000
                         fn=<module>:load
21:26:49-363855 INFO     Engine: backend=Backend.DIFFUSERS compute=zluda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
21:26:49-364853 DEBUG    Read: file="html\reference.json" json=95 bytes=47150 time=0.001
                         fn=_call_with_frames_removed:<module>
21:26:49-365855 DEBUG    Torch cuDNN: benchmark=True
21:26:49-366687 DEBUG    Torch attention: type="sdpa" flash=True memory=False math=True
21:26:49-367702 DEBUG    Torch attention: type="dynamic attention"
21:26:49-554194 INFO     Torch parameters: backend=zluda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass optimization="Scaled-Dot-Product"
21:26:49-721496 INFO     Device: device=AMD Radeon RX 9070 XT [ZLUDA] n=1 arch=compute_37 capability=(8, 8) cuda=11.8
                         cudnn=90100 driver=
21:26:49-852307 DEBUG    Entering start sequence
21:26:49-854417 DEBUG    Initializing
21:26:49-855419 DEBUG    Read: file="metadata.json" json=16 bytes=20145 time=0.000 fn=initialize:init_metadata
21:26:49-856418 DEBUG    Read: file="cache.json" json=2 bytes=2049 time=0.000 fn=initialize:init_cache
21:26:49-859416 WARNING  Cache location changed: previous="C:\Users\SgtSixpack\.cache\huggingface\hub" size=441 MB
21:26:49-883540 DEBUG    Huggingface cache: path="models\huggingface" size=209444 MB
21:26:49-925559 INFO     Available VAEs: path="models\VAE" items=0
21:26:49-926557 INFO     Available UNets: path="models\UNET" items=0
21:26:49-926557 INFO     Available TEs: path="models\Text-encoder" items=0
21:26:49-930557 INFO     Available Models: safetensors="models\Stable-diffusion":8 diffusers="models\Diffusers":3
                         items=11 time=0.00
21:26:49-940614 INFO     Available LoRAs: path="models\Lora" items=8 folders=2 time=0.00
21:26:49-956749 INFO     Available Styles: path="models\styles" items=344 time=0.02
21:26:50-024374 INFO     Available Detailer: path="models\yolo" items=11 downloaded=2
21:26:50-025376 DEBUG    Extensions: disabled=['sdnext-modernui']
21:26:50-026374 INFO     Load extensions
21:26:50-631998 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
21:26:50-635080 DEBUG    Extensions init time: total=0.61 sd-webui-agent-scheduler=0.47
21:26:50-643142 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.001 fn=__init__:__init__
21:26:50-644142 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.001
                         fn=__init__:find_scalers
21:26:50-645144 DEBUG    Available chaiNNer: path="models\chaiNNer" defined=25 discovered=0 downloaded=0
21:26:50-646146 INFO     Available Upscalers: items=72 downloaded=0 user=0 time=0.01 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
21:26:50-653215 DEBUG    UI start sequence
21:26:50-654215 INFO     UI locale: name="Auto"
21:26:50-654215 INFO     UI theme: type=Standard name="black-teal" available=13
21:26:50-658214 DEBUG    UI theme: css="J:\AItraining\SDNextFresh\sdnext\javascript\black-teal.css" base="sdnext.css"
                         user="None"
21:26:50-660216 DEBUG    UI initialize: txt2img
21:26:50-697247 DEBUG    Networks: type="model" items=105 subfolders=4 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Reference', 'J:\\AItraining\\SDNextFresh\\sdnext\\models\\Stable-diffusion'] list=0.02
                         thumb=0.00 desc=0.00 info=0.00 workers=12
21:26:50-699247 DEBUG    Networks: type="lora" items=8 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.01
                         thumb=0.00 desc=0.00 info=0.00 workers=12
21:26:50-704817 DEBUG    Networks: type="style" items=344 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.02 thumb=0.00 desc=0.00 info=0.00 workers=12
21:26:50-707325 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models\\wildcards']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
21:26:50-709325 DEBUG    Networks: type="embedding" items=1 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
21:26:50-710328 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
21:26:50-711324 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
21:26:50-820184 DEBUG    UI initialize: img2img
21:26:51-079449 DEBUG    UI initialize: control models="models\control"
21:26:51-183049 DEBUG    Script: fn="extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py" type=control
                         skip
21:26:51-299465 DEBUG    UI initialize: video
21:26:51-530255 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000 fn=__init__:read_from_file
21:26:51-530255 DEBUG    Settings: sections=23 settings=348/552 quicksettings=0
21:26:51-792746 INFO     Extension list is empty: refresh required
21:26:52-075576 DEBUG    Extension list: processed=5 installed=5 enabled=4 disabled=1 visible=5 hidden=0
21:26:52-343825 DEBUG    Root paths: ['J:\\AItraining\\SDNextFresh\\sdnext', 'models']
21:26:52-402049 INFO     Local URL: http://127.0.0.1:7860/
21:26:52-404935 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
21:26:52-405439 DEBUG    API initialize
21:26:52-503090 INFO     [AgentScheduler] Task queue is empty
21:26:52-505592 INFO     [AgentScheduler] Registering APIs
21:26:52-568943 DEBUG    Scripts setup: time=0.230 []
21:26:52-569944 DEBUG    Model metadata: file="metadata.json" no changes
21:26:52-570944 DEBUG    Model requested: fn=threading.py:run:<lambda>
21:26:52-571946 INFO     Load model: select="Diffusers\lopho/Wan2.2-T2V-A14B-Diffusers_bf16_vae [a7f7b49e14]"
21:26:52-573000 INFO     Autodetect model: detect="WanAI" class=WanPipeline
                         file="models\Diffusers\models--lopho--Wan2.2-T2V-A14B-Diffusers_bf16_vae\snapshots\a7f7b49e14b5
                         e82cd1ad699902f21d359d7b9be8"
21:26:52-574001 DEBUG    Setting model: component=huggingface parallel=True
21:26:52-576001 DEBUG    HF login: no token provided
21:26:52-742518 DEBUG    Load model: type=WanAI transformer="lopho/Wan2.2-T2V-A14B-Diffusers_bf16_vae" quant="None"
                         args={'torch_dtype': torch.bfloat16}
21:26:52-849895 ERROR    Load model:
                         path="models\Diffusers\models--lopho--Wan2.2-T2V-A14B-Diffusers_bf16_vae\snapshots\a7f7b49e14b5
                         e82cd1ad699902f21d359d7b9be8" lopho/Wan2.2-T2V-A14B-Diffusers_bf16_vae does not appear to have
                         a file named config.json.
21:26:52-850896 ERROR    Load model: 'tuple' object has no attribute 'sd_model_hash'
21:26:52-851898 ERROR    Model: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│J:\AItraining\SDNextFresh\sdnext\modules\sd_models.py:655 in load_diffuser                                            │
│                                                                                                                      │
│   654 │   │   set_overrides(sd_model, checkpoint_info)                                                               │
│❱  655 │   │   set_defaults(sd_model, checkpoint_info)                                                                │
│   656                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\modules\sd_models.py:556 in set_defaults                                             │
│                                                                                                                      │
│   555 def set_defaults(sd_model, checkpoint_info):                                                                   │
│❱  556 │   sd_model.sd_model_hash = checkpoint_info.calculate_shorthash() # pylint: disable=attribute-defined-outside │
│   557 │   sd_model.sd_checkpoint_info = checkpoint_info # pylint: disable=attribute-defined-outside-init             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'tuple' object has no attribute 'sd_model_hash'
21:26:52-929104 INFO     Load model: family=none time={} native=0 memory={'ram': {'total': 63.59, 'used': 1.48, 'free':
                         62}, 'gpu': {'used': 0.28, 'total': 15.92, 'active': 0.01, 'peak': 0.01, 'retries': 0, 'oom':
                         0, 'swap': 0}, 'job': 'Load'}
21:26:52-931105 DEBUG    Script init: ['task_scheduler.py:app_started=0.07']
21:26:52-931105 INFO     Startup time: total=56.75 launch=13.77 numpy=13.69 installer=13.67 libraries=7.96 torch=3.41
                         gradio=0.92 extensions=0.61 ui-extensions=0.54 checkpoint=0.36 ui-networks=0.31
                         ui-defaults=0.24 bnb=0.18 ui-control=0.16 app-started=0.11 ui-txt2img=0.10 ui-img2img=0.09
                         diffusers=0.09 ui-models=0.08 onnx=0.08 ui-video=0.07 samplers=0.07 detailer=0.07 api=0.06
21:26:52-934950 INFO     Launching browser
21:26:52-934950 DEBUG    Save: file="J:\AItraining\SDNextFresh\sdnext\config.json" json=14 bytes=720 time=0.004
21:26:59-217224 DEBUG    UI: connected
Progress 58.83it/s ██████████████ 100% 3/3 00:00 00:00 Loading checkpoint shards
Progress 11995.15it/s █████████████████ 100% 12/12 00:00 00:00 Fetching 12 files
Progress  2.34s/it ████████████ 100% 12/12 00:28 00:00 Loading checkpoint shards
Progress  2.67s/it ████████████ 100% 12/12 00:32 00:00 Loading checkpoint shards
Progress  5.49s/it █████████ 100% 6/6 00:32 00:00 Loading pipeline components...
21:28:27-084778 INFO     Offload: type=balanced op=init watermark=0.2-0.6 gpu=3.20-9.60:16.00 cpu=64.000 limit=0.00
                         always=[] never=[]
21:28:27-193981 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:27-200982 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:27-205981 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
21:28:27-208982 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
21:28:27-210981 INFO     Model class=WanPipeline modules=4 size=64.155
21:28:27-211981 INFO     Video load: cls=WanPipeline model="WAN 2.2 A14B T2V" time=62.28
21:28:27-232033 WARNING  Video: op=T2V init image not supported
21:28:27-237032 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:27-242032 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:27-244032 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
21:28:27-246032 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
21:28:29-468925 DEBUG    GC: current={'gpu': 0.28, 'ram': 29.8, 'oom': 0} prev={'gpu': 0.28, 'ram': 29.42} load={'gpu':
                         2, 'ram': 47} gc={'gpu': 0.0, 'py': 1373} fn=f:generate why=video time=2.22
21:28:29-470925 DEBUG    Video: cls=WanPipeline width=528 height=480 frames=17 steps=50
21:28:29-492431 DEBUG    Sampler: "Default" cls=UniPCMultistepScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.0001, 'beta_end': 0.02, 'beta_schedule': 'linear', 'trained_betas': None,
                         'solver_order': 2, 'prediction_type': 'flow_prediction', 'thresholding': False,
                         'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'predict_x0': True,
                         'solver_type': 'bh2', 'lower_order_final': True, 'disable_corrector': [], 'solver_p': None,
                         'use_karras_sigmas': False, 'use_exponential_sigmas': False, 'use_beta_sigmas': False,
                         'use_flow_sigmas': True, 'flow_shift': 3.0, 'timestep_spacing': 'linspace', 'steps_offset': 0,
                         'final_sigmas_type': 'zero', 'rescale_betas_zero_snr': False, 'use_dynamic_shifting': False,
                         'time_shift_type': 'exponential'}
21:28:29-514432 INFO     Processing modifiers: apply
21:28:29-518430 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:29-523430 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:29-526430 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
21:28:29-528430 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
21:28:29-533430 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:29-537431 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:28:29-539433 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
21:28:29-541431 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
21:28:29-542431 DEBUG    Network load: type=LoRA name="wan2_1-i2v-480p-pov-insertion-v1_0"
                         file="J:\AItraining\SDNextFresh\sdnext\models\Lora\wan2.1-i2v-480p-pov-insertion-v1.0.safetenso
                         rs" detected= method=diffusers scale=1.0 fuse=True
21:28:30-557393 DEBUG    Network load: type=LoRA loaded=['wan2_1-i2v-480p-pov-insertion-v1_0'] available={'transformer':
                         ['wan2_1-i2v-480p-pov-insertion-v1_0']} active=['wan2_1-i2v-480p-pov-insertion-v1_0']
                         scales=[1.0]
21:28:53-478076 TRACE    Server: alive=True requests=212 memory=44.25/63.59 status='idle' task='' timestamp=None
                         current='task(cjv9v0vlimbf88p)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=125
                         elapsed=120.9 eta=None progress=0
21:29:06-093255 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:29:06-098255 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:29:06-101255 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
21:29:06-102255 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
21:29:06-124759 INFO     Base: pipeline=WanPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt': 253, 'negative_prompt':
                         221, 'generator': 'cuda:[4046098804]', 'num_inference_steps': 50, 'num_frames': 17,
                         'output_type': 'pil', 'width': 528, 'height': 480, 'parser': 'fixed'}
21:29:21-157890 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:29:21-166888 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
21:29:27-136382 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
21:29:27-139383 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
Progress ?it/s                                              0% 0/50 00:06 ? Base
21:29:33-316829 ERROR    Processing: step=base args={'prompt': '<lora:wan2_1-i2v-480p-pov-insertion-v1_0:1.0> A man
                         appears and inserts his penis into her pussy, 1 beautiful girl, kneeling Best quality, 4k, 8k,
                         ultra high resolution, raw photo in high dynamic range, sharp focus, intricate texture, skin
                         imperfections', 'negative_prompt': 'EasyNegative, worst quality, low quality, normal quality,
                         child, painting, drawing, sketch, cartoon, anime, render, 3d, blurry, deformed, disfigured,
                         morbid, mutated, bad anatomy, bad art, towel, sheet, blanket, 3 fingers', 'generator':
                         [<torch._C.Generator object at 0x000001F50FEDC3B0>], 'callback_on_step_end': <function
                         diffusers_callback at 0x000001F4FD89CF40>, 'callback_on_step_end_tensor_inputs': ['latents',
                         'prompt_embeds', 'negative_prompt_embeds'], 'num_inference_steps': 50, 'num_frames': 17,
                         'output_type': 'pil', 'width': 528, 'height': 480} Expected all tensors to be on the same
                         device, but found at least two devices, cuda:0 and cpu!
21:29:33-319832 ERROR    Processing: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│J:\AItraining\SDNextFresh\sdnext\modules\processing_diffusers.py:147 in process_base                                  │
│                                                                                                                      │
│  146 │   │   else:                                                                                                   │
│❱ 147 │   │   │   output = shared.sd_model(**base_args)                                                               │
│  148 │   │   if isinstance(output, dict):                                                                            │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\utils\_contextlib.py:116 in decorate_context            │
│                                                                                                                      │
│  115 │   │   with ctx_factory():                                                                                     │
│❱ 116 │   │   │   return func(*args, **kwargs)                                                                        │
│  117                                                                                                                 │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan.py:593 in __call__       │
│                                                                                                                      │
│  592 │   │   │   │   with current_model.cache_context("cond"):                                                       │
│❱ 593 │   │   │   │   │   noise_pred = current_model(                                                                 │
│  594 │   │   │   │   │   │   hidden_states=latent_model_input,                                                       │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl         │
│                                                                                                                      │
│  1750 │   │   else:                                                                                                  │
│❱ 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                            │
│  1752                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                 │
│                                                                                                                      │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                        │
│❱ 1762 │   │   │   return forward_call(*args, **kwargs)                                                               │
│  1763                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\accelerate\hooks.py:175 in new_forward                        │
│                                                                                                                      │
│  174 │   │   else:                                                                                                   │
│❱ 175 │   │   │   output = module._old_forward(*args, **kwargs)                                                       │
│  176 │   │   return module._hf_hook.post_forward(module, output)                                                     │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\diffusers\models\transformers\transformer_wan.py:663 in forwa │
│                                                                                                                      │
│  662 │   │   │   for block in self.blocks:                                                                           │
│❱ 663 │   │   │   │   hidden_states = block(hidden_states, encoder_hidden_states, timestep_proj, rotary_emb)          │
│  664                                                                                                                 │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl         │
│                                                                                                                      │
│  1750 │   │   else:                                                                                                  │
│❱ 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                            │
│  1752                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                 │
│                                                                                                                      │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                        │
│❱ 1762 │   │   │   return forward_call(*args, **kwargs)                                                               │
│  1763                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\diffusers\models\transformers\transformer_wan.py:474 in forwa │
│                                                                                                                      │
│  473 │   │   │   shift_msa, scale_msa, gate_msa, c_shift_msa, c_scale_msa, c_gate_msa = (                            │
│❱ 474 │   │   │   │   self.scale_shift_table + temb.float()                                                           │
│  475 │   │   │   ).chunk(6, dim=1)                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
21:29:33-597139 DEBUG    Analyzed: model="Diffusers\lopho/Wan2.2-T2V-A14B-Diffusers_bf16_vae" type=wanai
                         class=WanPipeline size=253828884 mtime="2025-08-15 16:56:18" modules=[name="vae"
                         cls=AutoencoderKLWan config=True device=cpu dtype=torch.bfloat16 params=126892531 modules=260,
                         name="text_encoder" cls=T5EncoderModel config=True device=cpu dtype=torch.bfloat16
                         params=5680863232 modules=463, name="tokenizer" cls=T5TokenizerFast config=False,
                         name="transformer" cls=WanTransformer3DModel config=True device=cuda:0 dtype=torch.bfloat16
                         params=14288491584 modules=1138, name="scheduler" cls=UniPCMultistepScheduler config=True,
                         name="transformer_2" cls=WanTransformer3DModel config=True device=cpu dtype=torch.bfloat16
                         params=14288491584 modules=1138, name="boundary_ratio" cls=float config=False,
                         name="expand_timesteps" cls=bool config=False, name="_name_or_path" cls=str config=False,
                         name="_class_name" cls=str config=False, name="_diffusers_version" cls=str config=False]
21:29:33-599139 INFO     Processing modifiers: unapply
21:29:33-916400 DEBUG    GC: current={'gpu': 9.89, 'ram': 45.0, 'oom': 0} prev={'gpu': 11.56, 'ram': 44.94} load={'gpu':
                         62, 'ram': 71} gc={'gpu': 1.67, 'py': 180} fn=process_base:nextjob why=threshold time=0.32
21:29:33-918405 INFO     Processed: images=0 its=0.00 ops=['video']
21:29:33-918405 DEBUG    Processed: timers={'total': 85.93, 'post': 64.07, 'te': 15.0, 'offload': 6.05, 'gc': 0.44,
                         'process': 0.32}
21:29:33-919406 DEBUG    Processed: memory={'ram': {'total': 63.59, 'used': 45.0, 'free': 19}, 'gpu': {'used': 9.89,
                         'total': 15.92, 'active': 9.5, 'peak': 10.89, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}
21:29:33-920406 ERROR    Video: processing failed
```

### Backend

Original

### Compute

AMD ROCm

### Interface

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Update to latest release to resolve "tuple" error.
But root cause is that your model failed to load - and I don't recognize that model. Does it fail with official Wan model?

**Comment by sgtsixpack** [comment]
I ran sdnext with --update, just before I posted this.  Is this not updated?

I will try again tommorrow.

I thought the only model possible to run was from the selection tab.  Its wan 2.2 14b iirc,  I think I may have been running the txt to vid model on an image to vid.

**Comment by vladmandic** [comment]
you have Aug 15th version, there was a new release earlier today that cleans up some of the errors.

**Comment by sgtsixpack** [comment]
Version: app=sd.next updated=2025-08-20 hash=3ec0d35d branch=master

I've updated and get the same error, tried with --ignore and --deviceid 0 command, the same.

Also when I tried to save a style of my prompt in the video tab; it saved the prompt from the txt tab instead.

**Comment by CalamitousFelicitousness** [comment]
The two devices issue has nothing to do with your GPUs.

First, resolve the error with the VAE by setting it back to default, don't use your own supplied VAE or any other pre-downloaded components with any of the video models, whether it's T2I or T/I2V, let SDnext download and load what it needs.

Second, after you do that, run SDnext with `--debug` flag, use the video tab to reproduce the tensor error, and submit log here.

Then we'll go from there.

And don't mix in random problem like styles saving in here, stay on track of what this issue is about, submit a separate issue for the styles if you need to.

**Comment by sgtsixpack** [comment]
Sorry, here is more code from updated install, no lora; (I'm not using that custom model "cyberrealisticponyv125 with the video tab just in the txt to img ang img to img tabs and control tab now):

J:\AItraining\SDNextFresh\sdnext>webui.bat --use-zluda --debug --autolaunch
Using VENV: J:\AItraining\SDNextFresh\sdnext\venv
13:21:17-171936 INFO     Starting SD.Next
13:21:17-173941 INFO     Logger: file="J:\AItraining\SDNextFresh\sdnext\sdnext.log" level=DEBUG host="9800x3d9070xt"
                         size=81 mode=create
13:21:17-173941 INFO     Python: version=3.11.9 platform=Windows
                         bin="J:\AItraining\SDNextFresh\sdnext\venv\Scripts\python.exe"
                         venv="J:\AItraining\SDNextFresh\sdnext\venv"
13:21:17-342168 INFO     Version: app=sd.next updated=2025-08-20 hash=3ec0d35d branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master ui=main
13:21:17-986772 INFO     Version: app=sd.next latest=2025-08-20T18:42:31Z hash=3ec0d35d branch=master
13:21:17-994772 INFO     Platform: arch=AMD64 cpu=AMD64 Family 26 Model 68 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.26100-SP0 python=3.11.9 locale=('English_United Kingdom', '1252')
                         docker=False
13:21:17-995772 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
13:21:17-996775 INFO     Args: ['--use-zluda', '--debug', '--autolaunch']
13:21:17-997773 DEBUG    Setting environment tuning
13:21:17-997773 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
13:21:17-998775 INFO     Verifying torch installation
13:21:18-001771 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
13:21:18-005772 INFO     ROCm: AMD toolkit detected
13:21:18-431819 INFO     ROCm: agents=['gfx1201']
13:21:18-432818 INFO     ROCm: version=6.4, using agent gfx1201
13:21:18-472059 INFO     ZLUDA load: path='J:\AItraining\SDNextFresh\sdnext\.zluda' nightly=False
13:21:20-859735 INFO     Install: verifying requirements
13:21:20-895711 DEBUG    Timestamp repository update time: Wed Aug 20 19:42:31 2025
13:21:20-896710 INFO     Startup: standard
13:21:20-896710 INFO     Verifying submodules
13:21:22-727020 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
13:21:22-788554 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
13:21:22-842051 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
13:21:22-929472 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
13:21:22-930469 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
13:21:23-023195 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
13:21:23-082248 DEBUG    Git submodule: wiki / master
13:21:23-138247 DEBUG    Installed packages: 187
13:21:23-139248 DEBUG    Extensions all: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
13:21:23-186553 DEBUG    Extension installer: builtin=True
                         file="J:\AItraining\SDNextFresh\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py"
13:21:23-231553 DEBUG    Extension installer: builtin=True
                         file="J:\AItraining\SDNextFresh\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.
                         py"
13:21:23-254636 DEBUG    Extensions all: []
13:21:23-255637 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
13:21:23-280982 INFO     Install: verifying requirements
13:21:23-282982 DEBUG    Setup complete without errors: 1755778883
13:21:23-285981 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
13:21:23-286984 INFO     Installer time: total=9.92 torch=2.70 git=2.40 submodules=2.22 latest=0.81 amd=0.61 branch=0.41
                         base=0.23 version=0.17 files=0.13 installed=0.05 requirements=0.05
13:21:23-287981 INFO     Command line args: ['--use-zluda', '--debug', '--autolaunch'] autolaunch=True use_zluda=True
                         debug=True args=[]
13:21:23-287981 DEBUG    Env flags: []
13:21:23-288982 DEBUG    Starting module: <module 'webui' from 'J:\\AItraining\\SDNextFresh\\sdnext\\webui.py'>
13:21:34-583928 INFO     Torch: torch==2.7.1+cu118 torchvision==0.22.1+cu118
13:21:34-586928 INFO     Packages: diffusers==0.36.0.dev0 transformers==4.55.2 accelerate==1.10.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2
13:21:35-114301 DEBUG    ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']
13:21:35-220873 DEBUG    State initialized: id=2066887769232
13:21:35-730109 INFO     Device detect: memory=16.0 default=balanced
13:21:35-735113 DEBUG    Read: file="J:\AItraining\SDNextFresh\sdnext\config.json" json=15 bytes=763 time=0.000
                         fn=<module>:load
13:21:35-736109 INFO     Engine: backend=Backend.DIFFUSERS compute=zluda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
13:21:35-738111 DEBUG    Read: file="html\reference.json" json=96 bytes=47601 time=0.001
                         fn=_call_with_frames_removed:<module>
13:21:35-739110 DEBUG    Torch cuDNN: benchmark=True
13:21:35-740214 DEBUG    Torch attention: type="sdpa" flash=True memory=False math=True
13:21:35-741218 DEBUG    Torch attention: type="dynamic attention"
13:21:35-921651 INFO     Torch parameters: backend=zluda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass optimization="Scaled-Dot-Product"
13:21:36-090650 INFO     Device: device=AMD Radeon RX 9070 XT [ZLUDA] n=1 arch=compute_37 capability=(8, 8) cuda=11.8
                         cudnn=90100 driver=
13:21:36-249339 DEBUG    Entering start sequence
13:21:36-251340 DEBUG    Initializing
13:21:36-253339 DEBUG    Read: file="metadata.json" json=16 bytes=20145 time=0.000 fn=initialize:init_metadata
13:21:36-254339 DEBUG    Read: file="cache.json" json=2 bytes=2049 time=0.000 fn=initialize:init_cache
13:21:36-302453 INFO     Available VAEs: path="models\VAE" items=0
13:21:36-303449 INFO     Available UNets: path="models\UNET" items=0
13:21:36-304449 INFO     Available TEs: path="models\Text-encoder" items=0
13:21:36-309449 INFO     Available Models: safetensors="models\Stable-diffusion":8 diffusers="models\Diffusers":4
                         reference=96 items=12 time=0.00
13:21:36-323449 INFO     Available LoRAs: path="models\Lora" items=8 folders=2 time=0.00
13:21:36-346448 INFO     Available Styles: path="models\styles" items=347 time=0.02
13:21:36-427190 INFO     Available Detailer: path="models\yolo" items=11 downloaded=3
13:21:36-428190 DEBUG    Extensions: disabled=['sdnext-modernui']
13:21:36-428190 INFO     Load extensions
13:21:37-064826 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
13:21:37-068838 DEBUG    Extensions init time: total=0.64 sd-webui-agent-scheduler=0.49
13:21:37-076878 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.000 fn=__init__:__init__
13:21:37-078879 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.001
                         fn=__init__:find_scalers
13:21:37-079879 DEBUG    Available chaiNNer: path="models\chaiNNer" defined=25 discovered=0 downloaded=0
13:21:37-081881 INFO     Available Upscalers: items=72 downloaded=0 user=0 time=0.01 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
13:21:37-088879 INFO     Huggingface init: transfer=rust parallel=True direct=False token="None"
                         cache="models\huggingface"
13:21:37-092878 WARNING  Cache location changed: previous="C:\Users\SgtSixpack\.cache\huggingface\hub" size=445 MB
13:21:37-125525 DEBUG    Huggingface cache: path="models\huggingface" size=210893 MB
13:21:37-125525 DEBUG    UI start sequence
13:21:37-126526 INFO     UI locale: name="Auto"
13:21:37-127526 INFO     UI theme: type=Standard name="black-teal" available=13
13:21:37-131525 DEBUG    UI theme: css="J:\AItraining\SDNextFresh\sdnext\javascript\black-teal.css" base="sdnext.css"
                         user="None"
13:21:37-133525 DEBUG    UI initialize: txt2img
13:21:37-174098 DEBUG    Networks: type="model" items=107 subfolders=4 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Reference', 'J:\\AItraining\\SDNextFresh\\sdnext\\models\\Stable-diffusion'] list=0.03
                         thumb=0.00 desc=0.00 info=0.00 workers=12
13:21:37-176102 DEBUG    Networks: type="lora" items=8 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.01
                         thumb=0.00 desc=0.00 info=0.00 workers=12
13:21:37-182102 DEBUG    Networks: type="style" items=347 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.02 thumb=0.00 desc=0.00 info=0.00 workers=12
13:21:37-184175 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models\\wildcards']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
13:21:37-185174 DEBUG    Networks: type="embedding" items=1 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
13:21:37-187176 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
13:21:37-188178 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
13:21:37-299199 DEBUG    UI initialize: img2img
13:21:37-556548 DEBUG    UI initialize: control models="models\control"
13:21:37-657061 DEBUG    Script: fn="extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py" type=control
                         skip
13:21:37-773376 DEBUG    UI initialize: video
13:21:38-009052 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.001 fn=__init__:read_from_file
13:21:38-011056 DEBUG    Settings: sections=24 settings=351/555 quicksettings=0
13:21:38-268894 INFO     Extension list is empty: refresh required
13:21:38-553218 DEBUG    Extension list: processed=4 installed=4 enabled=4 disabled=0 visible=4 hidden=0
13:21:38-826062 DEBUG    Root paths: ['J:\\AItraining\\SDNextFresh\\sdnext', 'models']
13:21:38-884935 INFO     Local URL: http://127.0.0.1:7860/
13:21:38-886659 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
13:21:38-887663 DEBUG    API initialize
13:21:38-986171 INFO     [AgentScheduler] Task queue is empty
13:21:38-987170 INFO     [AgentScheduler] Registering APIs
13:21:39-050248 DEBUG    Scripts setup: time=0.371 ['XYZ Grid:0.167']
13:21:39-051248 DEBUG    Model metadata: file="metadata.json" no changes
13:21:39-053252 DEBUG    Model requested: fn=threading.py:run:<lambda>
13:21:39-054250 INFO     Load model: select="cyberrealisticPony_v125 [b83dffe522]"
13:21:39-055249 INFO     Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="J:\AItraining\SDNextFresh\sdnext\models\Stable-diffusion\cyberrealisticPony_v125.safetens
                         ors"
13:21:39-055249 DEBUG    Cache clear
13:21:39-183088 DEBUG    UI: connected
Progress  1.39it/s █████████ 100% 7/7 00:05 00:00 Loading pipeline components...
13:21:44-932602 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'extract_ema': False, 'config':
                         'configs/sdxl', 'use_safetensors': True, 'cache_dir': 'models\\huggingface'}
13:21:44-936603 INFO     Network load: type=embeddings loaded=0 skipped=1 time=0.00
13:21:44-936603 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}
13:21:44-937605 DEBUG    Setting model: attention="Scaled-Dot-Product"
13:21:44-942602 INFO     Offload: type=balanced op=init watermark=0.2-0.6 gpu=3.20-9.60:16.00 cpu=64.000 limit=0.00
                         always=[] never=[]
13:21:44-955654 DEBUG    Module: name=unet cls=UNet2DConditionModel size=4.782 params=2567463684 quant=None
13:21:44-958656 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=1.294 params=694659840
                         quant=None
13:21:44-960654 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.229 params=123060480 quant=None
13:21:44-962654 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None
13:21:44-963655 INFO     Model class=StableDiffusionXLPipeline modules=4 size=6.461
13:21:44-964740 INFO     Load model: family=sdxl time={'total': 5.91, 'load': 5.88} native=1024 memory={'ram': {'total':
                         63.59, 'used': 8.1, 'free': 55}, 'gpu': {'used': 0.28, 'total': 15.92, 'active': 0.01, 'peak':
                         0.01, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load'}
13:21:44-967743 DEBUG    Script init: ['task_scheduler.py:app_started=0.07']
13:21:44-968741 INFO     Startup time: total=40.96 libraries=8.08 launch=6.70 numpy=6.45 installer=6.43 checkpoint=5.92
                         torch=3.49 gradio=1.00 extensions=0.64 ui-extensions=0.54 ui-img2img=0.23 bnb=0.19
                         ui-networks=0.17 ui-control=0.16 app-started=0.11 diffusers=0.10 ui-txt2img=0.10 ui-models=0.08
                         detailer=0.08 onnx=0.08 ui-video=0.07 ui-defaults=0.06 api=0.05 samplers=0.05
13:21:44-970741 INFO     Launching browser
13:21:44-971741 DEBUG    Save: file="J:\AItraining\SDNextFresh\sdnext\config.json" json=15 bytes=745 time=0.005
13:22:29-957743 DEBUG    Cache clear
13:22:29-957743 DEBUG    Current model: {'ram': {'total': 63.59, 'used': 8.1, 'free': 55}, 'gpu': {'used': 0.28,
                         'total': 15.92, 'active': 0.01, 'peak': 0.01, 'retries': 0, 'oom': 0, 'swap': 0}, 'job':
                         'Load'}
13:22:30-334970 DEBUG    GC: current={'gpu': 0.28, 'ram': 8.07, 'oom': 0} prev={'gpu': 0.28, 'ram': 8.07} load={'gpu':
                         2, 'ram': 13} gc={'gpu': 0.0, 'py': 43775} fn=load_model:unload_model_weights why=unload
                         time=0.25
13:22:30-336971 DEBUG    Unload model: {'ram': {'total': 63.59, 'used': 8.07, 'free': 56}, 'gpu': {'used': 0.28,
                         'total': 15.92, 'active': 0.01, 'peak': 0.01, 'retries': 0, 'oom': 0, 'swap': 0}, 'job':
                         'Load'} after
Progress 64.82it/s ██████████████ 100% 3/3 00:00 00:00 Loading checkpoint shards
Progress ?it/s ████████████████████████████ 100% 12/12 00:00 ? Fetching 12 files
Progress  2.42s/it ████████████ 100% 12/12 00:29 00:00 Loading checkpoint shards
Progress  2.85s/it ████████████ 100% 12/12 00:34 00:00 Loading checkpoint shards
Progress  6.07s/it █████████ 100% 6/6 00:36 00:00 Loading pipeline components...
13:23:37-713743 INFO     Offload: type=balanced op=init watermark=0.2-0.6 gpu=3.20-9.60:16.00 cpu=64.000 limit=0.00
                         always=[] never=[]
13:23:37-776743 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:37-782743 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:37-786817 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
13:23:37-788817 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
13:23:37-791818 INFO     Model class=WanPipeline modules=4 size=64.155
13:23:37-792823 INFO     Video load: cls=WanPipeline model="WAN 2.2 A14B I2V" time=67.36
13:23:37-818879 DEBUG    Image resize: source=448:480 target=448:480 mode="Crop" upscaler="None" type=pil time=0.01
                         fn=f:generate
13:23:37-825879 DEBUG    Video: op=I2V init=<PIL.Image.Image image mode=RGB size=448x480 at 0x1E145B132D0>
                         resized=<PIL.Image.Image image mode=RGB size=448x480 at 0x1E1950DF690>
13:23:37-836878 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:37-841881 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:37-843878 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
13:23:37-845879 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
13:23:39-603460 DEBUG    GC: current={'gpu': 0.28, 'ram': 34.51, 'oom': 0} prev={'gpu': 0.28, 'ram': 34.11} load={'gpu':
                         2, 'ram': 54} gc={'gpu': 0.0, 'py': 384} fn=f:generate why=video time=1.76
13:23:39-605594 DEBUG    Video: cls=WanPipeline width=448 height=480 frames=17 steps=50
13:23:39-620762 DEBUG    Sampler: "Default" cls=UniPCMultistepScheduler config={'num_train_timesteps': 1000,
                         'beta_start': 0.0001, 'beta_end': 0.02, 'beta_schedule': 'linear', 'trained_betas': None,
                         'solver_order': 2, 'prediction_type': 'flow_prediction', 'thresholding': False,
                         'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'predict_x0': True,
                         'solver_type': 'bh2', 'lower_order_final': True, 'disable_corrector': [], 'solver_p': None,
                         'use_karras_sigmas': False, 'use_exponential_sigmas': False, 'use_beta_sigmas': False,
                         'use_flow_sigmas': True, 'flow_shift': 3.0, 'timestep_spacing': 'linspace', 'steps_offset': 0,
                         'final_sigmas_type': 'zero', 'rescale_betas_zero_snr': False, 'use_dynamic_shifting': False,
                         'time_shift_type': 'exponential'}
13:23:39-640762 INFO     Processing modifiers: apply
13:23:39-645765 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:39-650761 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:39-653762 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
13:23:39-655762 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
13:23:39-659761 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:39-663761 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:39-665761 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
13:23:39-667762 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
13:23:39-671761 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:39-675763 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:39-677761 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
13:23:39-679762 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
13:23:39-695769 INFO     Base: pipeline=WanPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt': 20, 'negative_prompt':
                         0, 'generator': 'cuda:[2694366483]', 'num_inference_steps': 50, 'num_frames': 17,
                         'output_type': 'pil', 'width': 448, 'height': 480, 'parser': 'fixed'}
13:23:45-607612 TRACE    Server: alive=True requests=173 memory=35.75/63.59 status='idle' task='' timestamp=None
                         current='task(nohbm9loam1ht8n)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=130
                         elapsed=126.55 eta=None progress=0
13:23:51-431038 DEBUG    Module: name=transformer cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:51-440037 DEBUG    Module: name=transformer_2 cls=WanTransformer3DModel size=26.669 params=14288491584 quant=None
13:23:52-954235 DEBUG    Module: name=text_encoder cls=T5EncoderModel size=10.581 params=5680863232 quant=None
13:23:52-957235 DEBUG    Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
Progress ?it/s                                              0% 0/50 00:22 ? Base
13:24:15-581555 ERROR    Processing: step=base args={'prompt': '1 girl, crosses legs', 'negative_prompt': '',
                         'generator': [<torch._C.Generator object at 0x000001E1917B4B50>], 'callback_on_step_end':
                         <function diffusers_callback at 0x000001E1483E2480>, 'callback_on_step_end_tensor_inputs':
                         ['latents', 'prompt_embeds', 'negative_prompt_embeds'], 'num_inference_steps': 50,
                         'num_frames': 17, 'output_type': 'pil', 'width': 448, 'height': 480} Expected all tensors to be
                         on the same device, but found at least two devices, cuda:0 and cpu!
13:24:15-584032 ERROR    Processing: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│J:\AItraining\SDNextFresh\sdnext\modules\processing_diffusers.py:148 in process_base                                  │
│                                                                                                                      │
│  147 │   │   else:                                                                                                   │
│❱ 148 │   │   │   output = shared.sd_model(**base_args)                                                               │
│  149 │   │   if isinstance(output, dict):                                                                            │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\utils\_contextlib.py:116 in decorate_context            │
│                                                                                                                      │
│  115 │   │   with ctx_factory():                                                                                     │
│❱ 116 │   │   │   return func(*args, **kwargs)                                                                        │
│  117                                                                                                                 │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan.py:593 in __call__       │
│                                                                                                                      │
│  592 │   │   │   │   with current_model.cache_context("cond"):                                                       │
│❱ 593 │   │   │   │   │   noise_pred = current_model(                                                                 │
│  594 │   │   │   │   │   │   hidden_states=latent_model_input,                                                       │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl         │
│                                                                                                                      │
│  1750 │   │   else:                                                                                                  │
│❱ 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                            │
│  1752                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                 │
│                                                                                                                      │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                        │
│❱ 1762 │   │   │   return forward_call(*args, **kwargs)                                                               │
│  1763                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\accelerate\hooks.py:175 in new_forward                        │
│                                                                                                                      │
│  174 │   │   else:                                                                                                   │
│❱ 175 │   │   │   output = module._old_forward(*args, **kwargs)                                                       │
│  176 │   │   return module._hf_hook.post_forward(module, output)                                                     │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\diffusers\models\transformers\transformer_wan.py:663 in forwa │
│                                                                                                                      │
│  662 │   │   │   for block in self.blocks:                                                                           │
│❱ 663 │   │   │   │   hidden_states = block(hidden_states, encoder_hidden_states, timestep_proj, rotary_emb)          │
│  664                                                                                                                 │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl         │
│                                                                                                                      │
│  1750 │   │   else:                                                                                                  │
│❱ 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                            │
│  1752                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                 │
│                                                                                                                      │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                        │
│❱ 1762 │   │   │   return forward_call(*args, **kwargs)                                                               │
│  1763                                                                                                                │
│                                                                                                                      │
│J:\AItraining\SDNextFresh\sdnext\venv\Lib\site-packages\diffusers\models\transformers\transformer_wan.py:474 in forwa │
│                                                                                                                      │
│  473 │   │   │   shift_msa, scale_msa, gate_msa, c_shift_msa, c_scale_msa, c_gate_msa = (                            │
│❱ 474 │   │   │   │   self.scale_shift_table + temb.float()                                                           │
│  475 │   │   │   ).chunk(6, dim=1)                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
13:24:15-848722 DEBUG    Analyzed: model="cyberrealisticPony_v125" type=wanai class=WanPipeline size=6938041144
                         mtime="2025-08-16 12:49:41" modules=[name="vae" cls=AutoencoderKLWan config=True device=cpu
                         dtype=torch.bfloat16 params=126892531 modules=260, name="text_encoder" cls=T5EncoderModel
                         config=True device=cpu dtype=torch.bfloat16 params=5680863232 modules=463, name="tokenizer"
                         cls=T5TokenizerFast config=False, name="transformer" cls=WanTransformer3DModel config=True
                         device=cuda:0 dtype=torch.bfloat16 params=14288491584 modules=1138, name="scheduler"
                         cls=UniPCMultistepScheduler config=True, name="transformer_2" cls=WanTransformer3DModel
                         config=True device=cpu dtype=torch.bfloat16 params=14288491584 modules=1138,
                         name="boundary_ratio" cls=float config=False, name="expand_timesteps" cls=bool config=False]
13:24:15-850723 INFO     Processing modifiers: unapply
13:24:16-144279 DEBUG    GC: current={'gpu': 9.88, 'ram': 45.72, 'oom': 0} prev={'gpu': 11.15, 'ram': 45.72}
                         load={'gpu': 62, 'ram': 72} gc={'gpu': 1.27, 'py': 174} fn=process_base:nextjob why=threshold
                         time=0.29
13:24:16-145278 INFO     Processed: images=0 its=0.00 ops=['video']
13:24:16-146281 DEBUG    Processed: timers={'total': 50.2, 'post': 36.19, 'te': 11.7, 'offload': 1.59, 'gc': 0.37,
                         'process': 0.29}
13:24:16-147277 DEBUG    Processed: memory={'ram': {'total': 63.59, 'used': 45.72, 'free': 18}, 'gpu': {'used': 9.88,
                         'total': 15.92, 'active': 9.49, 'peak': 10.52, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}
13:24:16-148278 ERROR    Video: processing failed

**Comment by CalamitousFelicitousness** [comment]
Now enable SDNQ quantization for Model and TE in INT8.

<img width="535" height="433" alt="Image" src="https://github.com/user-attachments/assets/29f1211c-5fa7-4c69-858c-9dff7df017b6" />

Also, our Discord is full of these exact issues that were already resolved and explained, search and read them.

**Comment by sgtsixpack** [comment]
Problem solved but the issue is now the same as another thread in the forum.  I have garbled output.:  https://github.com/vladmandic/sdnext/issues/4111
