### ISSUE TITLE
[Issue]: Using ROCm7 on Windows video generation halts during text encode

### ISSUE THREAD

**Issue by burretploof** [vladmandic/sdnext#4183]
### Issue Description

When attempting to generate I2I video (with FramePack, in this example) while using ROCm 7 preview PyTorch wheels on Windows, the generation will seemingly halt during the "text encode" stage. It throws no error and task manager shows no relevant GPU usage. Power draw I'm monitoring using a smart plug confirms that there's no heavy activity.

I'll attach screenshots in addition to the logs, since the latter don't show the relevant stage.

<img width="1113" height="626" alt="Image" src="https://github.com/user-attachments/assets/75b6e604-671b-4fab-95d6-80119f7c0b03" />

<img width="724" height="657" alt="Image" src="https://github.com/user-attachments/assets/ee75ef5d-bdb7-4c45-8889-c649350b83b6" />

### Version Platform Description

I redacted submodule updates etc. and only kept platform info. Browser is Firefox.

2025-09-03 12:25:55,028 | Burret-PC | sd | INFO | launch | Starting SD.Next
2025-09-03 12:25:55,032 | Burret-PC | sd | INFO | installer | Logger: file="E:\Work\LLM\sdnext-rocm\sdnext.log" level=DEBUG host="Burret-PC" size=77 mode=create
2025-09-03 12:25:55,034 | Burret-PC | sd | INFO | installer | Python: version=3.12.11 platform=Windows bin="E:\Work\LLM\sdnext-rocm\venv\Scripts\python.exe" venv="E:\Work\LLM\sdnext-rocm\venv"
2025-09-03 12:25:55,305 | Burret-PC | sd | INFO | installer | Version: app=sd.next updated=2025-09-01 hash=33c1d0f9 branch=dev url=https://github.com/vladmandic/sdnext/tree/dev ui=dev
2025-09-03 12:25:55,686 | Burret-PC | sd | INFO | installer | Version: app=sd.next latest=2025-09-03T02:05:06Z hash=777b46f3 branch=dev
2025-09-03 12:25:55,723 | Burret-PC | sd | INFO | launch | Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows release=Windows-11-10.0.26100-SP0 python=3.12.11 locale=('English_Germany', '1252') docker=False
2025-09-03 12:25:55,725 | Burret-PC | sd | DEBUG | installer | Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
2025-09-03 12:25:55,727 | Burret-PC | sd | INFO | launch | Args: ['--debug', '--use-rocm', '--use-nightly', '--skip-torch', '--experimental']
2025-09-03 12:25:55,727 | Burret-PC | sd | DEBUG | installer | Setting environment tuning
2025-09-03 12:25:55,728 | Burret-PC | sd | DEBUG | installer | Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
2025-09-03 12:26:13,437 | Burret-PC | sd | INFO | loader | Torch: torch==2.9.0a0+rocm7.0.0rc20250825 torchvision==0.24.0a0+rocm7.0.0rc20250825
2025-09-03 12:26:13,440 | Burret-PC | sd | INFO | loader | Packages: diffusers==0.35.0.dev0 transformers==4.56.0.dev0 accelerate==1.10.0 gradio==3.43.2 pydantic==1.10.21 numpy==1.26.4
2025-09-03 12:26:14,036 | Burret-PC | sd | DEBUG | __init__ | ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']
2025-09-03 12:26:14,544 | Burret-PC | sd | INFO | shared | Engine: backend=Backend.DIFFUSERS compute=rocm device=cuda attention="Scaled-Dot-Product" mode=no_grad
2025-09-03 12:26:14,561 | Burret-PC | sd | DEBUG | devices | Torch tunable: enabled=True tuning=True iterations=30 duration=1000 fn="models\tunable\tunable.csv" entries=41
2025-09-03 12:26:14,562 | Burret-PC | sd | DEBUG | devices | Torch attention: type="sdpa" flash=True memory=True math=True
2025-09-03 12:26:14,563 | Burret-PC | sd | DEBUG | devices | Torch attention: type="dynamic attention"
2025-09-03 12:26:14,741 | Burret-PC | sd | INFO | devices | Torch parameters: backend=rocm device=cuda config=Auto dtype=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[True, True] fp16=pass bf16=pass optimization="Scaled-Dot-Product"
2025-09-03 12:26:14,744 | Burret-PC | sd | INFO | shared | Device: device=AMD Radeon RX 9070 XT n=1 hip=7.0.51830-9aa982d6c
2025-09-03 12:26:15,128 | Burret-PC | sd | DEBUG | webui | Entering start sequence

### Relevant log output

```shell
2025-09-03 12:51:20,217 | Burret-PC | sd | DEBUG | sd_models | Cache clear
2025-09-03 12:51:20,218 | Burret-PC | sd | DEBUG | sd_models | Current model: {'ram': {'total': 63.92, 'used': 6.0, 'free': 58}, 'gpu': {'used': 0.2, 'total': 15.92, 'active': 0.0, 'peak': 0.11, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load'}
2025-09-03 12:51:20,593 | Burret-PC | sd | DEBUG | devices | GC: current={'gpu': 0.2, 'ram': 5.97, 'oom': 0} prev={'gpu': 0.2, 'ram': 5.97} load={'gpu': 1, 'ram': 9} gc={'gpu': 0.0, 'py': 64212} fn=load_model:unload_model_weights why=unload time=0.28
2025-09-03 12:51:20,595 | Burret-PC | sd | DEBUG | sd_models | Unload model: {'ram': {'total': 63.92, 'used': 5.97, 'free': 58}, 'gpu': {'used': 0.2, 'total': 15.92, 'active': 0.0, 'peak': 0.11, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load'} after
2025-09-03 12:51:20,596 | Burret-PC | sd | DEBUG | framepack_load | FramePack load: module=llm {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder': 'text_encoder'}
2025-09-03 12:51:20,597 | Burret-PC | sd | DEBUG | model_quant | Quantization: module="TE" type=sdnq mode=pre dtype=int8 matmul=False group_size=0 quant_conv=False matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default offload_mode=balanced non_blocking=True modules_to_not_convert=[] modules_dtype_dict={}
2025-09-03 12:51:34,761 | Burret-PC | sd | DEBUG | devices | GC: current={'gpu': 0.2, 'ram': 12.04, 'oom': 0} prev={'gpu': 1.84, 'ram': 12.26} load={'gpu': 1, 'ram': 19} gc={'gpu': 1.64, 'py': 131} fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.26
2025-09-03 12:51:35,488 | Burret-PC | sd | DEBUG | framepack_load | FramePack load: module=te {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder': 'text_encoder_2'}
2025-09-03 12:51:36,314 | Burret-PC | sd | DEBUG | framepack_load | FramePack load: module=vae {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder': 'vae'}
2025-09-03 12:51:37,361 | Burret-PC | sd | DEBUG | framepack_load | FramePack load: module=encoder {'repo': 'lllyasviel/flux_redux_bfl', 'subfolder': 'feature_extractor'} model={'repo': 'lllyasviel/flux_redux_bfl', 'subfolder': 'image_encoder'}
2025-09-03 12:51:37,928 | Burret-PC | sd | DEBUG | framepack_load | FramePack load: module=transformer {'repo': 'lllyasviel/FramePack_F1_I2V_HY_20250503', 'subfolder': ''}
2025-09-03 12:51:37,929 | Burret-PC | sd | DEBUG | model_quant | Quantization: module="Model" type=sdnq mode=pre dtype=int8 matmul=False group_size=0 quant_conv=False matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default offload_mode=balanced non_blocking=True modules_to_not_convert=[] modules_dtype_dict={}
2025-09-03 12:52:09,680 | Burret-PC | sd | DEBUG | devices | GC: current={'gpu': 0.2, 'ram': 31.04, 'oom': 0} prev={'gpu': 0.2, 'ram': 31.04} load={'gpu': 1, 'ram': 49} gc={'gpu': 0.0, 'py': 157} fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.27
2025-09-03 12:52:09,703 | Burret-PC | sd | INFO | framepack_load | FramePack load: model=FramepackHunyuanVideoPipeline variant="forward-only" type=hunyuanvideo time=49.11
2025-09-03 12:52:09,704 | Burret-PC | sd | INFO | sd_offload | Offload: type=balanced op=init watermark=0-0.6 gpu=0.00-9.60:16.00 cpu=64.000 limit=0.00 always=[] never=[]
2025-09-03 12:52:09,739 | Burret-PC | sd | DEBUG | sd_offload | Module: name=transformer cls=HunyuanVideoTransformer3DModelPacked size=12.007 params=12874314816 quant=QuantizationMethod.SDNQ
2025-09-03 12:52:09,746 | Burret-PC | sd | DEBUG | sd_offload | Module: name=text_encoder cls=LlamaModel size=7.479 params=7505186816 quant=QuantizationMethod.SDNQ
2025-09-03 12:52:09,752 | Burret-PC | sd | DEBUG | sd_offload | Module: name=image_processor cls=SiglipVisionModel size=0.798 params=428225600 quant=None
2025-09-03 12:52:09,757 | Burret-PC | sd | DEBUG | sd_offload | Module: name=vae cls=AutoencoderKLHunyuanVideo size=0.459 params=246478803 quant=None
2025-09-03 12:52:09,760 | Burret-PC | sd | DEBUG | sd_offload | Module: name=text_encoder_2 cls=CLIPTextModel size=0.229 params=123060480 quant=None
2025-09-03 12:52:09,760 | Burret-PC | sd | INFO | sd_offload | Model class=FramepackHunyuanVideoPipeline modules=5 size=20.972
2025-09-03 12:52:10,027 | Burret-PC | sd | DEBUG | devices | GC: current={'gpu': 0.2, 'ram': 31.04, 'oom': 0} prev={'gpu': 0.2, 'ram': 31.04} load={'gpu': 1, 'ram': 49} gc={'gpu': 0.0, 'py': 892} fn=load_model:load_model why=load time=0.27
2025-09-03 12:52:27,686 | Burret-PC | sd | TRACE | launch | Server: alive=True requests=532 memory=31.04/63.92 status='idle' task='' timestamp=None current='' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=1574 elapsed=1567.09 eta=None progress=0
2025-09-03 12:54:27,727 | Burret-PC | sd | TRACE | launch | Server: alive=True requests=556 memory=31.04/63.92 status='idle' task='' timestamp=None current='' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=1694 elapsed=1687.13 eta=None progress=0
2025-09-03 12:54:48,684 | Burret-PC | sd | INFO | framepack_wrappers | FramePack start: mode=i2v variant="forward-only" frames=34 sections=1 resolution=640 seed=2417301397 duration=2 teacache=True thres=0.15 cfgzero=True
2025-09-03 12:54:48,686 | Burret-PC | sd | INFO | framepack_wrappers | FramePack params: steps=25 start=1 end=1 vision=1 scale=1 distilled=10 rescale=0 shift=3
2025-09-03 12:54:48,702 | Burret-PC | sd | DEBUG | framepack_wrappers | FramePack prepare: input="1024x1024" resized="608x640" resolution=640 scale=1.0
2025-09-03 12:55:46,051 | Burret-PC | sd | TRACE | framepack_hijack | FramePack prompt: system=153 user=1 optimized=True unmodified=False mode=optimized
2025-09-03 12:56:27,771 | Burret-PC | sd | TRACE | launch | Server: alive=True requests=579 memory=29.74/63.92 status='idle' task='' timestamp=None current='task(pnfqxdbut89lhew)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=1814 elapsed=1807.18 eta=None progress=0
2025-09-03 12:58:27,816 | Burret-PC | sd | TRACE | launch | Server: alive=True requests=603 memory=29.74/63.92 status='idle' task='' timestamp=None current='task(pnfqxdbut89lhew)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=1934 elapsed=1927.22 eta=None progress=0
2025-09-03 13:00:27,862 | Burret-PC | sd | TRACE | launch | Server: alive=True requests=627 memory=29.74/63.92 status='idle' task='' timestamp=None current='task(pnfqxdbut89lhew)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=2054 elapsed=2047.27 eta=None progress=0
2025-09-03 13:02:27,911 | Burret-PC | sd | TRACE | launch | Server: alive=True requests=651 memory=29.74/63.92 status='idle' task='' timestamp=None current='task(pnfqxdbut89lhew)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=2174 elapsed=2167.31 eta=None progress=0
2025-09-03 13:04:27,954 | Burret-PC | sd | TRACE | launch | Server: alive=True requests=674 memory=29.74/63.92 status='idle' task='' timestamp=None current='task(pnfqxdbut89lhew)' id='' job=0 jobs=0 total=2 step=0 steps=0 queued=0 uptime=2294 elapsed=2287.36 eta=None progress=0
2025-09-03 13:06:22,552 | Burret-PC | sd | TRACE | webui | State history: uptime=2409 jobs=4 tasks=0 latents=0 images=0
2025-09-03 13:06:22,553 | Burret-PC | sd | INFO | webui | Exiting
```

### Backend

Diffusers

### Compute

AMD ROCm

### Interface

Standard

### Branch

Dev

### Model

Any Video Model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
Try disabling non_blocking. It can have major issues with non-nvidia gpus.

**Comment by burretploof** [comment]
> Try disabling non_blocking. It can have major issues with non-nvidia gpus.

Non-blocking move operations, right?
With that deactivated, the result is unfortunately the same!

**Comment by Disty0** [comment]
> Non-blocking move operations, right?

Yep, that is the setting i was talking about.

> Torch tunable: enabled=True tuning=True

Tunableop does use quite a lot of memory and takes quite a lot of time to tune, try disabling it.


Text encoder shouldn't use 48 GB VRAM even at FP32.

**Comment by burretploof** [comment]
> > Non-blocking move operations, right?
> 
> Yep, that is the setting i was talking about.
> 
> > Torch tunable: enabled=True tuning=True
> 
> Tunableop does use quite a lot of memory and takes quite a lot of time to tune, try disabling it.
> 
> Text encoder shouldn't use 48 GB VRAM even at FP32.

Good call, but the end result is unfortunately the same. :(

I set it to false and restarted the server. Then I started a video generation with FramePack again and ten minutes in, the only activity was in the very beginning, for a few seconds, before halting again.

[sdnext.log](https://github.com/user-attachments/files/22131644/sdnext.log)

<img width="1113" height="626" alt="Image" src="https://github.com/user-attachments/assets/c4d7d8cc-d27c-46d2-af3a-854d968c3aa2" />

**Comment by vladmandic** [comment]
does this still happen with the latest therock torch wheels?
suggest using `webui --use-rocm --reinstall` to get updated torch.

**Comment by Matthew-X** [comment]
Similar issue here, but with RX 7900 XTX. When trying to do Image txt2image generation.
It now gets ROCm 7.2 and HIP 7.2 from somewhere and runs with it (At this time I've searched everywhere and I can't find any traces of ROCm 7.2 only 7.1.1 shows as released.) So perhaps this might be causing issues and making it incompatible? As I see that torch version is "torch==2.9.1+rocm7.11.0a20251204" which I'd assume is not compatible with ROCm/HIP 7.2?

> 07:19:10-853287 INFO     Version: app=sd.next updated=2025-12-05 commit=1cfb61809 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev kanvas=main ui=dev
07:19:11-393110 TRACE    Repository branches: active=dev available=['dev', 'master', 'upstream']
07:19:11-828181 INFO     Version: app=sd.next latest=2025-12-05T15:40:49Z hash=1cfb6180 branch=dev
07:19:11-850177 INFO     Platform: arch=AMD64 cpu=AMD64 Family 26 Model 68 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-11-10.0.26200-SP0 python=3.12.10 locale=('English_United States', '1252')
                         docker=False
07:19:11-851178 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
07:19:11-852177 INFO     Args: ['--use-rocm']
07:19:11-852177 DEBUG    Setting environment tuning
07:19:11-853177 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
07:19:11-854177 INFO     Verifying torch installation
07:19:11-854177 DEBUG    Torch overrides: cuda=False rocm=True ipex=False directml=False openvino=False zluda=False
HIP Library Path: C:\WINDOWS\System32\amdhip64_7.dll
07:19:11-885177 INFO     ROCm: agents=['gfx1100']
07:19:11-886178 INFO     ROCm: version=7.2, using agent gfx1100
07:19:11-886178 INFO     Python: version=3.12.10 platform=Windows bin="E:\Programs\sdnext\venv\Scripts\python.exe"
                         venv="E:\Programs\sdnext\venv"
07:19:16-757251 INFO     Torch backend: version="2.9.1+rocm7.11.0a20251204" type=ROCm HIP=7.2.53150-28254cb13e
07:19:16-758253 INFO     Torch detected: gpu="AMD Radeon RX 7900 XTX" vram=24560 arch=(11, 0) cores=48
07:19:16-759252 INFO     Torch detected: gpu="AMD Radeon(TM) Graphics" vram=37996 arch=(10, 3) cores=1
07:19:16-862255 INFO     Install: verifying requirements
07:19:16-889251 DEBUG    Timestamp repository update time: Sat Dec  6 04:40:49 2025
07:19:16-890251 INFO     Startup: standard
07:19:16-890251 INFO     Verifying submodules
07:19:18-522861 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
07:19:18-567368 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
07:19:18-610368 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main
07:19:18-653762 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
07:19:18-698972 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
07:19:18-770973 DEBUG    Git detached head detected: folder="wiki" reattach=master
07:19:18-771974 DEBUG    Git submodule: wiki / master
07:19:18-818971 DEBUG    Installed packages: 251
07:19:18-819971 DEBUG    Extensions all: ['sd-extension-chainner', 'sd-extension-system-info', 'sdnext-kanvas', 'sdnext-modernui',
                         'stable-diffusion-webui-rembg']
07:19:18-902972 DEBUG    Extension installer: builtin=True
                         file="E:\Programs\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py"
07:19:18-923976 DEBUG    Extensions all: []
07:19:18-923976 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info', 'sdnext-kanvas',
                         'sdnext-modernui', 'stable-diffusion-webui-rembg']
07:19:18-946972 INFO     Install: verifying requirements
07:19:18-949971 DEBUG    Setup complete without errors: 1764958759
07:19:18-951971 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
07:19:18-952972 INFO     Installer time: total=10.80 torch=4.91 git=2.02 submodules=1.91 latest=1.11 branch=0.30 base=0.13
                         version=0.13
07:19:18-953974 INFO     Command line args: ['--use-rocm'] use_rocm=True args=[]
07:19:18-954973 DEBUG    Env flags: []
07:19:18-954973 DEBUG    Starting module: <module 'webui' from 'E:\\Programs\\sdnext\\webui.py'>
07:19:18-969971 WARNING  Loader: torch is not built with distributed support
07:19:23-681299 INFO     Torch: torch==2.9.1+rocm7.11.0a20251204 torchvision==0.24.0+rocm7.11.0a20251204
07:19:23-682298 INFO     Packages: diffusers==0.36.0.dev0 transformers==4.57.1 accelerate==1.11.0 gradio==3.43.2 pydantic==1.10.21
                         numpy==2.1.2 cv2==4.12.0
07:19:24-009299 DEBUG    ONNX: version=1.23.2, available=['AzureExecutionProvider', 'CPUExecutionProvider']
07:19:24-079299 DEBUG    State initialized: id=2061900818448
07:19:24-126654 INFO     Device detect: memory=24.0 default=balanced optimization=highvram
07:19:24-127663 DEBUG    Triton: pass=False fn=<module>:has_triton time=0.00
07:19:24-129657 DEBUG    Read: file="E:\Programs\sdnext\config.json" json=14 bytes=687 time=0.000 fn=<module>:load
07:19:24-131659 INFO     Engine: backend=Backend.DIFFUSERS compute=rocm device=cuda attention="Scaled-Dot-Product" mode=no_grad
07:19:24-131659 DEBUG    Read: file="html\reference.json" json=143 bytes=69317 time=0.000 fn=_call_with_frames_removed:<module>
07:19:24-132659 DEBUG    Torch attention: type="sdpa" kernels=['Flash', 'Memory', 'Math'] overrides=[]
07:19:24-133658 DEBUG    Torch attention installed: flashattn=False sageattention=False
07:19:24-133658 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False xla=False
                         xformers=False
07:19:24-437857 DEBUG    Triton: pass=False fn=<module>:set_cuda_params time=0.00
07:19:24-439857 INFO     Torch parameters: backend=rocm device=cuda config=Auto dtype=torch.bfloat16 context=no_grad nohalf=False
                         nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass bf16=pass triton=fail
                         optimization="Scaled-Dot-Product"
07:19:24-444857 DEBUG    Quantization: registered=SDNQ
07:19:24-445859 INFO     Device: device=AMD Radeon RX 7900 XTX n=2 hip=7.2.53150-28254cb13e
07:19:24-531366 DEBUG    Entering start sequence
07:19:24-533370 DEBUG    Initializing

**Comment by Matthew-X** [comment]
Here's attempt at generating prompt "cat". It shows that Lora has been loaded into the GPU's memory but GPU just spikes at the beginning a bit and then full stops with this message being stuck in the terminal:

<img width="1630" height="920" alt="Image" src="https://github.com/user-attachments/assets/ce15267e-7103-4bba-8318-04b8bf8cd956" />

> 07:33:04-480962 INFO     UI: ready time=5847
07:33:23-756619 DEBUG    Select input: type=<class 'str'> source=None init=None mask=None mode=Image  time=0.00
07:33:24-108619 DEBUG    Sampler: "Default" cls=EulerAncestralDiscreteScheduler config={'num_train_timesteps': 1000, 'beta_start':
                         0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'trained_betas': None, 'prediction_type':
                         'epsilon', 'timestep_spacing': 'trailing', 'steps_offset': 1, 'rescale_betas_zero_snr': False,
                         'interpolation_type': 'linear', 'use_karras_sigmas': False, 'clip_sample': False, 'sample_max_value': 1.0,
                         'set_alpha_to_one': False, 'skip_prk_steps': True}
07:33:24-114619 INFO     Processing modifiers: apply
07:33:24-132617 DEBUG    Tokenizer: words=49408 file="configs/sdxl\tokenizer\vocab.json"
07:33:24-654913 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds': torch.Size([1,
                         77, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds': torch.Size([1, 77,
                         2048]), 'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator':
                         'cuda:[3604589167]', 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None,
                         'output_type': 'latent', 'width': 1024, 'height': 1024, 'parser': 'native'}
Progress ?it/s                                              0% 0/20 00:00 ? Base

**Comment by vladmandic** [comment]
is this still an issue with latest sdnext with new torch-rocm?

**Comment by burretploof** [comment]
It is different now. In the current version, with a recent build of ROCm, it throws an actual error - immediately this time.

<img width="1097" height="113" alt="Image" src="https://github.com/user-attachments/assets/2397534f-c0e0-4616-85c5-53e83508ee67" />

Regular image tasks, both t2i and i2i work perfectly fine.

The logs are attached.

[sdnext.log](https://github.com/user-attachments/files/26606234/sdnext.log)

**Comment by vladmandic** [comment]
ok, dev branch has been updated - this issue should be resolved, lets see what's next?

**Comment by burretploof** [comment]
It is now working properly, it seems. I was able to generate a short video using FramePack after these changes were implemented.

Thank you!
