### ISSUE TITLE
[Issue]: Error when trying wan2.2 A14b i2v

### ISSUE THREAD

**Issue by mkossigit** [vladmandic/sdnext#4190]
### Issue Description

Using t2v works fine, but then switching to i2v gets an error but no crash:  
RuntimeError: Given groups=1, weight of size [5120, 16, 1, 2, 2], expected input[1, 36, 5, 104, 60] to have 16 channels, but got 36 channels instead

Ran in --safe mode

18:09:53-116933 INFO     Starting SD.Next
18:09:53-119933 INFO     Logger: file="F:\VladStable2\automatic\sdnext.log" level=INFO host="KOSSI-Zen" size=5876657
                         mode=append
18:09:53-123565 INFO     Python: version=3.11.9 platform=Windows bin="F:\VladStable2\automatic\venv\Scripts\python.exe"
                         venv="F:\VladStable2\automatic\venv"
18:09:53-278569 INFO     Version: app=sd.next updated=2025-09-04 hash=c210c9344 branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev ui=dev
18:09:54-978279 INFO     Version: app=sd.next latest=2025-09-04T20:38:45Z hash=c210c934 branch=dev
18:09:54-986277 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.11.9 locale=('English_Australia', '1252')
                         docker=False
18:09:54-991279 INFO     Args: ['--upgrade', '--safe']
18:09:54-994298 INFO     Verifying torch installation
18:09:55-012294 INFO     CUDA: nVidia toolkit detected
18:09:55-178291 INFO     Install: verifying requirements
18:09:55-182292 INFO     Startup: standard
18:09:55-183293 INFO     Verifying submodules
18:10:18-061062 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
18:10:18-156059 INFO     Install: verifying requirements
18:10:18-160059 INFO     Updating Wiki
18:10:19-913800 INFO     Running in safe mode without user extensions
18:10:19-919826 INFO     Installer time: total=74.76 git=24.11 update=22.47 submodules=12.08 latest=1.85
                         sd-webui-agent-scheduler=1.81 stable-diffusion-webui-rembg=1.79
                         stable-diffusion-webui-images-browser=1.78 sd-extension-system-info=1.78
                         sd-extension-chainner=1.78 sdnext-modernui=1.77 wiki=1.75 branch=0.85 base=0.30
                         requirements=0.19 installed=0.19 version=0.15 files=0.07
18:10:19-930827 INFO     Command line args: ['--upgrade', '--safe'] upgrade=True safe=True args=[]
18:10:28-449260 INFO     Torch: torch==2.7.1+cu128 torchvision==0.22.1+cu128
18:10:28-453261 INFO     Packages: diffusers==0.36.0.dev0 transformers==4.56.0 accelerate==1.10.1 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2
18:10:29-142776 INFO     Device detect: memory=16.0 default=balanced
18:10:29-149777 WARNING  Setting validation: unknown=['cross_attention_options', 'schedulers_brownian_noise',
                         'multiple_tqdm', 'ad_save_images_before', 'cuda_compile_precompile', 'cuda_compile_verbose',
                         'schedulers_use_karras', 'tac_frequencyFunction', 'tac_undersocreReplacementExclusionList',
                         'tac_alwaysSpaceAtEnd', 'tac_alias.onlyShowAlias', 'tac_translation.searchByTranslation']
18:10:29-155776 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
18:10:29-199775 INFO     Torch parameters: backend=cuda device=cuda config=BF16 dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[True, True] fp16=pass
                         bf16=pass optimization="Scaled-Dot-Product"
18:10:29-254775 INFO     Device: device=NVIDIA GeForce RTX 4080 n=1 arch=sm_120 capability=(8, 9) cuda=12.8 cudnn=90701
                         driver=576.26
18:10:29-519949 INFO     Available VAEs: path="F:\StableDiffusion\stable-diffusion-webui\models\VAE" items=48
18:10:29-522952 INFO     Available UNets: path="models\UNET" items=0
18:10:29-524954 INFO     Available TEs: path="models\Text-encoder" items=2
18:10:29-529950 INFO     Available Models:
                         safetensors="F:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion":3
                         diffusers="models\Diffusers":1 reference=98 items=4 time=0.00
18:10:29-800556 INFO     Available LoRAs: path="F:\StableDiffusion\stable-diffusion-webui\models\Lora" items=1569
                         folders=13 time=0.26
18:10:29-828559 INFO     Available Styles: path="models\styles" items=308 time=0.03
18:10:29-907232 INFO     Available Detailer: path="models\yolo" items=12 downloaded=2
18:10:29-910233 INFO     Load extensions
18:10:30-472584 INFO     Available Upscalers: items=107 downloaded=58 user=35 time=0.02 types=['None', 'Resize',
                         'Latent', 'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN',
                         'SCUNet', 'Diffusion', 'SwinIR']
18:10:30-484586 INFO     Huggingface init: transfer=rust parallel=True direct=False token="hf_...oMzB"
                         cache="C:\Users\mkoss\huggingface"
18:10:30-538586 INFO     UI locale: name="Auto"
18:10:30-539586 INFO     UI theme: type=Standard name="black-teal" available=13
18:10:34-822039 INFO     Local URL: http://127.0.0.1:7860/
18:10:35-029037 INFO     Model: autoload=False
18:10:35-033039 INFO     Startup time: total=96.68 launch=27.33 numpy=27.27 installer=27.20 torch=5.98 ui-networks=1.60
                         libraries=1.49 ui-extensions=1.07 gradio=0.98 extensions=0.54 bnb=0.47 diffusers=0.45
                         ui-txt2img=0.40 ui-defaults=0.34 lora=0.27 ui-control=0.24 ui-img2img=0.16 ui-video=0.12
                         ui-models=0.12 app-started=0.10 api=0.10 samplers=0.09 detailer=0.08 cleanup=0.05
18:11:42-300241 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;
                         rv:142.0) Gecko/20100101 Firefox/142.0
18:11:42-303241 INFO     UI: ready time=13.28
18:12:35-132627 TRACE    Server: alive=True requests=53 memory=1.25/63.93 status='idle' task='' timestamp=None
                         current='' id=0 job=0 jobs=0 total=0 step=0 steps=0 queued=0 uptime=126 elapsed=None eta=None
                         progress=0
Progress  3.09s/it ██████████████ 100% 3/3 00:09 00:00 Loading checkpoint shards
Progress ?it/s ████████████████████████████ 100% 12/12 00:00 ? Fetching 12 files
Progress  3.94s/it ██████████    83% 10/12 00:39 00:07 Loading checkpoint shards18:14:35-298196 TRACE    Server: alive=True requests=77 memory=27.41/63.93 status='running' task='Load'
                         timestamp='20250905181328' current='task(cw3kmf3h9f5c7hz)' id='99bdbd31b2f3467' job=0 jobs=1
                         total=2 step=0 steps=0 queued=0 uptime=246 elapsed=67.16 eta=None progress=0
Progress  3.75s/it ████████████ 100% 12/12 00:45 00:00 Loading checkpoint shards
Progress 11998.01it/s █████████████████ 100% 12/12 00:00 00:00 Fetching 12 files
Progress  3.63s/it ████████████ 100% 12/12 00:43 00:00 Loading checkpoint shards
Progress  6.68it/s █████████ 100% 6/6 00:00 00:00 Loading pipeline components...
18:15:26-443581 INFO     Offload: type=balanced op=init watermark=0.2-0.6 gpu=3.20-9.60:16.00 cpu=64.000 limit=0.00
                         always=[] never=[]
18:15:26-478578 INFO     Model class=WanImageToVideoPipeline modules=4 size=36.483
18:15:26-481578 INFO     Video load: cls=WanImageToVideoPipeline model="WAN 2.2 A14B I2V" time=118.30
18:15:26-849210 INFO     Processing modifiers: apply
18:15:27-049208 INFO     Base: pipeline=WanImageToVideoPipeline task=IMAGE_2_IMAGE batch=1/1x1 set={'prompt': 49,
                         'negative_prompt': 0, 'generator': 'cuda:[38768450]', 'num_inference_steps': 5, 'num_frames':
                         17, 'output_type': 'pil', 'image': <PIL.Image.Image image mode=RGB size=480x832 at
                         0x23717D3B350>, 'width': 480, 'height': 832, 'parser': 'fixed'}
Progress ?it/s                                               0% 0/5 00:02 ? Base
18:15:38-869736 ERROR    Processing: step=base args={'prompt': 'greek marble bust of a man, slowly smiles, laughs',
                         'negative_prompt': '', 'generator': [<torch._C.Generator object at 0x00000237140AB8B0>],
                         'callback_on_step_end': <function diffusers_callback at 0x000002372EBCDF80>,
                         'callback_on_step_end_tensor_inputs': ['latents', 'prompt_embeds', 'negative_prompt_embeds'],
                         'num_inference_steps': 5, 'num_frames': 17, 'output_type': 'pil', 'image': <PIL.Image.Image
                         image mode=RGB size=480x832 at 0x23717C96590>, 'width': 480, 'height': 832} Given groups=1,
                         weight of size [5120, 16, 1, 2, 2], expected input[1, 36, 5, 104, 60] to have 16 channels, but
                         got 36 channels instead
18:15:38-889738 ERROR    Processing: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│F:\VladStable2\automatic\modules\processing_diffusers.py:148 in process_base                                         │
│                                                                                                                     │
│  147 │   │   else:                                                                                                  │
│> 148 │   │   │   output = shared.sd_model(**base_args)                                                              │
│  149 │   │   if isinstance(output, dict):                                                                           │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\torch\utils\_contextlib.py:116 in decorate_context                   │
│                                                                                                                     │
│  115 │   │   with ctx_factory():                                                                                    │
│> 116 │   │   │   return func(*args, **kwargs)                                                                       │
│  117                                                                                                                │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan_i2v.py:756 in __call__          │
│                                                                                                                     │
│  755 │   │   │   │   with current_model.cache_context("cond"):                                                      │
│> 756 │   │   │   │   │   noise_pred = current_model(                                                                │
│  757 │   │   │   │   │   │   hidden_states=latent_model_input,                                                      │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl                │
│                                                                                                                     │
│  1750 │   │   else:                                                                                                 │
│> 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                           │
│  1752                                                                                                               │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                        │
│                                                                                                                     │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│> 1762 │   │   │   return forward_call(*args, **kwargs)                                                              │
│  1763                                                                                                               │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\accelerate\hooks.py:175 in new_forward                               │
│                                                                                                                     │
│  174 │   │   else:                                                                                                  │
│> 175 │   │   │   output = module._old_forward(*args, **kwargs)                                                      │
│  176 │   │   return module._hf_hook.post_forward(module, output)                                                    │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\diffusers\models\transformers\transformer_wan.py:632 in forward      │
│                                                                                                                     │
│  631 │   │                                                                                                          │
│> 632 │   │   hidden_states = self.patch_embedding(hidden_states)                                                    │
│  633 │   │   hidden_states = hidden_states.flatten(2).transpose(1, 2)                                               │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\torch\nn\modules\module.py:1751 in _wrapped_call_impl                │
│                                                                                                                     │
│  1750 │   │   else:                                                                                                 │
│> 1751 │   │   │   return self._call_impl(*args, **kwargs)                                                           │
│  1752                                                                                                               │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\torch\nn\modules\module.py:1762 in _call_impl                        │
│                                                                                                                     │
│  1761 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│> 1762 │   │   │   return forward_call(*args, **kwargs)                                                              │
│  1763                                                                                                               │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\accelerate\hooks.py:175 in new_forward                               │
│                                                                                                                     │
│  174 │   │   else:                                                                                                  │
│> 175 │   │   │   output = module._old_forward(*args, **kwargs)                                                      │
│  176 │   │   return module._hf_hook.post_forward(module, output)                                                    │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\torch\nn\modules\conv.py:725 in forward                              │
│                                                                                                                     │
│   724 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│>  725 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│   726                                                                                                               │
│                                                                                                                     │
│F:\VladStable2\automatic\venv\Lib\site-packages\torch\nn\modules\conv.py:720 in _conv_forward                        │
│                                                                                                                     │
│   719 │   │   │   )                                                                                                 │
│>  720 │   │   return F.conv3d(                                                                                      │
│   721 │   │   │   input, weight, bias, self.stride, self.padding, self.dilation, self.groups                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Given groups=1, weight of size [5120, 16, 1, 2, 2], expected input[1, 36, 5, 104, 60] to have 16 channels, but got 36 channels instead
18:15:39-478680 INFO     Processing modifiers: unapply
18:15:39-784479 INFO     Processed: images=0 its=0.00 ops=['video']
18:15:39-788480 ERROR    Video: processing failed

### Version Platform Description

Win10
AMD x5900
4080 16gb
64gb ram

[sdnext.log](https://github.com/user-attachments/files/22168013/sdnext.log)

15:34:10-810608 INFO     Starting SD.Next
15:34:10-815613 INFO     Logger: file="F:\VladStable2\automatic\sdnext.log" level=INFO host="KOSSI-Zen" size=2150801
                         mode=append
15:34:10-818611 INFO     Python: version=3.11.9 platform=Windows bin="F:\VladStable2\automatic\venv\Scripts\python.exe"
                         venv="F:\VladStable2\automatic\venv"
15:34:11-020611 INFO     Version: app=sd.next updated=2025-09-03 hash=40d6dc80c branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev ui=dev
15:34:11-893122 INFO     Version: app=sd.next latest=2025-09-03T21:12:27Z hash=40d6dc80 branch=dev
15:34:11-903124 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.11.9 locale=('English_Australia', '1252')
                         docker=False
15:34:11-908122 INFO     Args: ['--upgrade']
15:34:11-911122 INFO     Verifying torch installation
15:34:11-933132 INFO     CUDA: nVidia toolkit detected
15:34:12-143131 INFO     Install: verifying requirements
15:34:12-148131 INFO     Startup: standard
15:34:12-149132 INFO     Verifying submodules
15:34:27-697822 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'a1111-sd-webui-tagcomplete', 'sd-extension-framepack']

### Relevant log output

```shell
2025-09-03 15:44:37,277 | KOSSI-Zen | sd | DEBUG | video_load | Video load: module=te repo="Wan-AI/Wan2.2-T2V-A14B-Diffusers" folder="text_encoder" cls=T5EncoderModel quant=SDNQConfig
2025-09-03 15:44:49,423 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 1.42, 'ram': 28.26, 'oom': 0} prev={'gpu': 2.6, 'ram': 28.26} load={'gpu': 9, 'ram': 44} gc={'gpu': 1.18, 'py': 139} fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.40
2025-09-03 15:44:49,423 | KOSSI-Zen | sd | DEBUG | model_quant | Quantization: module="Model" type=sdnq mode=pre dtype=int4 matmul=False group_size=0 quant_conv=False matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
2025-09-03 15:44:49,424 | KOSSI-Zen | sd | DEBUG | video_load | Video load: module=transformer repo="Wan-AI/Wan2.2-T2V-A14B-Diffusers" folder="transformer" cls=WanTransformer3DModel quant=SDNQConfig
2025-09-03 15:45:35,631 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 1.42, 'ram': 26.23, 'oom': 0} prev={'gpu': 1.42, 'ram': 26.23} load={'gpu': 9, 'ram': 41} gc={'gpu': 0.0, 'py': 160} fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.41
2025-09-03 15:45:35,635 | KOSSI-Zen | sd | DEBUG | model_quant | Quantization: module="Model" type=sdnq mode=pre dtype=int4 matmul=False group_size=0 quant_conv=False matmul_conv=False dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
2025-09-03 15:45:35,636 | KOSSI-Zen | sd | DEBUG | video_load | Video load: module=transformer repo="Wan-AI/Wan2.2-T2V-A14B-Diffusers" folder="transformer_2" cls=WanTransformer3DModel quant=SDNQConfig
2025-09-03 15:46:00,650 | KOSSI-Zen | sd | TRACE | launch | Server: alive=True requests=171 memory=24.85/63.93 status='running' task='Load' timestamp='20250903154436' current='task(db8zu4njq3fob6t)' id='f0672535ba4947d' job=0 jobs=1 total=9 step=0 steps=0 queued=0 uptime=491 elapsed=84.59 eta=None progress=0
2025-09-03 15:46:21,944 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 1.42, 'ram': 25.81, 'oom': 0} prev={'gpu': 1.42, 'ram': 25.81} load={'gpu': 9, 'ram': 40} gc={'gpu': 0.0, 'py': 162} fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.41
2025-09-03 15:46:21,948 | KOSSI-Zen | sd | DEBUG | video_load | Video load: module=pipe repo="Wan-AI/Wan2.2-T2V-A14B-Diffusers" cls=WanImageToVideoPipeline
2025-09-03 15:46:23,974 | KOSSI-Zen | sd | DEBUG | installer | Setting model: component=vae {'upcast': False}
2025-09-03 15:46:23,974 | KOSSI-Zen | sd | INFO | sd_offload | Offload: type=balanced op=init watermark=0.2-0.6 gpu=3.20-9.60:16.00 cpu=64.000 limit=0.00 always=[] never=[]
2025-09-03 15:46:23,995 | KOSSI-Zen | sd | DEBUG | sd_offload | Module: name=text_encoder cls=T5EncoderModel size=7.394 params=3868923904 quant=QuantizationMethod.SDNQ
2025-09-03 15:46:24,002 | KOSSI-Zen | sd | DEBUG | sd_offload | Module: name=transformer cls=WanTransformer3DModel size=7.039 params=7262868544 quant=QuantizationMethod.SDNQ
2025-09-03 15:46:24,010 | KOSSI-Zen | sd | DEBUG | sd_offload | Module: name=transformer_2 cls=WanTransformer3DModel size=7.039 params=7262868544 quant=QuantizationMethod.SDNQ
2025-09-03 15:46:24,011 | KOSSI-Zen | sd | DEBUG | sd_offload | Module: name=vae cls=AutoencoderKLWan size=0.236 params=126892531 quant=None
2025-09-03 15:46:24,012 | KOSSI-Zen | sd | INFO | sd_offload | Model class=WanImageToVideoPipeline modules=4 size=21.709
2025-09-03 15:46:24,014 | KOSSI-Zen | sd | INFO | video_load | Video load: cls=WanImageToVideoPipeline model="WAN 2.2 A14B I2V" time=106.70
2025-09-03 15:46:24,049 | KOSSI-Zen | sd | DEBUG | images_resize | Image resize: source=1536:2304 target=480:832 mode="Crop" upscaler="None" type=pil time=0.03 fn=f:generate
2025-09-03 15:46:24,049 | KOSSI-Zen | sd | DEBUG | video_run | Video: op=I2V init=<PIL.Image.Image image mode=RGB size=1536x2304 at 0x1EF35A08310> resized=<PIL.Image.Image image mode=RGB size=480x832 at 0x1EF55DE82D0>
2025-09-03 15:46:24,447 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 1.42, 'ram': 26.24, 'oom': 0} prev={'gpu': 1.42, 'ram': 26.24} load={'gpu': 9, 'ram': 41} gc={'gpu': 0.0, 'py': 594} fn=f:generate why=video time=0.40
2025-09-03 15:46:24,447 | KOSSI-Zen | sd | DEBUG | video_run | Video: cls=WanImageToVideoPipeline width=480 height=832 frames=17 steps=4
2025-09-03 15:46:24,448 | KOSSI-Zen | sd | DEBUG | sd_samplers | Sampler: "Default" cls=UniPCMultistepScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.0001, 'beta_end': 0.02, 'beta_schedule': 'linear', 'trained_betas': None, 'solver_order': 2, 'prediction_type': 'flow_prediction', 'thresholding': False, 'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'predict_x0': True, 'solver_type': 'bh2', 'lower_order_final': True, 'disable_corrector': [], 'solver_p': None, 'use_karras_sigmas': False, 'use_exponential_sigmas': False, 'use_beta_sigmas': False, 'use_flow_sigmas': True, 'flow_shift': 3.0, 'timestep_spacing': 'linspace', 'steps_offset': 0, 'final_sigmas_type': 'zero', 'rescale_betas_zero_snr': False, 'use_dynamic_shifting': False, 'time_shift_type': 'exponential'}
2025-09-03 15:46:24,449 | KOSSI-Zen | sd | INFO | processing_diffusers | Processing modifiers: apply
2025-09-03 15:46:24,452 | KOSSI-Zen | sd | INFO | processing_args | Base: pipeline=WanImageToVideoPipeline task=IMAGE_2_IMAGE batch=1/1x1 set={'prompt': 82, 'negative_prompt': 0, 'guidance_scale': 2.0, 'generator': 'cuda:[3903677015]', 'num_inference_steps': 4, 'num_frames': 17, 'output_type': 'pil', 'image': <PIL.Image.Image image mode=RGB size=480x832 at 0x1EF55DE82D0>, 'width': 480, 'height': 832, 'parser': 'fixed'}
2025-09-03 15:46:24,471 | KOSSI-Zen | sd | DEBUG | sd_hijack_te | Encode: prompt="marble statue head of a man, marble bust is smiling and laughing, black background" hijack=True
2025-09-03 15:46:27,540 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.05, 'ram': 19.17, 'oom': 0} prev={'gpu': 9.38, 'ram': 19.32} load={'gpu': 57, 'ram': 30} gc={'gpu': 0.33, 'py': 67369} fn=hijack_encode_prompt:end why=threshold time=0.53
2025-09-03 15:46:27,956 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.12, 'ram': 19.18, 'oom': 0} prev={'gpu': 9.2, 'ram': 19.18} load={'gpu': 57, 'ram': 30} gc={'gpu': 0.08, 'py': 254} fn=hijack_vae_encode:begin why=threshold time=0.39
2025-09-03 15:46:33,174 | KOSSI-Zen | sd | DEBUG | sd_hijack_vae | Encode: vae=AutoencoderKLWan slicing=True tiling=False latents=[1, 3, 17, 832, 480]:cuda:0:torch.bfloat16 time=5.216
2025-09-03 15:46:35,131 | KOSSI-Zen | sd | ERROR | processing_diffusers | Processing: step=base args={'prompt': 'marble statue head of a man, marble bust is smiling and laughing, black background', 'negative_prompt': '', 'guidance_scale': 2.0, 'generator': [<torch._C.Generator object at 0x000001EF359DAAD0>], 'callback_on_step_end': <function diffusers_callback at 0x000001EF2DA37D80>, 'callback_on_step_end_tensor_inputs': ['latents', 'prompt_embeds', 'negative_prompt_embeds'], 'num_inference_steps': 4, 'num_frames': 17, 'output_type': 'pil', 'image': <PIL.Image.Image image mode=RGB size=480x832 at 0x1EF372B15D0>, 'width': 480, 'height': 832} Given groups=1, weight of size [5120, 16, 1, 2, 2], expected input[1, 36, 5, 104, 60] to have 16 channels, but got 36 channels instead
2025-09-03 15:46:35,147 | KOSSI-Zen | sd | ERROR | errors | Processing: RuntimeError
2025-09-03 15:46:35,675 | KOSSI-Zen | sd | DEBUG | modelstats | Analyzed: model="Diffusers\Wan-AI/Wan2.2-T2V-A14B-Diffusers" type=wanai class=WanImageToVideoPipeline size=0 mtime="2025-09-01 20:07:04" modules=[name="vae" cls=AutoencoderKLWan config=True device=cuda:0 dtype=torch.bfloat16 params=126892531 modules=260, name="text_encoder" cls=T5EncoderModel config=True device=cpu dtype=torch.bfloat16 params=3868923904 modules=607, name="tokenizer" cls=T5TokenizerFast config=False, name="image_encoder" cls=NoneType config=False, name="transformer" cls=WanTransformer3DModel config=True device=cuda:0 dtype=torch.bfloat16 params=7262868544 modules=1539, name="scheduler" cls=UniPCMultistepScheduler config=True, name="image_processor" cls=NoneType config=False, name="transformer_2" cls=WanTransformer3DModel config=True device=cpu dtype=torch.bfloat16 params=7262868544 modules=1539, name="boundary_ratio" cls=float config=False, name="expand_timesteps" cls=bool config=False]
2025-09-03 15:46:35,675 | KOSSI-Zen | sd | INFO | processing_diffusers | Processing modifiers: unapply
2025-09-03 15:46:36,054 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 22.25, 'oom': 0} prev={'gpu': 9.66, 'ram': 22.25} load={'gpu': 60, 'ram': 35} gc={'gpu': 0.0, 'py': 182} fn=process_base:nextjob why=threshold time=0.38
2025-09-03 15:46:36,054 | KOSSI-Zen | sd | INFO | processing | Processed: images=0 its=0.00 ops=['video']
2025-09-03 15:46:36,057 | KOSSI-Zen | sd | DEBUG | processing | Processed: timers={'total': 20.72, 'post': 11.23, 'vae': 5.22, 'te': 2.53, 'gc': 1.36, 'process': 0.38}
2025-09-03 15:46:36,057 | KOSSI-Zen | sd | DEBUG | processing | Processed: memory={'ram': {'total': 63.93, 'used': 22.25, 'free': 42}, 'gpu': {'used': 9.66, 'total': 15.99, 'active': 7.75, 'peak': 7.75, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}
2025-09-03 15:46:36,058 | KOSSI-Zen | sd | ERROR | video_utils | Video: processing failed
2025-09-03 15:46:36,443 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 22.22, 'oom': 0} prev={'gpu': 9.66, 'ram': 22.22} load={'gpu': 60, 'ram': 35} gc={'gpu': 0.0, 'py': 489} fn=f:end why=threshold time=0.38
2025-09-03 15:47:11,703 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 21.62, 'oom': 0} prev={'gpu': 9.66, 'ram': 21.62} load={'gpu': 60, 'ram': 34} gc={'gpu': 0.0, 'py': 335} fn=f:begin why=threshold time=0.41
2025-09-03 15:47:11,707 | KOSSI-Zen | sd | DEBUG | json_helpers | Save: file="F:\VladStable2\automatic\config.json" json=68 bytes=3095 time=0.003
2025-09-03 15:47:11,704 | KOSSI-Zen | sd | INFO | ui_settings | Settings: changed=1 ['sdp_options']
2025-09-03 15:47:11,708 | KOSSI-Zen | sd | DEBUG | options_handler | Settings: unused=['cross_attention_options', 'schedulers_brownian_noise', 'multiple_tqdm', 'ad_save_images_before', 'cuda_compile_precompile', 'cuda_compile_verbose', 'schedulers_use_karras']
2025-09-03 15:47:12,120 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 21.62, 'oom': 0} prev={'gpu': 9.66, 'ram': 21.62} load={'gpu': 60, 'ram': 34} gc={'gpu': 0.0, 'py': 127} fn=f:end why=threshold time=0.41
2025-09-03 15:46:35,675 | KOSSI-Zen | sd | INFO | processing_diffusers | Processing modifiers: unapply
2025-09-03 15:46:36,054 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 22.25, 'oom': 0} prev={'gpu': 9.66, 'ram': 22.25} load={'gpu': 60, 'ram': 35} gc={'gpu': 0.0, 'py': 182} fn=process_base:nextjob why=threshold time=0.38
2025-09-03 15:46:36,054 | KOSSI-Zen | sd | INFO | processing | Processed: images=0 its=0.00 ops=['video']
2025-09-03 15:46:36,057 | KOSSI-Zen | sd | DEBUG | processing | Processed: timers={'total': 20.72, 'post': 11.23, 'vae': 5.22, 'te': 2.53, 'gc': 1.36, 'process': 0.38}
2025-09-03 15:46:36,057 | KOSSI-Zen | sd | DEBUG | processing | Processed: memory={'ram': {'total': 63.93, 'used': 22.25, 'free': 42}, 'gpu': {'used': 9.66, 'total': 15.99, 'active': 7.75, 'peak': 7.75, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': ''}
2025-09-03 15:46:36,058 | KOSSI-Zen | sd | ERROR | video_utils | Video: processing failed
2025-09-03 15:46:36,443 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 22.22, 'oom': 0} prev={'gpu': 9.66, 'ram': 22.22} load={'gpu': 60, 'ram': 35} gc={'gpu': 0.0, 'py': 489} fn=f:end why=threshold time=0.38
2025-09-03 15:47:11,703 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 21.62, 'oom': 0} prev={'gpu': 9.66, 'ram': 21.62} load={'gpu': 60, 'ram': 34} gc={'gpu': 0.0, 'py': 335} fn=f:begin why=threshold time=0.41
2025-09-03 15:47:11,707 | KOSSI-Zen | sd | DEBUG | json_helpers | Save: file="F:\VladStable2\automatic\config.json" json=68 bytes=3095 time=0.003
2025-09-03 15:47:11,704 | KOSSI-Zen | sd | INFO | ui_settings | Settings: changed=1 ['sdp_options']
2025-09-03 15:47:11,708 | KOSSI-Zen | sd | DEBUG | options_handler | Settings: unused=['cross_attention_options', 'schedulers_brownian_noise', 'multiple_tqdm', 'ad_save_images_before', 'cuda_compile_precompile', 'cuda_compile_verbose', 'schedulers_use_karras']
2025-09-03 15:47:12,120 | KOSSI-Zen | sd | DEBUG | devices | GC: current={'gpu': 9.66, 'ram': 21.62, 'oom': 0} prev={'gpu': 9.66, 'ram': 21.62} load={'gpu': 60, 'ram': 34} gc={'gpu': 0.0, 'py': 127} fn=f:end why=threshold time=0.41
```

### Backend

Diffusers

### Compute

nVidia CUDA

### Interface

Standard

### Branch

Dev

### Model

Any Video Model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
update: same issue occurs when using wan in i2i mode

**Comment by vladmandic** [comment]
wan 2.2 a14b i2v is now fixed, at the end it was a silly typo - sdnext was loading t2v model instead of i2v model.

regarding i2i, wan22 a14b is not supported since it currently does not support denoising strength so its pointless for single frame.

**Comment by vladmandic** [comment]
for reference: https://github.com/huggingface/diffusers/issues/12368
