### ISSUE TITLE
[Issue]: Intel Arc GPU not being utilized

### ISSUE THREAD

**Issue by Silverflare29** [vladmandic/sdnext#4203]
### Issue Description

Disclaimer: I am new to Stable Diffusion and this is my first UI (at least that worked for my machine)

I am using the current version of this repo as of September 13, 2025

Machine Specs:
- Windows 11
- Intel i5 12450HX
- Intel Arc A530M Graphics 4GB
- 8GB RAM (4800MHz)

I was able to open the UI and run the UI and I was able to output something in the text to image part. I used **juggernautXL_ragnarokBy** safetensor file/model for stable diffusion. The output time was about a minute, max 5 minutes. I've checked my machine and the UI is only utilizing the CPU and the majority was in the Memory and Integrated Graphics. There's 0 utilization in my dedicated graphics. Apologies if this has been asked before, but all of the fix I'm finding online seems to be extremely outdated and none of the frameworks supports such fix. Do we have an updated fix for this?

**Comment by vladmandic** [comment]
issues always need actual log - right now this is just a general statement that is not actionable.
please run `webui --debug` and upload log here.

**Comment by vladmandic** [comment]
@Silverflare29 any updates?

**Comment by vladmandic** [comment]
closing as no information provided - once information is provided, i'll reopen the issue.

**Comment by Silverflare29** [comment]
Sorry, I forgot I made a query about this. I don't know how to do the `webui --debug` or where to do it. But I was able to find the log that the webui generated upon launch (file: [sdnext.log](https://github.com/user-attachments/files/22428685/sdnext.log)), I'm not quite sure if this is the correct file. Anyways, I also added some command line input thingies:

`set COMMANDLINE_ARGS=--use-ipex --listen --port 7860`

I tried using the `--use-ipex` since it's not utilizing my Intel GPU, but this does not fix it. The `--listen --port 7860` is just so that I can access it via my phone.

To add, the UI also kinda goes on a timeout every image generation, should I open a new Ticket for that?

**Comment by vladmandic** [comment]
seems like correct torch is installed and gpu is detected
```log
2025-09-19 21:45:20,388 | Silbrrrrr | sd | DEBUG | devices | Torch attention: type="sdpa" flash=True memory=True math=True
2025-09-19 21:45:22,808 | Silbrrrrr | sd | INFO | devices | Torch parameters: backend=ipex device=xpu config=Auto dtype=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, False] fp16=pass bf16=pass optimization="Scaled-Dot-Product"
2025-09-19 21:45:22,808 | Silbrrrrr | sd | INFO | shared | Device: device=Intel(R) Arc(TM) A530M Graphics n=1 ipex= driver=1.6.32960
```
try adding `--device-id 1` to your `COMMANDLINE_ARGS`

cc @Disty0 for advice

**Comment by Silverflare29** [comment]
I did added it to the Command Line, but I am receiving this error upon startup.
```
23:39:50-733687 ERROR    Setting model: offload=sequential The device index is out of range. It must be in [0, 1), but got 1.
```
Here's the log as shown in the console: [sdnext_copied_log.txt](https://github.com/user-attachments/files/22430867/sdnext_copied_log.txt)

I changed it to `--device-id 0` and it's working now and is 1 minute faster than before (from 6 min to 5min). It seems like it does not count the iGPU as a GPU. But there's still a problem, the utilization average is around 8% maxing out to 20%.

I noticed that my SSDs (2 SSDs) are the ones being used at almost 100% utilization. I have virtual ram of so much from both my SSDs since I multitask a lot. That might be causing the problem, imma try to reduce it significantly. Will update after.

**Comment by Disty0** [comment]
Your iGPU isn't supported by PyTorch so it won't work at all. A530M is detected correctly and is in use.

There are multiple problems in your system.
8 GB System RAM is simply not enough for SDXL. You can't run XL models on your PC without everything slowing down to a halt.
Btw, your PC will use your SSD as RAM when you run out of System RAM. That's why it is very slow and why you have 100% SSD utilization.

Your GPU also only has 4GB VRAM, also not enough for SDXL. You can still run it with lowvram mode (it is enabled by default on 4GB and you are currently using it.) but it will be slow and will need even more System RAM.

You can't run SDXL models on your system. Only solution is to upgrade your System RAM first.
You might be able to barely run it with very aggressive quantization: https://github.com/vladmandic/sdnext/wiki/SDNQ-Quantization

Also the max performance possible with SDXL on your GPU is around a minute per image at 20 steps and 1024x1024 resolution. It is not a strong GPU either.

You can use the old 512x512 resolution SD 1.5 models as they are much smaller models but quality of them are not really good.

**Comment by Silverflare29** [comment]
I managed to make it work somehow. I can now generate in around 3 minutes (from 6 minutes) which I think is reasonable for an 8 GB RAM and 2GB VRAM. It is currently utilizing on average 40% of my GPU maxing out to 70%

I made the Command Line like this: `set COMMANDLINE_ARGS=--use-ipex --device-id 0`
Device ID at 0 instead of 1 since as you said iGPU is not supported, hence not detected.

Then I went on to **Performance Options** in Windows settings.
`Advanced > Processor Scheduling > Background Processes`
I also set the Virtual RAM of C: to System Managed and D: to 20GB - 30GB.

Somehow, these settings increases the GPU utilization from an average of 25% to 40%, from max of 50% to max of 70%.

I tried to tweak them and these showed the best results so far.
