### ISSUE TITLE
[Issue]: Framepack fails with AttributeError: 'Image' object has no attribute 'shape'

### ISSUE THREAD

**Issue by SAC020** [vladmandic/sdnext#4328]
### Issue Description

1. Video
2. Uploaded an init image in the input tab, left last image blank
3. Framepack tab, default values, entered a prompt
4. Generate => error

### Version Platform Description

PS C:\ai\sdnext> .\webui.bat --debug
Using VENV: C:\ai\sdnext\venv
12:23:21-789143 INFO     Starting SD.Next
12:23:21-792149 INFO     Logger: file="C:\ai\sdnext\sdnext.log" level=DEBUG host="SEB-PC" size=74 mode=create
12:23:21-792919 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\sdnext\venv\Scripts\python.exe"
                         venv="C:\ai\sdnext\venv"
12:23:22-102315 INFO     Version: app=sd.next updated=2025-10-26 hash=818b0c082 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev ui=dev
12:23:22-817684 INFO     Version: app=sd.next latest=2025-10-31T07:45:18Z hash=b0e147a4 branch=dev
12:23:22-830694 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26200-SP0 python=3.11.9 locale=('English_United States', '1250')
                         docker=False
12:23:22-834509 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
12:23:22-836139 INFO     Args: ['--debug']

### Relevant log output

```shell
PS C:\ai\sdnext> .\webui.bat --debug
Using VENV: C:\ai\sdnext\venv
12:23:21-789143 INFO     Starting SD.Next
12:23:21-792149 INFO     Logger: file="C:\ai\sdnext\sdnext.log" level=DEBUG host="SEB-PC" size=74 mode=create
12:23:21-792919 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\sdnext\venv\Scripts\python.exe"
                         venv="C:\ai\sdnext\venv"
12:23:22-102315 INFO     Version: app=sd.next updated=2025-10-26 hash=818b0c082 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev ui=dev
12:23:22-817684 INFO     Version: app=sd.next latest=2025-10-31T07:45:18Z hash=b0e147a4 branch=dev
12:23:22-830694 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26200-SP0 python=3.11.9 locale=('English_United States', '1250')
                         docker=False
12:23:22-834509 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
12:23:22-836139 INFO     Args: ['--debug']
12:23:22-837358 DEBUG    Setting environment tuning
12:23:22-838451 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
12:23:22-840083 INFO     Verifying torch installation
12:23:22-840626 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
12:23:22-856945 INFO     CUDA: nVidia toolkit detected
12:23:25-270916 INFO     Torch backend: version="2.7.1+cu128" type=CUDA CUDA=12.8 cuDNN=90701
12:23:25-274433 INFO     Torch detected: gpu="NVIDIA GeForce RTX 4090" vram=24564 arch=(8, 9) cores=128
12:23:25-411838 WARNING  Modified files: ['scripts/detect_extension.py']
12:23:25-563800 INFO     Install: verifying requirements
12:23:25-623320 DEBUG    Timestamp repository update time: Sun Oct 26 09:44:04 2025
12:23:25-624311 INFO     Startup: standard
12:23:25-625303 INFO     Verifying submodules
12:23:29-000049 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-chainner" reattach=main
12:23:29-001538 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
12:23:29-179122 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
12:23:29-180258 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
12:23:29-328702 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=dev
12:23:29-329815 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
12:23:29-569563 DEBUG    Git detached head detected: folder="extensions-builtin/stable-diffusion-webui-rembg"
                         reattach=master
12:23:29-570722 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
12:23:29-723296 DEBUG    Git detached head detected: folder="wiki" reattach=master
12:23:29-724186 DEBUG    Git submodule: wiki / master
12:23:29-944055 DEBUG    Installed packages: 289
12:23:29-945796 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
12:23:30-317646 DEBUG    Extension installer: builtin=True
                         file="C:\ai\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py"
12:23:30-575767 DEBUG    Extension installer: builtin=True
                         file="C:\ai\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py"
12:23:30-694529 DEBUG    Extensions all: ['canvas-zoom', 'sd-webui-openpose-editor']
12:23:30-696189 DEBUG    Extension installer: builtin=False file="C:\ai\sdnext\extensions\canvas-zoom\install.py"
12:23:35-571399 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg', 'canvas-zoom',
                         'sd-webui-openpose-editor']
12:23:35-697491 INFO     Install: verifying requirements
12:23:35-701295 DEBUG    Setup complete without errors: 1761906216
12:23:35-720716 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.01}
12:23:35-722700 INFO     Installer time: total=20.06 canvas-zoom=4.75 git=4.42 submodules=4.20 torch=2.43 latest=1.02
                         branch=0.91 base=0.40 version=0.30 installed=0.29 requirements=0.29
                         sd-webui-agent-scheduler=0.14 files=0.14 Lora=0.13 sd-webui-openpose-editor=0.12
                         sd-extension-chainner=0.12 sd-extension-system-info=0.12 sdnext-modernui=0.12
                         stable-diffusion-webui-rembg=0.12
12:23:35-725676 INFO     Command line args: ['--debug'] args=[]
12:23:35-727468 DEBUG    Env flags: []
12:23:35-727974 DEBUG    Starting module: <module 'webui' from 'C:\\ai\\sdnext\\webui.py'>
12:23:49-756809 INFO     Torch: torch==2.7.1+cu128 torchvision==0.22.1+cu128
12:23:49-760057 INFO     Packages: diffusers==0.36.0.dev0 transformers==4.57.1 accelerate==1.11.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0
12:23:50-885364 DEBUG    ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']
12:23:51-061415 DEBUG    State initialized: id=2495215129360
12:23:51-132430 INFO     Device detect: memory=24.0 default=balanced optimization=highvram
12:23:54-654378 DEBUG    Read: file="C:\ai\sdnext\config.json" json=34 bytes=1463 time=0.000 fn=<module>:load
12:23:54-656315 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
12:23:54-659674 DEBUG    Read: file="html\reference.json" json=132 bytes=64653 time=0.002
                         fn=_call_with_frames_removed:<module>
12:23:54-660778 DEBUG    Torch cuDNN: benchmark=True
12:23:54-661901 DEBUG    Torch attention: type="sdpa" opts=['Flash attention', 'Memory attention', 'Math attention']
12:23:54-663743 INFO     Torch attention: flashattn=False sageattention=False
12:23:54-693151 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=pass optimization="Scaled-Dot-Product"
12:23:54-759191 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_120 capability=(8, 9) cuda=12.8 cudnn=90701
                         driver=581.57
12:23:55-000898 DEBUG    Entering start sequence
12:23:55-004890 DEBUG    Initializing
12:23:55-010081 DEBUG    Read: file="metadata.json" json=517 bytes=788247 time=0.003 fn=initialize:init_metadata
12:23:55-012251 DEBUG    Read: file="cache.json" json=2 bytes=6600 time=0.001 fn=initialize:init_cache
12:23:55-086142 INFO     Available VAEs: path="models\VAE" items=0
12:23:55-088126 INFO     Available UNets: path="models\UNET" items=0
12:23:55-089252 INFO     Available TEs: path="models\Text-encoder" items=4
12:23:55-105365 INFO     Available Models: safetensors="models\Stable-diffusion":22 diffusers="models\Diffusers":11
                         reference=132 items=33 time=0.01
12:23:55-137766 INFO     Available LoRAs: path="models\Lora" items=232 folders=3 time=0.02
12:23:55-157197 INFO     Available Styles: path="models\styles" items=288 time=0.02
12:23:55-271866 INFO     Available Detailer: path="models\yolo" items=12 downloaded=4
12:23:55-274474 DEBUG    Extensions: disabled=['Lora', 'sdnext-modernui']
12:23:55-275067 INFO     Load extensions
12:23:56-338314 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
12:23:56-356052 DEBUG    Extensions init time: total=1.08 sd-webui-agent-scheduler=0.74 cogvideo.py=0.08
                         sd-extension-chainner=0.06
12:23:56-638651 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.000 fn=__init__:__init__
12:23:56-640116 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
12:23:56-643584 DEBUG    Available chaiNNer: path="models\chaiNNer" defined=25 discovered=0 downloaded=10
12:23:56-651107 INFO     Available Upscalers: items=78 downloaded=24 user=3 time=0.29 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SeedVR', 'SwinIR']
12:23:56-719567 INFO     Networks: type="video" engines=11 models=57 time=0.06
12:23:56-724118 INFO     Huggingface: transfer=rust parallel=True direct=False token="hf_...UtOy"
                         cache="D:\huggingface\hub" init
12:23:57-092198 DEBUG    Huggingface: cache="D:\huggingface\hub" size=630450 MB
12:23:57-093686 DEBUG    UI start sequence
12:23:57-107696 INFO     UI locale: name="Auto"
12:23:57-108914 INFO     UI theme: type=Standard name="black-teal" available=14
12:23:57-111123 DEBUG    UI theme: css="C:\ai\sdnext\javascript\black-teal.css" base="['sdnext.css', 'timesheet.css']"
                         user="None"
12:23:57-114363 DEBUG    UI initialize: tab=txt2img
12:23:57-247662 DEBUG    Read: file="html\reference.json" json=132 bytes=64653 time=0.004 fn=list_items:list_reference
12:23:57-287713 DEBUG    Networks: type="reference" items={'total': 132, 'ready': 1, 'hidden': 0, 'experimental': 0,
                         'base': 86, 'distilled': 17, 'quantized': 13, 'community': 14}
12:23:57-309263 DEBUG    Networks: type="model" items=163 subfolders=7 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Reference', 'C:\\ai\\sdnext\\models\\Stable-diffusion'] list=0.17 thumb=0.02 desc=0.02
                         info=0.10 workers=12
12:23:57-319551 DEBUG    Networks: type="lora" items=232 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.15
                         thumb=0.04 desc=0.13 info=0.37 workers=12
12:23:57-338225 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.11 thumb=0.00 desc=0.00 info=0.00 workers=12
12:23:57-343682 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models\\wildcards']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
12:23:57-346924 DEBUG    Networks: type="embedding" items=13 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.09 thumb=0.03 desc=0.01 info=0.01 workers=12
12:23:57-349556 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
12:23:57-351246 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
12:23:57-605074 DEBUG    UI initialize: tab=img2img
12:23:57-849799 DEBUG    UI initialize: tab=control models="models\control"
12:23:58-046728 DEBUG    Script: fn="extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py" type=control
                         skip
12:23:58-283111 DEBUG    UI initialize: tab=video
12:23:58-419212 DEBUG    UI initialize: tab=process
12:23:58-473310 DEBUG    UI initialize: tab=caption
12:23:58-588963 DEBUG    UI initialize: tab=models
12:23:58-671776 DEBUG    UI initialize: tab=gallery
12:23:58-729872 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.001 fn=__init__:read_from_file
12:23:58-730826 DEBUG    UI initialize: tab=settings
12:23:58-735386 DEBUG    Settings: sections=25 settings=407/620 quicksettings=0
12:23:59-497306 DEBUG    UI initialize: tab=info
12:23:59-527343 DEBUG    UI initialize: tab=extensions
12:24:00-360076 DEBUG    Extension list: processed=412 installed=7 enabled=6 disabled=1 visible=412 hidden=0
12:24:00-592860 DEBUG    Root paths: ['C:\\ai\\sdnext', 'models']
12:24:00-702462 INFO     Local URL: http://127.0.0.1:7860/
12:24:00-702963 INFO     API docs: http://127.0.0.1:7860/docs
12:24:00-704280 INFO     API redocs: http://127.0.0.1:7860/redocs
12:24:00-706279 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
12:24:00-706793 DEBUG    API initialize
12:24:00-933782 INFO     [AgentScheduler] Task queue is empty
12:24:00-934939 INFO     [AgentScheduler] Registering APIs
12:24:01-386561 DEBUG    Scripts setup: time=0.413 ['XYZ Grid:0.048', 'IP Adapters:0.042']
12:24:01-388049 DEBUG    Model metadata: file="metadata.json" no changes
12:24:01-388622 INFO     Model: autoload=True selected="Diffusers\black-forest-labs/FLUX.1-Krea-dev [8162a9c7b0]"
12:24:01-390957 DEBUG    Model requested: fn=threading.py:run:<lambda>
12:24:01-392009 INFO     Load model: select="Diffusers\black-forest-labs/FLUX.1-Krea-dev [8162a9c7b0]"
12:24:01-395169 INFO     Autodetect model: detect="FLUX" class=FluxPipeline
                         file="models\Diffusers\models--black-forest-labs--FLUX.1-Krea-dev\snapshots\8162a9c7b05a641be09
                         8422bf2fcf335615c2f28"
12:24:01-396235 DEBUG    Cache clear
12:24:02-283139 INFO     HF login: token="hf_...UtOy" fn="D:\huggingface\hub\token"
12:24:02-431207 DEBUG    Load model: type=Flux repo="black-forest-labs/FLUX.1-Krea-dev" cls=FluxPipeline
                         offload=balanced dtype=torch.bfloat16 args={'torch_dtype': torch.bfloat16}
12:24:02-445704 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
12:24:02-446716 DEBUG    Load model: transformer="black-forest-labs/FLUX.1-Krea-dev" cls=FluxTransformer2DModel
                         subfolder=transformer quant="SDNQConfig" args={'torch_dtype': torch.bfloat16}
Progress ?it/s ███████████████████████████████ 100% 3/3 00:00 ? Fetching 3 files
Progress ?it/s                          0% 0/3 00:00 ? Loading checkpoint shards12:24:03-522139 DEBUG    UI: connected  
12:24:03-523572 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0031
Progress 17.03s/it ██████████████ 100% 3/3 00:51 00:00 Loading checkpoint shards
12:24:54-394917 DEBUG    GC: current={'gpu': 1.66, 'ram': 26.27, 'oom': 0} prev={'gpu': 1.66, 'ram': 26.28} load={'gpu':
                         7, 'ram': 41} gc={'gpu': 0.0, 'py': 2778}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.30
12:24:54-408842 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
12:24:54-413055 DEBUG    Load model: text_encoder="Disty0/t5-xxl" cls=T5EncoderModel quant="SDNQConfig" shared=True
                         args={'torch_dtype': torch.bfloat16, 'config': T5Config {
                           "architectures": [
                             "T5EncoderModel"
                           ],
                           "classifier_dropout": 0.0,
                           "d_ff": 10240,
                           "d_kv": 64,
                           "d_model": 4096,
                           "decoder_start_token_id": 0,
                           "dense_act_fn": "gelu_new",
                           "dropout_rate": 0.1,
                           "dtype": "bfloat16",
                           "eos_token_id": 1,
                           "feed_forward_proj": "gated-gelu",
                           "initializer_factor": 1.0,
                           "is_encoder_decoder": true,
                           "is_gated_act": true,
                           "layer_norm_epsilon": 1e-06,
                           "model_type": "t5",
                           "num_decoder_layers": 24,
                           "num_heads": 64,
                           "num_layers": 24,
                           "output_past": true,
                           "pad_token_id": 0,
                           "relative_attention_max_distance": 128,
                           "relative_attention_num_buckets": 32,
                           "tie_word_embeddings": false,
                           "transformers_version": "4.57.1",
                           "use_cache": true,
                           "vocab_size": 32128
                         }
                         }
Progress ?it/s ███████████████████████████████ 100% 2/2 00:00 ? Fetching 2 files
Progress  7.67s/it ██████████████ 100% 2/2 00:15 00:00 Loading checkpoint shards
12:25:10-804255 DEBUG    GC: current={'gpu': 1.77, 'ram': 33.97, 'oom': 0} prev={'gpu': 2.61, 'ram': 33.98} load={'gpu':
                         7, 'ram': 53} gc={'gpu': 0.84, 'py': 132}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.28
Progress 19.16it/s ██████████████ 100% 1/1 00:00 00:00 Loading checkpoint shards
Progress 17.26it/s █████████ 100% 7/7 00:00 00:00 Loading pipeline components...
12:25:11-820986 DEBUG    GC: current={'gpu': 1.77, 'ram': 34.04, 'oom': 0} prev={'gpu': 1.77, 'ram': 34.04} load={'gpu':
                         7, 'ram': 53} gc={'gpu': 0.0, 'py': 131} fn=load_diffuser_force:load_flux why=load time=0.29
12:25:11-825198 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}
12:25:11-826237 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=64.000 limit=0.00
                         always=['T5EncoderModel', 'UMT5EncoderModel'] never=['CLIPTextModel',
                         'CLIPTextModelWithProjection', 'AutoencoderKL'] pre=True streams=False
12:25:11-850509 DEBUG    Module: name=transformer cls=FluxTransformer2DModel size=11.498 params=12075876416
                         quant=QuantizationMethod.SDNQ
12:25:11-860222 DEBUG    Module: name=text_encoder_2 cls=T5EncoderModel size=7.460 params=4810381312
                         quant=QuantizationMethod.SDNQ
12:25:11-862787 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.229 params=123060480 quant=None
12:25:11-865943 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83819683 quant=None
12:25:11-866660 INFO     Model class=FluxPipeline modules=4 size=19.343
12:25:11-870029 INFO     Load model: family=f1 time={'total': 70.48, 'load': 70.43} native=1024 memory={'ram': {'total':
                         63.92, 'rss': 20.7, 'used': 34.03, 'free': 29.89, 'avail': 29.89, 'buffers': 0, 'cached': 0},
                         'gpu': {'used': 1.77, 'total': 23.99, 'active': 0.02, 'peak': 0.54, 'retries': 0, 'oom': 0,
                         'swap': 0}, 'job': ''}
12:25:11-872887 DEBUG    Script init: ['system-info.py:app_started=0.09', 'task_scheduler.py:app_started=0.46']
12:25:11-874736 INFO     Startup time: total=139.56 checkpoint=70.49 launch=14.66 loader=14.48 installer=14.47
                         torch=10.10 libraries=5.85 gradio=1.43 ui-extensions=1.38 diffusers=1.31 extensions=1.08
                         app-started=0.55 ui-networks=0.51 bnb=0.44 cleanup=0.37 ui-control=0.30 upscalers=0.30
                         ui-info=0.28 ui-txt2img=0.22 ui-img2img=0.19 ui-models=0.16 ui-defaults=0.16 api=0.13
                         detailer=0.11 ui-video=0.09 samplers=0.08 networks=0.07 onnx=0.06 ui-gallery=0.06
                         ui-extras=0.05 cv2=0.05
12:25:11-879283 DEBUG    Save: file="C:\ai\sdnext\config.json" json=34 bytes=1421 time=0.006
12:25:15-434249 DEBUG    Cache clear
12:25:15-435752 DEBUG    Current model: {'ram': {'total': 63.92, 'rss': 20.77, 'used': 34.14, 'free': 29.78, 'avail':
                         29.78, 'buffers': 0, 'cached': 0}, 'gpu': {'used': 1.77, 'total': 23.99, 'active': 0.02,
                         'peak': 0.54, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load FramePack'}
12:25:16-249926 DEBUG    GC: current={'gpu': 1.77, 'ram': 34.1, 'oom': 0} prev={'gpu': 1.77, 'ram': 34.13} load={'gpu':
                         7, 'ram': 53} gc={'gpu': 0.0, 'py': 49519} fn=load_model:unload_model_weights why=unload
                         time=0.31
12:25:16-252411 DEBUG    Unload model: {'ram': {'total': 63.92, 'rss': 20.76, 'used': 34.1, 'free': 29.82, 'avail':
                         29.82, 'buffers': 0, 'cached': 0}, 'gpu': {'used': 1.77, 'total': 23.99, 'active': 0.02,
                         'peak': 0.54, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load FramePack'} after
12:25:16-741324 DEBUG    FramePack load: module=llm {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder':
                         'text_encoder'}
12:25:16-742529 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
Progress  5.76s/it ██████████████ 100% 4/4 00:23 00:00 Loading checkpoint shards
12:25:40-491040 DEBUG    GC: current={'gpu': 1.82, 'ram': 31.84, 'oom': 0} prev={'gpu': 3.47, 'ram': 31.85} load={'gpu':
                         8, 'ram': 50} gc={'gpu': 1.65, 'py': 285}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.31
12:25:41-272717 DEBUG    FramePack load: module=te {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder':
                         'text_encoder_2'}
Progress  1.77it/s ██████████████ 100% 1/1 00:00 00:00 Loading checkpoint shards
12:25:42-563431 DEBUG    FramePack load: module=vae {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder': 'vae'}
12:25:44-651865 DEBUG    FramePack load: module=encoder {'repo': 'lllyasviel/flux_redux_bfl', 'subfolder':
                         'feature_extractor'} model={'repo': 'lllyasviel/flux_redux_bfl', 'subfolder': 'image_encoder'}
Progress  5.85it/s ██████████████ 100% 1/1 00:00 00:00 Loading checkpoint shards
12:25:45-596838 DEBUG    FramePack load: module=transformer {'repo': 'lllyasviel/FramePackI2V_HY', 'subfolder': ''}
12:25:45-597838 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
Progress 4791.66it/s █████████████████████ 100% 3/3 00:00 00:00 Fetching 3 files
Progress 19.85s/it ██████████████ 100% 3/3 00:59 00:00 Loading checkpoint shards
12:26:46-241719 DEBUG    GC: current={'gpu': 1.82, 'ram': 35.77, 'oom': 0} prev={'gpu': 1.82, 'ram': 35.77} load={'gpu':
                         8, 'ram': 56} gc={'gpu': 0.0, 'py': 235}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.34
12:26:46-265687 INFO     FramePack load: model=FramepackHunyuanVideoPipeline variant="bi-directional" type=hunyuanvideo
                         time=90.01
12:26:46-267003 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=64.000 limit=0.00
                         always=['T5EncoderModel', 'UMT5EncoderModel'] never=['CLIPTextModel',
                         'CLIPTextModelWithProjection', 'AutoencoderKL'] pre=True streams=False
12:26:46-296338 DEBUG    Module: name=transformer cls=HunyuanVideoTransformer3DModelPacked size=12.363
                         params=13065642112 quant=QuantizationMethod.SDNQ
12:26:46-302723 DEBUG    Module: name=text_encoder cls=LlamaModel size=7.638 params=7590449152
                         quant=QuantizationMethod.SDNQ
12:26:46-306787 DEBUG    Module: name=image_processor cls=SiglipVisionModel size=0.798 params=428225600 quant=None
12:26:46-309957 DEBUG    Module: name=vae cls=AutoencoderKLHunyuanVideo size=0.459 params=246478803 quant=None
12:26:46-312634 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModel size=0.229 params=123060480 quant=None
12:26:46-314553 INFO     Model class=FramepackHunyuanVideoPipeline modules=5 size=21.487
12:26:46-604732 DEBUG    GC: current={'gpu': 1.82, 'ram': 35.77, 'oom': 0} prev={'gpu': 1.82, 'ram': 35.77} load={'gpu':
                         8, 'ram': 56} gc={'gpu': 0.0, 'py': 638} fn=load_model:load_model why=load time=0.29
12:26:46-626038 INFO     FramePack start: mode=i2v variant="bi-directional" frames=67 sections=2 resolution=640
                         seed=230306629 duration=4 teacache=True thres=0.15 cfgzero=False
12:26:46-627406 INFO     FramePack params: steps=25 start=1 end=1 vision=1 scale=1 distilled=10 rescale=0 shift=3
Traceback (most recent call last):
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\utils.py", line 503, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\ai\sdnext\venv\Lib\site-packages\gradio\utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\ai\sdnext\modules\framepack\framepack_wrappers.py", line 153, in run_framepack
    init_image = prepare_image(init_image, resolution)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\sdnext\modules\framepack\framepack_wrappers.py", line 30, in prepare_image
    h, w, _c = image.shape
               ^^^^^^^^^^^
AttributeError: 'Image' object has no attribute 'shape'
```

### Backend

Diffusers

### Compute

nVidia CUDA

### Interface

Standard

### Branch

Dev

### Model

Any Video Model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
thanks, posted a fix to dev branch.

**Comment by SAC020** [comment]
Now I'm getting a different error, "Model load failed" in the UI. No error in log, but no progress either


<img width="3731" height="1194" alt="Image" src="https://github.com/user-attachments/assets/be50ff21-d7c6-442b-a126-11c8b4e5a016" />


```
PS C:\ai\sdnext> .\webui.bat --debug
Using VENV: C:\ai\sdnext\venv
18:47:01-769329 INFO     Starting SD.Next
18:47:01-771661 INFO     Logger: file="C:\ai\sdnext\sdnext.log" level=DEBUG host="SEB-PC" size=74 mode=create
18:47:01-773274 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\sdnext\venv\Scripts\python.exe"
                         venv="C:\ai\sdnext\venv"
18:47:02-045767 INFO     Version: app=sd.next updated=2025-10-31 hash=526472a92 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev ui=dev
18:47:02-852243 INFO     Version: app=sd.next latest=2025-10-31T16:32:09Z hash=3f3038ae branch=dev
18:47:02-868505 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26200-SP0 python=3.11.9 locale=('English_United States', '1250')
                         docker=False
18:47:02-872473 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
18:47:02-874213 INFO     Args: ['--debug']
18:47:02-875761 DEBUG    Setting environment tuning
18:47:02-876824 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
18:47:02-879077 INFO     Verifying torch installation
18:47:02-879598 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
18:47:02-897887 INFO     CUDA: nVidia toolkit detected
18:47:05-082287 INFO     Torch backend: version="2.7.1+cu128" type=CUDA CUDA=12.8 cuDNN=90701
18:47:05-086287 INFO     Torch detected: gpu="NVIDIA GeForce RTX 4090" vram=24564 arch=(8, 9) cores=128
18:47:05-222334 WARNING  Modified files: ['scripts/detect_extension.py']
18:47:05-341258 INFO     Install: verifying requirements
18:47:05-391010 DEBUG    Timestamp repository update time: Fri Oct 31 17:04:28 2025
18:47:05-391587 INFO     Startup: standard
18:47:05-392410 INFO     Verifying submodules
18:47:08-983585 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-chainner" reattach=main
18:47:08-984589 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
18:47:09-127780 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
18:47:09-128777 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
18:47:09-274969 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=dev
18:47:09-275971 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
18:47:09-484378 DEBUG    Git detached head detected: folder="extensions-builtin/stable-diffusion-webui-rembg"
                         reattach=master
18:47:09-484985 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
18:47:09-625292 DEBUG    Git detached head detected: folder="wiki" reattach=master
18:47:09-626466 DEBUG    Git submodule: wiki / master
18:47:09-828730 DEBUG    Installed packages: 289
18:47:09-830346 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
18:47:10-177393 DEBUG    Extension installer: builtin=True
                         file="C:\ai\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py"
18:47:10-414985 DEBUG    Extension installer: builtin=True
                         file="C:\ai\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py"
18:47:10-534199 DEBUG    Extensions all: ['canvas-zoom', 'sd-webui-openpose-editor']
18:47:10-536111 DEBUG    Extension installer: builtin=False file="C:\ai\sdnext\extensions\canvas-zoom\install.py"
18:47:15-014481 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg', 'canvas-zoom',
                         'sd-webui-openpose-editor']
18:47:15-132315 INFO     Install: verifying requirements
18:47:15-135933 DEBUG    Setup complete without errors: 1761929235
18:47:15-142585 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
18:47:15-144431 INFO     Installer time: total=19.47 git=4.53 canvas-zoom=4.36 submodules=4.32 torch=2.21 latest=1.07
                         branch=0.82 base=0.42 version=0.26 requirements=0.24 installed=0.24 files=0.14
                         stable-diffusion-webui-rembg=0.12 sd-webui-agent-scheduler=0.12 sd-extension-chainner=0.12
                         sdnext-modernui=0.12 sd-webui-openpose-editor=0.11 sd-extension-system-info=0.11 Lora=0.11
18:47:15-146443 INFO     Command line args: ['--debug'] args=[]
18:47:15-147248 DEBUG    Env flags: []
18:47:15-147750 DEBUG    Starting module: <module 'webui' from 'C:\\ai\\sdnext\\webui.py'>
18:47:28-187434 INFO     Torch: torch==2.7.1+cu128 torchvision==0.22.1+cu128
18:47:28-190044 INFO     Packages: diffusers==0.36.0.dev0 transformers==4.57.1 accelerate==1.11.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0
18:47:29-254515 DEBUG    ONNX: version=1.22.1, available=['AzureExecutionProvider', 'CPUExecutionProvider']
18:47:29-427292 DEBUG    State initialized: id=2141332069008
18:47:29-493801 INFO     Device detect: memory=24.0 default=balanced optimization=highvram
18:47:29-500400 DEBUG    Read: file="C:\ai\sdnext\config.json" json=34 bytes=1463 time=0.000 fn=<module>:load
18:47:29-502674 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
18:47:29-504758 DEBUG    Read: file="html\reference.json" json=136 bytes=66290 time=0.001
                         fn=_call_with_frames_removed:<module>
18:47:29-505803 DEBUG    Torch cuDNN: benchmark=True
18:47:29-506862 DEBUG    Torch attention: type="sdpa" opts=['Flash attention', 'Memory attention', 'Math attention']
18:47:29-508780 DEBUG    Torch attention installed: flashattn=False sageattention=False
18:47:29-509778 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False
                         xla=False xformers=False
18:47:33-153060 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=3.59
18:47:33-154524 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=pass optimization="Scaled-Dot-Product"
18:47:33-231587 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_120 capability=(8, 9) cuda=12.8 cudnn=90701
                         driver=581.57
18:47:33-475274 DEBUG    Entering start sequence
18:47:33-479375 DEBUG    Initializing
18:47:33-485096 DEBUG    Read: file="metadata.json" json=530 bytes=797984 time=0.004 fn=initialize:init_metadata
18:47:33-487294 DEBUG    Read: file="cache.json" json=2 bytes=6600 time=0.001 fn=initialize:init_cache
18:47:33-554749 INFO     Available VAEs: path="models\VAE" items=0
18:47:33-556234 INFO     Available UNets: path="models\UNET" items=0
18:47:33-557475 INFO     Available TEs: path="models\Text-encoder" items=4
18:47:33-605088 INFO     Available Models: safetensors="models\Stable-diffusion":22 diffusers="models\Diffusers":11
                         reference=136 items=33 time=0.05
18:47:33-660785 INFO     Available LoRAs: path="models\Lora" items=235 folders=3 time=0.04
18:47:33-681640 INFO     Available Styles: path="models\styles" items=288 time=0.02
18:47:33-787836 INFO     Available Detailer: path="models\yolo" items=12 downloaded=4
18:47:33-789241 DEBUG    Extensions: disabled=['Lora', 'sdnext-modernui']
18:47:33-790277 INFO     Load extensions
18:47:34-533240 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
18:47:34-547695 DEBUG    Extensions init time: total=0.76 sd-webui-agent-scheduler=0.45 cogvideo.py=0.07
                         sd-extension-chainner=0.06
18:47:35-018428 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.001 fn=__init__:__init__
18:47:35-020245 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
18:47:35-025818 DEBUG    Available chaiNNer: path="models\chaiNNer" defined=25 discovered=0 downloaded=10
18:47:35-035890 INFO     Available Upscalers: items=79 downloaded=24 user=3 time=0.48 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN',
                         'SCUNet', 'Diffusion', 'SeedVR', 'SwinIR']
18:47:35-099194 INFO     Networks: type="video" engines=11 models=54 errors=0 time=0.05
18:47:35-103751 INFO     Huggingface: transfer=rust parallel=True direct=False token="hf_...UtOy"
                         cache="D:\huggingface\hub" init
18:47:35-401531 DEBUG    Huggingface: cache="D:\huggingface\hub" size=630450 MB
18:47:35-402570 DEBUG    UI start sequence
18:47:35-417608 INFO     UI locale: name="Auto"
18:47:35-418748 INFO     UI theme: type=Standard name="black-teal" available=14
18:47:35-421227 DEBUG    UI theme: css="C:\ai\sdnext\javascript\black-teal.css" base="['sdnext.css', 'timesheet.css']"
                         user="None"
18:47:35-424624 DEBUG    UI initialize: tab=txt2img
18:47:35-561134 DEBUG    Read: file="html\reference.json" json=136 bytes=66290 time=0.002 fn=list_items:list_reference
18:47:35-612122 DEBUG    Networks: type="reference" items={'total': 136, 'ready': 1, 'hidden': 0, 'experimental': 0,
                         'base': 87, 'distilled': 17, 'quantized': 15, 'community': 15}
18:47:35-633062 DEBUG    Networks: type="model" items=167 subfolders=7 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Reference', 'C:\\ai\\sdnext\\models\\Stable-diffusion'] list=0.18 thumb=0.02 desc=0.02
                         info=0.11 workers=12
18:47:35-641196 DEBUG    Networks: type="lora" items=235 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.16
                         thumb=0.04 desc=0.14 info=0.34 workers=12
18:47:35-651710 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.11 thumb=0.00 desc=0.00 info=0.00 workers=12
18:47:35-656049 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models\\wildcards']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
18:47:35-659125 DEBUG    Networks: type="embedding" items=13 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.09 thumb=0.02 desc=0.00 info=0.02 workers=12
18:47:35-660552 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
18:47:35-662266 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
18:47:35-910350 DEBUG    UI initialize: tab=img2img
18:47:36-167032 DEBUG    UI initialize: tab=control models="models\control"
18:47:36-370544 DEBUG    Script: fn="extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py" type=control
                         skip
18:47:36-612746 DEBUG    UI initialize: tab=video
18:47:36-757843 DEBUG    UI initialize: tab=process
18:47:36-812849 DEBUG    UI initialize: tab=caption
18:47:36-933448 DEBUG    UI initialize: tab=models
18:47:37-017181 DEBUG    UI initialize: tab=gallery
18:47:37-074673 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000 fn=__init__:read_from_file
18:47:37-075479 DEBUG    UI initialize: tab=settings
18:47:37-079767 DEBUG    Settings: sections=25 settings=410/624 quicksettings=0
18:47:37-627741 DEBUG    UI initialize: tab=info
18:47:37-657449 DEBUG    UI initialize: tab=extensions
18:47:38-739422 DEBUG    Extension list: processed=412 installed=7 enabled=6 disabled=1 visible=412 hidden=0
18:47:38-988806 DEBUG    Root paths: ['C:\\ai\\sdnext', 'models']
18:47:39-101411 INFO     Local URL: http://127.0.0.1:7860/
18:47:39-102459 INFO     API docs: http://127.0.0.1:7860/docs
18:47:39-103969 INFO     API redocs: http://127.0.0.1:7860/redocs
18:47:39-106062 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
18:47:39-107564 DEBUG    API initialize
18:47:39-348105 INFO     [AgentScheduler] Task queue is empty
18:47:39-349107 INFO     [AgentScheduler] Registering APIs
18:47:39-804623 DEBUG    Scripts setup: time=0.419 ['XYZ Grid:0.048', 'IP Adapters:0.04']
18:47:39-805644 DEBUG    Model metadata: file="metadata.json" no changes
18:47:39-806653 INFO     Model: autoload=True selected="Diffusers\black-forest-labs/FLUX.1-Krea-dev [8162a9c7b0]"
18:47:39-808866 DEBUG    Model requested: fn=threading.py:run:<lambda>
18:47:39-809961 DEBUG    Search model: name="Diffusers\black-forest-labs/FLUX.1-Krea-dev [8162a9c7b0]"
                         matched="models\Diffusers\models--black-forest-labs--FLUX.1-Krea-dev\snapshots\8162a9c7b05a641b
                         e098422bf2fcf335615c2f28" type=alias
18:47:39-811025 INFO     Load model: select="Diffusers\black-forest-labs/FLUX.1-Krea-dev [8162a9c7b0]"
18:47:39-814698 INFO     Autodetect model: detect="FLUX" class=FluxPipeline
                         file="models\Diffusers\models--black-forest-labs--FLUX.1-Krea-dev\snapshots\8162a9c7b05a641be09
                         8422bf2fcf335615c2f28"
18:47:39-815834 DEBUG    Cache clear
18:47:40-370743 INFO     HF login: token="hf_...UtOy" fn="D:\huggingface\hub\token"
18:47:40-527998 DEBUG    Load model: type=Flux repo="black-forest-labs/FLUX.1-Krea-dev" cls=FluxPipeline
                         offload=balanced dtype=torch.bfloat16 args={'torch_dtype': torch.bfloat16}
18:47:40-543125 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
18:47:40-545767 DEBUG    Load model: transformer="black-forest-labs/FLUX.1-Krea-dev" cls=FluxTransformer2DModel
                         subfolder=transformer quant="SDNQConfig" args={'torch_dtype': torch.bfloat16}
Progress ?it/s ███████████████████████████████ 100% 3/3 00:00 ? Fetching 3 files
Progress 17.87s/it ██████████████ 100% 3/3 00:53 00:00 Loading checkpoint shards
18:48:35-300753 DEBUG    GC: current={'gpu': 1.66, 'ram': 25.55, 'oom': 0} prev={'gpu': 1.66, 'ram': 25.53} load={'gpu':
                         7, 'ram': 40} gc={'gpu': 0.0, 'py': 2773}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.31
18:48:35-315264 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
18:48:35-318570 DEBUG    Load model: text_encoder="Disty0/t5-xxl" cls=T5EncoderModel quant="SDNQConfig" shared=True
Progress ?it/s ███████████████████████████████ 100% 2/2 00:00 ? Fetching 2 files
Progress  7.90s/it ██████████████ 100% 2/2 00:15 00:00 Loading checkpoint shards
18:48:52-629608 DEBUG    GC: current={'gpu': 1.77, 'ram': 33.08, 'oom': 0} prev={'gpu': 2.39, 'ram': 33.03} load={'gpu':
                         7, 'ram': 52} gc={'gpu': 0.62, 'py': 127}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.47
Progress 13.93it/s ██████████████ 100% 1/1 00:00 00:00 Loading checkpoint shards
Progress 11.74it/s █████████ 100% 7/7 00:00 00:00 Loading pipeline components...
18:48:53-903563 DEBUG    GC: current={'gpu': 1.77, 'ram': 33.24, 'oom': 0} prev={'gpu': 1.77, 'ram': 33.23} load={'gpu':
                         7, 'ram': 52} gc={'gpu': 0.0, 'py': 131} fn=load_diffuser_force:load_flux why=load time=0.37
18:48:53-907300 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}
18:48:53-908645 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=64.000 limit=0.00
                         always=['T5EncoderModel', 'UMT5EncoderModel'] never=['CLIPTextModel',
                         'CLIPTextModelWithProjection', 'AutoencoderKL'] pre=True streams=False
18:48:53-933075 DEBUG    Module: name=transformer cls=FluxTransformer2DModel size=11.498 params=12075876416
                         quant=QuantizationMethod.SDNQ
18:48:53-942190 DEBUG    Module: name=text_encoder_2 cls=T5EncoderModel size=7.460 params=4810381312
                         quant=QuantizationMethod.SDNQ
18:48:53-945067 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.229 params=123060480 quant=None
18:48:53-948754 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83819683 quant=None
18:48:53-949752 INFO     Model class=FluxPipeline modules=4 size=19.343
18:48:53-952834 INFO     Load model: family=FluxPipeline time={'total': 74.14, 'load': 74.09} native=1024 memory={'ram':
                         {'total': 63.92, 'rss': 20.69, 'used': 33.24, 'free': 30.68, 'avail': 30.68, 'buffers': 0,
                         'cached': 0}, 'gpu': {'used': 1.77, 'total': 23.99, 'active': 0.02, 'peak': 0.49, 'retries': 0,
                         'oom': 0, 'swap': 0}, 'job': ''}
18:48:53-956786 DEBUG    Script init: ['system-info.py:app_started=0.10', 'task_scheduler.py:app_started=0.46']
18:48:53-957827 INFO     Startup time: total=140.57 checkpoint=74.15 launch=14.12 loader=13.92 installer=13.92
                         torch=9.13 libraries=5.90 ui-extensions=1.66 gradio=1.47 diffusers=1.29 extensions=0.76
                         app-started=0.56 ui-networks=0.52 upscalers=0.49 bnb=0.39 ui-control=0.31 cleanup=0.30
                         ui-txt2img=0.21 ui-img2img=0.19 ui-defaults=0.16 ui-models=0.16 api=0.14 detailer=0.11
                         ui-video=0.09 samplers=0.08 networks=0.07 ui-extras=0.06 onnx=0.06 ui-gallery=0.06 cv2=0.06
                         lora=0.06
18:48:53-962181 DEBUG    Save: file="C:\ai\sdnext\config.json" json=34 bytes=1421 time=0.005
18:50:53-998996 TRACE    Server: alive=True requests=1 memory=33.04/63.92 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=4 step=0 steps=0 queued=0 uptime=205 elapsed=120.04
                         eta=None progress=0
18:51:39-698767 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 0.974
18:51:44-440638 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.0039
18:51:45-592620 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0005
18:51:45-595841 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0
18:51:45-598789 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.0035
18:51:45-621156 INFO     UI: ready time=9549
18:51:45-775228 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0009
18:51:45-775758 DEBUG    UI: connected
18:52:01-076377 DEBUG    Settings overrides: ['Model: FLUX.1-Krea-dev']
18:52:54-056380 TRACE    Server: alive=True requests=236 memory=33.49/63.92 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=4 step=0 steps=0 queued=0 uptime=325 elapsed=240.1 eta=None
                         progress=0
18:53:03-850190 DEBUG    Cache clear
18:53:03-851764 DEBUG    Current model: {'ram': {'total': 63.92, 'rss': 20.78, 'used': 33.57, 'free': 30.35, 'avail':
                         30.35, 'buffers': 0, 'cached': 0}, 'gpu': {'used': 1.77, 'total': 23.99, 'active': 0.02,
                         'peak': 0.49, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load FramePack'}
18:53:04-662907 DEBUG    GC: current={'gpu': 1.77, 'ram': 33.56, 'oom': 0} prev={'gpu': 1.77, 'ram': 33.58} load={'gpu':
                         7, 'ram': 53} gc={'gpu': 0.0, 'py': 50630} fn=load_model:unload_model_weights why=unload
                         time=0.33
18:53:04-664914 DEBUG    Unload model: {'ram': {'total': 63.92, 'rss': 20.76, 'used': 33.56, 'free': 30.36, 'avail':
                         30.36, 'buffers': 0, 'cached': 0}, 'gpu': {'used': 1.77, 'total': 23.99, 'active': 0.02,
                         'peak': 0.49, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load FramePack'} after
18:53:05-214068 DEBUG    FramePack load: module=llm {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder':
                         'text_encoder'}
18:53:05-215769 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
Progress  5.60s/it ██████████████ 100% 4/4 00:22 00:00 Loading checkpoint shards
18:53:28-277921 DEBUG    GC: current={'gpu': 1.82, 'ram': 31.36, 'oom': 0} prev={'gpu': 3.25, 'ram': 31.36} load={'gpu':
                         8, 'ram': 49} gc={'gpu': 1.43, 'py': 241}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.29
18:53:29-111358 DEBUG    FramePack load: module=te {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder':
                         'text_encoder_2'}
Progress  1.99it/s ██████████████ 100% 1/1 00:00 00:00 Loading checkpoint shards
18:53:30-322022 DEBUG    FramePack load: module=vae {'repo': 'hunyuanvideo-community/HunyuanVideo', 'subfolder': 'vae'}
18:53:32-372502 DEBUG    FramePack load: module=encoder {'repo': 'lllyasviel/flux_redux_bfl', 'subfolder':
                         'feature_extractor'} model={'repo': 'lllyasviel/flux_redux_bfl', 'subfolder': 'image_encoder'}
Progress  5.93it/s ██████████████ 100% 1/1 00:00 00:00 Loading checkpoint shards
18:53:33-319193 DEBUG    FramePack load: module=transformer {'repo': 'lllyasviel/FramePackI2V_HY', 'subfolder': ''}
18:53:33-320513 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 matmul=True group_size=0 svd_rank=32
                         svd_steps=8 use_svd=True quant_conv=False matmul_conv=False dequantize_fp32=False
                         quantize_with_gpu=True quantization_device=cuda return_device=cpu device_map=default
                         offload_mode=balanced non_blocking=False modules_to_not_convert=[] modules_dtype_dict={}
Progress ?it/s ███████████████████████████████ 100% 3/3 00:00 ? Fetching 3 files
Progress 19.94s/it ██████████████ 100% 3/3 00:59 00:00 Loading checkpoint shards
18:54:34-207377 DEBUG    GC: current={'gpu': 1.82, 'ram': 36.92, 'oom': 0} prev={'gpu': 1.82, 'ram': 36.84} load={'gpu':
                         8, 'ram': 58} gc={'gpu': 0.0, 'py': 280}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.44
18:54:34-235669 INFO     FramePack load: model=FramepackHunyuanVideoPipeline variant="bi-directional"
                         type=FramepackHunyuanVideoPipeline time=89.57
18:54:34-237111 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=64.000 limit=0.00
                         always=['T5EncoderModel', 'UMT5EncoderModel'] never=['CLIPTextModel',
                         'CLIPTextModelWithProjection', 'AutoencoderKL'] pre=True streams=False
18:54:34-270064 DEBUG    Module: name=transformer cls=HunyuanVideoTransformer3DModelPacked size=12.687
                         params=13059126336 quant=QuantizationMethod.SDNQ
18:54:34-276218 DEBUG    Module: name=text_encoder cls=LlamaModel size=7.638 params=7590449152
                         quant=QuantizationMethod.SDNQ
18:54:34-281606 DEBUG    Module: name=image_processor cls=SiglipVisionModel size=0.798 params=428225600 quant=None
18:54:34-285674 DEBUG    Module: name=vae cls=AutoencoderKLHunyuanVideo size=0.459 params=246478803 quant=None
18:54:34-288077 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModel size=0.229 params=123060480 quant=None
18:54:34-289836 INFO     Model class=FramepackHunyuanVideoPipeline modules=5 size=21.811
18:54:34-621115 DEBUG    GC: current={'gpu': 1.82, 'ram': 36.95, 'oom': 0} prev={'gpu': 1.82, 'ram': 36.93} load={'gpu':
                         8, 'ram': 58} gc={'gpu': 0.0, 'py': 638} fn=load_model:load_model why=load time=0.33
18:54:54-625249 TRACE    Server: alive=True requests=394 memory=37.72/63.92 status='idle' task='' timestamp=None
                         current='' id='' job=0 jobs=0 total=5 step=0 steps=0 queued=0 uptime=445 elapsed=20.0 eta=None
                         progress=0

```

**Comment by vladmandic** [comment]
i believe that was a side-effect of another issue that has been resolved. please update.

**Comment by SAC020** [comment]
It works now, thank you!
