### ISSUE TITLE
[Issue]: rocBLAS error: Could not load gfx1103

### ISSUE THREAD

**Issue by NakedSnake28** [vladmandic/sdnext#4405]
### Issue Description

Hi. I tried to install ZLUDU on the 780M. Installed HIP SDK 6.4.2, installed the unofficial rocBLAS library for gfx1103 (780M). I followed the installation recommendations and as a result I get the error rocBLAS error: 

Could not load C:\Program Files\AMD\ROCm\6.4\bin\/rocblas/library/TensileLibrary_lazy_gfx1103.dat

rocBLAS error: Could not initialize Tensile library

### Version Platform Description

Microsoft Windows-10-10.0.26100-SP0 (Microsoft Windows 11 Pro 24H2), gfx1103, Firefox

### Relevant log output

```shell
PS C:\SDNext\sdnext> ./webui.bat --debug --use-zluda --lowram
Using VENV: C:\SDNext\sdnext\venv
22:57:16-645467 INFO     Starting SD.Next
22:57:16-645467 INFO     Logger: file="C:\SDNext\sdnext\sdnext.log" level=DEBUG host="Snake" size=73 mode=create
22:57:16-645467 INFO     Python: version=3.10.6 platform=Windows bin="C:\SDNext\sdnext\venv\Scripts\python.exe"
                         venv="C:\SDNext\sdnext\venv"
22:57:16-645467 WARNING  Python: version=3.10.6 is not actively supported
22:57:16-880335 INFO     Version: app=sd.next updated=2025-11-14 hash=e38a711c6 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master ui=main
22:57:17-436681 INFO     Version: app=sd.next latest=2025-11-14T14:52:21Z hash=e38a711c branch=master
22:57:17-437183 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD system=Windows
                         release=Windows-10-10.0.26100-SP0 python=3.10.6 locale=('Russian_Russia', '1251') docker=False
22:57:17-437183 DEBUG    Packages: prefix=venv site=['venv', 'venv\\lib\\site-packages']
22:57:17-448735 INFO     Args: ['--debug', '--use-zluda', '--lowram']
22:57:17-448735 DEBUG    Setting environment tuning
22:57:17-448735 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
22:57:17-451859 INFO     Verifying torch installation
22:57:17-451859 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
HIP Library Path: C:\Windows\System32\amdhip64_7.dll
22:57:17-512341 INFO     ROCm: AMD toolkit detected
22:57:17-512341 INFO     ROCm: agents=['gfx1103']
22:57:17-514904 INFO     ROCm: version=6.4, using agent gfx1103
22:57:17-733645 INFO     ZLUDA load: path='C:\SDNext\sdnext\.zluda' nightly=False
22:57:18-061281 INFO     ROCm: HSA_OVERRIDE_GFX_VERSION config overridden: device=gfx1103 version=11.0.0
22:57:24-258793 INFO     Torch backend: version="2.7.1+cu118" type=CUDA CUDA=11.8 cuDNN=90100
22:57:24-347072 INFO     Torch detected: gpu="AMD Radeon 780M Graphics [ZLUDA]" vram=6346 arch=(8, 8) cores=6
22:57:25-286296 INFO     Install: verifying requirements
22:57:25-349727 DEBUG    Timestamp repository update time: Fri Nov 14 18:52:21 2025
22:57:25-349727 INFO     Startup: standard
22:57:25-349727 INFO     Verifying submodules
22:57:28-337325 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
22:57:28-505607 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
22:57:28-507113 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
22:57:28-648928 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
22:57:28-648928 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
22:57:28-751602 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
22:57:28-900272 DEBUG    Git detached head detected: folder="wiki" reattach=master
22:57:28-901778 DEBUG    Git submodule: wiki / master
22:57:29-044298 DEBUG    Installed packages: 253
22:57:29-044298 DEBUG    Extensions all: ['sd-extension-chainner', 'sd-extension-system-info', 'sdnext-modernui',
                         'stable-diffusion-webui-rembg']
22:57:29-282804 DEBUG    Extension installer: builtin=True
                         file="C:\SDNext\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py"
22:57:29-361434 DEBUG    Extensions all: []
22:57:29-361434 INFO     Extensions enabled: ['sd-extension-chainner', 'sd-extension-system-info', 'sdnext-modernui',
                         'stable-diffusion-webui-rembg']
22:57:29-439870 INFO     Install: verifying requirements
22:57:29-439870 DEBUG    Setup complete without errors: 1763319449
22:57:29-455602 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
22:57:29-455602 INFO     Installer time: total=18.63 torch=7.60 git=3.86 submodules=3.63 latest=0.79 branch=0.69
                         amd=0.55 base=0.44 version=0.23 requirements=0.17 installed=0.16 files=0.15
22:57:29-455602 INFO     Command line args: ['--debug', '--use-zluda', '--lowram'] lowram=True use_zluda=True args=[]
22:57:29-455602 DEBUG    Env flags: []
22:57:29-455602 DEBUG    Starting module: <module 'webui' from 'C:\\SDNext\\sdnext\\webui.py'>
22:58:04-198497 INFO     Torch: torch==2.7.1+cu118 torchvision==0.22.1+cu118
22:58:04-198497 INFO     Packages: diffusers==0.36.0.dev0 transformers==4.57.1 accelerate==1.11.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0
22:58:05-629840 DEBUG    ONNX: version=1.23.2, available=['AzureExecutionProvider', 'CPUExecutionProvider']
22:58:06-081634 DEBUG    State initialized: id=3053096469984
22:58:06-447742 INFO     Device detect: memory=6.0 default=balanced optimization=medvram
22:58:06-447742 DEBUG    Triton: pass=False fn=<module>:has_triton time=0.00
22:58:06-460713 DEBUG    Read: file="C:\SDNext\sdnext\config.json" json=14 bytes=696 time=0.001 fn=<module>:load
22:58:06-462458 INFO     Engine: backend=Backend.DIFFUSERS compute=zluda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
22:58:06-478145 DEBUG    Read: file="html\reference.json" json=136 bytes=66343 time=0.016
                         fn=_call_with_frames_removed:<module>
22:58:06-478145 DEBUG    Torch cuDNN: benchmark=True
22:58:06-478145 DEBUG    Torch attention: type="sdpa" opts=['Math attention', 'Dynamic attention']
22:58:06-478145 DEBUG    Torch attention installed: flashattn=False sageattention=False
22:58:06-478145 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False
                         xla=False xformers=False
22:58:06-777138 DEBUG    Triton: pass=False fn=<module>:set_cuda_params time=0.00
22:58:06-777138 INFO     Torch parameters: backend=zluda device=cuda config=Auto dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=fail optimization="Scaled-Dot-Product"

rocBLAS error: Could not load C:\Program Files\AMD\ROCm\6.4\bin\/rocblas/library/TensileLibrary_lazy_gfx1103.dat

rocBLAS error: Could not initialize Tensile library
```

### Backend

Diffusers

### Compute

ZLUDA

### Interface

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
cc @lshqqytiger

**Comment by lshqqytiger** [comment]
Radeon 780M (gfx1103) needs custom tensile libraries that can be downloaded from [here](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.4.2) to run rocBLAS.
However, I'd like to recommend using official ROCm PyTorch instead.
https://github.com/vladmandic/sdnext/wiki/AMD-ROCm#rocm-on-windows

**Comment by NakedSnake28** [comment]
> Radeon 780M (gfx1103) needs custom tensile libraries that can be downloaded from [here](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.4.2) to run rocBLAS. However, I'd like to recommend using official ROCm PyTorch instead. https://github.com/vladmandic/sdnext/wiki/AMD-ROCm#rocm-on-windows

I'll start with the fact that the ROCm is for my 780M (gfx1103), so I put a custom rocBLAS under the 780M and it still doesn't work.
In total, we have that neither ROCm nor ZLUDA works for me. Maybe it's windows 11 24h2.

**Comment by vladmandic** [comment]
@NakedSnake28 you said neither zluda nor rocm works for you, but we need logs for that.

**Comment by tex2100** [comment]
> > Radeon 780M (gfx1103) needs custom tensile libraries that can be downloaded from [here](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.4.2) to run rocBLAS. However, I'd like to recommend using official ROCm PyTorch instead. https://github.com/vladmandic/sdnext/wiki/AMD-ROCm#rocm-on-windows
> 
> I'll start with the fact that the ROCm is for my 780M (gfx1103), so I put a custom rocBLAS under the 780M and it still doesn't work. In total, we have that neither ROCm nor ZLUDA works for me. Maybe it's windows 11 24h2.

I have a Ryzen AI 340+ Radeon 840 M laptop, but I experienced the same circumstance. gfx1152 (Radeon 840 M) file could not load... it reports an error when launching SD.next with Zluda. The reason is not officially supported 840m with Zluda/rocm. If you need a workaround, I think that Korean guy has 780M scripts for Comfy.
https://linsoo.pe.kr/47387/

**Comment by vladmandic** [comment]
original author did not provide info for the past few months, if info is provided we can reopen the issue.
