### ISSUE TITLE
[Issue]: Triton is installed but declared missing by SD-Next

### ISSUE THREAD

**Issue by SAC020** [vladmandic/sdnext#4536]
### Issue Description

1. installed triton inside the SDNext venv
2. ran the script attached to verify the installation, it passes
3. still, SDNext declares Triton as missing

Nvidia RTX 5090

```
(venv) PS C:\ai\sdnext> python.exe .\triton_test.py
torch 2.8.0+cu128 cuda 12.8 gpu NVIDIA GeForce RTX 5090
triton 3.5.1 file C:\ai\sdnext\venv\Lib\site-packages\triton\__init__.py
OK: triton jit ran. max error: 0.0
(venv) PS C:\ai\sdnext>
```

[triton_test.py](https://github.com/user-attachments/files/24527784/triton_test.py)

```
...
15:08:16-273685 DEBUG    Initializing: settings
15:08:16-276124 DEBUG    Triton: pass=False fn=<module>:has_triton time=0.00
15:08:16-374868 INFO     Torch parameters: backend=cuda device=cuda config=BF16 dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=fail optimization="Scaled-Dot-Product"
...

```

### Version Platform Description

PS C:\ai\sdnext> .\webui.bat --debug
Using VENV: C:\ai\sdnext\venv
15:07:46-650985 INFO     Starting SD.Next
15:07:46-654089 INFO     Logger: file="C:\ai\sdnext\sdnext.log" level=DEBUG host="SEB-PC" size=74 mode=create
15:07:46-655279 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\sdnext\venv\Scripts\python.exe"
                         venv="C:\ai\sdnext\venv"
15:07:46-947594 INFO     Version: app=sd.next updated=2026-01-09 commit=47dcab352 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev kanvas=main ui=dev
15:07:47-620287 TRACE    Repository branches: active=dev available=['dev', 'master', 'upstream']
15:07:47-976404 INFO     Version: app=sd.next latest=2026-01-08T21:34:32Z hash=47dcab35 branch=dev
15:07:47-988562 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26200-SP0 python=3.11.9 locale=('English_United States', '1250')
                         docker=False
15:07:47-990567 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
15:07:47-992083 INFO     Args: ['--debug']

### Relevant log output

```shell
PS C:\ai\sdnext> .\webui.bat --debug
Using VENV: C:\ai\sdnext\venv
15:07:46-650985 INFO     Starting SD.Next
15:07:46-654089 INFO     Logger: file="C:\ai\sdnext\sdnext.log" level=DEBUG host="SEB-PC" size=74 mode=create
15:07:46-655279 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\sdnext\venv\Scripts\python.exe"
                         venv="C:\ai\sdnext\venv"
15:07:46-947594 INFO     Version: app=sd.next updated=2026-01-09 commit=47dcab352 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev kanvas=main ui=dev
15:07:47-620287 TRACE    Repository branches: active=dev available=['dev', 'master', 'upstream']
15:07:47-976404 INFO     Version: app=sd.next latest=2026-01-08T21:34:32Z hash=47dcab35 branch=dev
15:07:47-988562 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26200-SP0 python=3.11.9 locale=('English_United States', '1250')
                         docker=False
15:07:47-990567 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
15:07:47-992083 INFO     Args: ['--debug']
15:07:47-992582 DEBUG    Setting environment tuning
15:07:47-993579 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
15:07:47-995097 INFO     Verifying torch installation
15:07:47-996161 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
15:07:48-012511 INFO     CUDA: nVidia toolkit detected
15:07:49-733676 INFO     Torch backend: version="2.8.0+cu128" type=CUDA CUDA=12.8 cuDNN=91002
15:07:49-736887 INFO     Torch detected: gpu="NVIDIA GeForce RTX 5090" vram=32607 arch=(12, 0) cores=170
15:07:49-901693 WARNING  Modified files: ['scripts/detect_extension.py', 'triton_test.py']
15:07:50-016137 INFO     Install: verifying requirements
15:07:50-070970 DEBUG    Timestamp repository update time: Thu Jan  8 23:34:32 2026
15:07:50-071790 INFO     Startup: standard
15:07:50-072900 INFO     Verifying submodules
15:07:53-631765 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-chainner" reattach=main
15:07:53-632827 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
15:07:53-774191 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
15:07:53-774947 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
15:07:53-917320 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-kanvas" reattach=main
15:07:53-918324 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main
15:07:54-091501 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=dev
15:07:54-092407 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
15:07:54-310029 DEBUG    Git detached head detected: folder="extensions-builtin/stable-diffusion-webui-rembg"
                         reattach=master
15:07:54-310908 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
15:07:54-451379 DEBUG    Git detached head detected: folder="wiki" reattach=master
15:07:54-451941 DEBUG    Git submodule: wiki / master
15:07:54-660698 DEBUG    Installed packages: 262
15:07:54-662186 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sdnext-kanvas',
                         'sdnext-modernui', 'stable-diffusion-webui-rembg']
15:07:55-195365 DEBUG    Extension installer: builtin=True
                         file="C:\ai\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py"
15:07:55-302068 DEBUG    Extensions all: ['canvas-zoom', 'sd-webui-openpose-editor']
15:07:55-303676 DEBUG    Extension installer: builtin=False file="C:\ai\sdnext\extensions\canvas-zoom\install.py"
15:08:01-223989 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sdnext-kanvas', 'sdnext-modernui', 'stable-diffusion-webui-rembg', 'canvas-zoom',
                         'sd-webui-openpose-editor']
15:08:01-338513 INFO     Install: verifying requirements
15:08:01-342313 DEBUG    Setup complete without errors: 1767964081
15:08:01-348064 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
15:08:01-348759 INFO     Installer time: total=21.12 canvas-zoom=5.81 git=4.72 submodules=4.48 torch=1.74 latest=1.32
                         branch=1.01 base=0.35 version=0.29 requirements=0.24 installed=0.24 files=0.16 Lora=0.11
                         sd-webui-openpose-editor=0.11 sd-extension-chainner=0.11 stable-diffusion-webui-rembg=0.11
                         sdnext-modernui=0.10 sd-extension-system-info=0.10 sdnext-kanvas=0.10
15:08:01-350660 INFO     Command line args: ['--debug'] args=[]
15:08:01-352039 DEBUG    Env flags: []
15:08:01-352819 DEBUG    Starting module: <module 'webui' from 'C:\\ai\\sdnext\\webui.py'>
15:08:01-354606 DEBUG    Initializing: libraries
15:08:14-861806 INFO     Torch: torch==2.8.0+cu128 torchvision==0.23.0+cu128
15:08:14-864349 INFO     Packages: diffusers==0.37.0.dev0 transformers==4.57.3 accelerate==1.12.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0
15:08:14-891100 DEBUG    Initializing: shared module
15:08:15-023419 DEBUG    Initializing: pipelines
15:08:16-171869 DEBUG    ONNX: version=1.23.2, available=['AzureExecutionProvider', 'CPUExecutionProvider']
15:08:16-191744 DEBUG    State initialized: id=1294064141072
15:08:16-268248 DEBUG    Initializing: default modes
15:08:16-269777 INFO     Device detect: memory=32.0 default=balanced optimization=highvram
15:08:16-273685 DEBUG    Initializing: settings
15:08:16-276124 DEBUG    Triton: pass=False fn=<module>:has_triton time=0.00
15:08:16-280577 DEBUG    Read: file="C:\ai\sdnext\config.json" json=39 bytes=1684 time=0.001 fn=<module>:load
15:08:16-282499 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
15:08:16-285705 DEBUG    Read: file="html\reference.json" json=152 bytes=72781 time=0.000
                         fn=_call_with_frames_removed:<module>
15:08:16-286492 DEBUG    Initializing: devices
15:08:16-287048 DEBUG    Torch cuDNN: benchmark=True
15:08:16-287831 DEBUG    Torch attention: type="sdpa" kernels=['Flash', 'Memory', 'Math'] overrides=[]
15:08:16-290157 DEBUG    Torch attention installed: flashattn=False sageattention=False
15:08:16-291194 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False
                         xla=False xformers=False
15:08:16-373202 DEBUG    Triton: pass=False fn=<module>:set_cuda_params time=0.00
15:08:16-374868 INFO     Torch parameters: backend=cuda device=cuda config=BF16 dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=fail optimization="Scaled-Dot-Product"
15:08:16-390086 DEBUG    Quantization: registered=SDNQ
15:08:16-463100 INFO     Device: device=NVIDIA GeForce RTX 5090 n=1 arch=sm_120 capability=(12, 0) cuda=12.8 cudnn=91002
                         driver=591.59
15:08:16-682960 DEBUG    Entering start sequence
15:08:16-685768 DEBUG    Initializing: modules
15:08:16-692797 DEBUG    Read: file="metadata.json" json=1342 bytes=1428112 time=0.005 fn=initialize:init_metadata
15:08:16-694156 DEBUG    Read: file="cache.json" json=2 bytes=6944 time=0.000 fn=initialize:init_cache
15:08:16-752723 INFO     Available VAEs: path="models\VAE" items=0
15:08:16-754143 INFO     Available UNets: path="models\UNET" items=1
15:08:16-754834 INFO     Available TEs: path="models\Text-encoder" items=4
15:08:16-769897 INFO     Available Models: safetensors="models\Stable-diffusion":22 diffusers="models\Diffusers":10
                         reference=152 items=32 time=0.01
15:08:16-804555 INFO     Available LoRAs: path="models\Lora" items=349 folders=3 time=0.02
15:08:16-823297 INFO     Available Styles: path="models\styles" items=288 time=0.02
15:08:16-915377 INFO     Available Detailer: path="models\yolo" items=15 downloaded=4
15:08:16-917524 DEBUG    Extensions: disabled=['Lora', 'sdnext-modernui']
15:08:16-918227 INFO     Load extensions
15:08:17-256871 DEBUG    Extensions init time: total=0.34 stable-diffusion-webui-rembg=0.12
15:08:17-496190 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.001 fn=__init__:__init__
15:08:17-498102 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
15:08:17-501806 DEBUG    Available chaiNNer: path="models\chaiNNer" defined=25 discovered=0 downloaded=10
15:08:17-508251 INFO     Available Upscalers: items=79 downloaded=24 user=3 time=0.25 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN',
                         'SCUNet', 'Diffusion', 'SeedVR', 'SwinIR']
15:08:17-578348 INFO     Networks: type="video" engines=13 models=67 errors=0 time=0.06
15:08:17-582003 INFO     Huggingface: transfer=rust parallel=True direct=False token="hf_...UtOy"
                         cache="D:\huggingface\hub" init
15:08:17-848633 DEBUG    Huggingface: cache="D:\huggingface\hub" size=571248 MB
15:08:17-849542 DEBUG    UI start sequence
15:08:17-850081 DEBUG    UI image support: kanvas=main
15:08:17-860643 INFO     UI locale: name="Auto"
15:08:17-861776 INFO     UI theme: type=Standard name="black-teal" available=14
15:08:17-864309 DEBUG    UI theme: css="C:\ai\sdnext\javascript\black-teal.css" base="['sdnext.css', 'timesheet.css']"
                         user="None"
15:08:17-867471 DEBUG    UI initialize: tab=txt2img
15:08:18-009592 DEBUG    Read: file="html\reference.json" json=152 bytes=72781 time=0.003 fn=list_items:list_reference
15:08:18-051995 DEBUG    Networks: type="reference" items={'total': 152, 'ready': 1, 'hidden': 0, 'experimental': 0,
                         'base': 95, 'distilled': 18, 'quantized': 20, 'community': 15, 'cloud': 2}
15:08:18-077200 DEBUG    Networks: type="model" items=182 subfolders=8 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Reference', 'C:\\ai\\sdnext\\models\\Stable-diffusion'] list=0.19 thumb=0.02 desc=0.02
                         info=0.12 workers=12
15:08:18-088002 DEBUG    Networks: type="lora" items=349 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.19
                         thumb=0.05 desc=0.17 info=0.48 workers=12
15:08:18-097957 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.14 thumb=0.01 desc=0.00 info=0.00 workers=12
15:08:18-101348 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models\\wildcards']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
15:08:18-104199 DEBUG    Networks: type="embedding" items=13 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.09 thumb=0.06 desc=0.00 info=0.00 workers=12
15:08:18-105962 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
15:08:18-108076 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
15:08:18-333386 DEBUG    UI initialize: tab=img2img
15:08:18-594131 DEBUG    UI initialize: tab=control models="models\control"
15:08:19-156842 DEBUG    UI initialize: tab=video
15:08:19-311539 DEBUG    UI initialize: tab=process
15:08:19-374813 DEBUG    UI initialize: tab=caption
15:08:19-507449 DEBUG    UI initialize: tab=models
15:08:19-593961 DEBUG    UI initialize: tab=gallery
15:08:19-674606 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.001 fn=__init__:read_from_file
15:08:19-675155 DEBUG    UI initialize: tab=settings
15:08:20-087858 DEBUG    Settings: sections=24 settings=411/635 quicksettings=3
15:08:20-193334 DEBUG    UI initialize: tab=info
15:08:20-233826 DEBUG    UI initialize: tab=extensions
15:08:21-034075 DEBUG    Extension list: processed=412 installed=6 enabled=5 disabled=1 visible=412 hidden=0
15:08:21-452091 DEBUG    Root paths: ['C:\\ai\\sdnext', 'models']
15:08:21-575939 INFO     Local URL: http://127.0.0.1:7860/
15:08:21-577453 INFO     API docs: http://127.0.0.1:7860/docs
15:08:21-578459 INFO     API redocs: http://127.0.0.1:7860/redocs
15:08:21-580659 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
15:08:21-581426 DEBUG    API initialize
15:08:21-824658 DEBUG    Scripts setup: time=0.511 ['IP Adapters:0.202', 'XYZ Grid:0.05']
15:08:21-826097 DEBUG    Model metadata: file="metadata.json" no changes
15:08:21-826608 INFO     Model: autoload=True selected="Diffusers\Qwen/Qwen-Image-2512 [25468b98e3]"
15:08:21-829004 DEBUG    Model requested: fn=threading.py:run:<lambda>
15:08:21-829996 DEBUG    Search model: name="Diffusers\Qwen/Qwen-Image-2512 [25468b98e3]"
                         matched="models\Diffusers\models--Qwen--Qwen-Image-2512\snapshots\25468b98e3276ca6700de15c6628e
                         51b7de54a26" type=alias
15:08:21-830989 INFO     Load model: select="Diffusers\Qwen/Qwen-Image-2512 [25468b98e3]"
15:08:21-835533 INFO     Autodetect model: detect="Qwen" class=QwenImagePipeline
                         file="models\Diffusers\models--Qwen--Qwen-Image-2512\snapshots\25468b98e3276ca6700de15c6628e51b
                         7de54a26"
15:08:21-836330 DEBUG    Cache clear
15:08:21-840949 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 matmul_dtype=auto matmul=False
                         group_size=0 svd_rank=32 svd_steps=8 use_svd=True quant_conv=False matmul_conv=False
                         dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cuda
                         device_map=gpu offload_mode=balanced non_blocking=False modules_to_not_convert=[]
                         modules_dtype_dict={}
15:08:21-842467 DEBUG    Load model: type=Qwen model="Diffusers\Qwen/Qwen-Image-2512" repo="Qwen/Qwen-Image-2512"
                         offload=balanced dtype=torch.bfloat16 args={'torch_dtype': torch.bfloat16}
15:08:21-844306 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=int8 matmul_dtype=auto matmul=False
                         group_size=0 svd_rank=32 svd_steps=8 use_svd=True quant_conv=False matmul_conv=False
                         dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cuda
                         device_map=gpu offload_mode=balanced non_blocking=False
                         modules_to_not_convert=['transformer_blocks.0.img_mod.1.weight'] modules_dtype_dict={}
15:08:21-846915 DEBUG    Load model: transformer="Qwen/Qwen-Image-2512" cls=QwenImageTransformer2DModel
                         subfolder=transformer quant="SDNQConfig" loader=default args={'torch_dtype': torch.bfloat16,
                         'device_map': device(type='cuda')}
Progress ?it/s ███████████████████████████████ 100% 9/9 00:00 ? Fetching 9 files
Progress  7.66s/it █████████▎      67% 6/9 00:45 00:22 Loading checkpoint shards15:09:11-978256 DEBUG    UI: connected  
15:09:11-979254 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0025
Progress  8.19s/it ██████████████ 100% 9/9 01:13 00:00 Loading checkpoint shards
15:09:41-289490 DEBUG    GC: current={'gpu': 1.83, 'ram': 32.18, 'oom': 0} prev={'gpu': 21.64, 'ram': 32.82}
                         load={'gpu': 6, 'ram': 50} gc={'gpu': 19.81, 'py': 6712}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.41
15:09:41-305622 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=int8 matmul_dtype=auto matmul=False
                         group_size=0 svd_rank=32 svd_steps=8 use_svd=True quant_conv=False matmul_conv=False
                         dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cuda
                         device_map=gpu offload_mode=balanced non_blocking=False modules_to_not_convert=[]
                         modules_dtype_dict={}
15:09:41-306740 DEBUG    Load model: text_encoder="hunyuanvideo-community/HunyuanImage-2.1-Diffusers"
                         cls=Qwen2_5_VLForConditionalGeneration quant="SDNQConfig" loader=default shared=True
Progress  6.12s/it ██████████████ 100% 4/4 00:24 00:00 Loading checkpoint shards
15:10:09-336060 DEBUG    GC: current={'gpu': 2.24, 'ram': 40.3, 'oom': 0} prev={'gpu': 18.82, 'ram': 40.32} load={'gpu':
                         7, 'ram': 63} gc={'gpu': 16.58, 'py': 127}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.32
Progress 23.49it/s █████████ 100% 5/5 00:00 00:00 Loading pipeline components...
15:10:09-922449 DEBUG    Setting model: component=vae {'slicing': False, 'tiling': False}
15:10:09-925302 DEBUG    Setting model: attention="Scaled-Dot-Product"
15:10:09-926219 INFO     Offload: type=balanced op=init watermark=0.2-0.9 gpu=6.40-28.80:32.00 cpu=64.000 limit=0.00
                         always=['T5EncoderModel', 'UMT5EncoderModel'] never=['CLIPTextModel',
                         'CLIPTextModelWithProjection', 'AutoencoderKL'] pre=True streams=False
15:10:09-961432 DEBUG    Module: name=transformer cls=QwenImageTransformer2DModel size=19.685 params=20731979328
                         quant=QuantizationMethod.SDNQ
15:10:09-969196 DEBUG    Module: name=text_encoder cls=Qwen2_5_VLForConditionalGeneration size=8.938 params=8398341376
                         quant=QuantizationMethod.SDNQ
15:10:09-972775 DEBUG    Module: name=vae cls=AutoencoderKLQwenImage size=0.236 params=126892531 quant=None
15:10:09-973488 INFO     Model class=QwenImagePipeline modules=3 size=28.859
15:10:09-977715 INFO     Load model: family=qwen time={'total': 108.15, 'load': 108.09} native=0 memory={'ram':
                         {'total': 63.92, 'rss': 30.24, 'used': 40.29, 'free': 23.63, 'avail': 23.63, 'buffers': 0,
                         'cached': 0}, 'gpu': {'used': 2.24, 'total': 31.84, 'active': 0.04, 'peak': 20.34, 'retries':
                         0, 'oom': 0, 'swap': 0}, 'job': ''}
15:10:09-983708 DEBUG    Script init: ['system-info.py:app_started=0.10']
15:10:09-984719 INFO     Startup time: total=174.12 checkpoint=108.16 launch=15.57 loader=15.17 installer=15.17
                         torch=7.82 gradio=3.94 libraries=2.87 ui-extensions=1.34 ui-networks=0.53 diffusers=0.52
                         ui-control=0.43 extensions=0.34 cleanup=0.27 upscalers=0.25 ui-img2img=0.19 ui-txt2img=0.18
                         ui-models=0.16 api=0.14 ui-defaults=0.14 app-started=0.10
```

### Backend

Diffusers

### Compute

nVidia CUDA

### Interface

Standard

### Branch

Dev

### Model

Other image model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
your test script looks nice, but its different than sdnext's which primarily checks if triton compile works which does require full build environment to be available as that is typical execution case for triton:

```py
        from torch.utils._triton import has_triton as torch_has_triton
        if torch_has_triton():
            if early:
                return True
            def test_triton_func(a,b,c):
                return a * b + c
            test_triton_func = torch.compile(test_triton_func, fullgraph=True)
            test_triton_func(torch.randn(16, device=device), torch.randn(16, device=device), torch.randn(16, device=device))
            triton_ok = True
        else:
            triton_ok = False
```

cc @Disty0

**Comment by SAC020** [comment]
well, it's a chatgpt script, not mine :) but anyway, how should i install triton (on windows) so it actually works for sdnext?

**Comment by vladmandic** [comment]
on linux, nothing really other than triton itself as 99% linux distros have build tools
on windows, probably need to install visual studio

**Comment by SAC020** [comment]
Fixed it with GPT based on your test code.

```
# 1) remove both, to avoid leftover metadata/conflicts
pip uninstall -y triton triton-windows

# 2) install a known-good line for torch 2.8 integration
pip install -U "triton-windows<3.5"
```

Verify:

```
python -c "import triton; print('triton', triton.__version__)"
python -c "from triton.compiler.compiler import triton_key; print('OK: triton_key present')"
python -c "from torch.utils._triton import has_triton; print('torch_has_triton', has_triton())"
```

SD-Next webui debug

```
15:39:19-945274 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=4.51
15:39:19-947753 INFO     Torch parameters: backend=cuda device=cuda config=BF16 dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=pass optimization="Scaled-Dot-Product"
```


GPT dixit:

```
Fix was pinning triton-windows<3.5 (3.4.0.post21) because 3.5.1 lacks triton_key needed by torch 2.8 Inductor; after downgrade torch.utils._triton.has_triton() becomes True and SDNQ matmul enables.

Triton 3.5.x on Windows is incompatible with PyTorch 2.8 Inductor because it removed triton_key, which PyTorch still imports.

triton-windows 3.4.0.post21 still exposes that API → torch_has_triton() returns True.

SD.Next’s check is correct for its execution path — it requires PyTorch-level Triton, not just raw Triton JIT.
```

**Comment by vladmandic** [comment]
that is actually really on-point and helpfull from gpt

**Comment by SAC020** [comment]
Re-opening this because I don't understand it anymore. Although triton is detected, it still disables MatMul. Why? And how do I fix it?


```
13:57:55-041862 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=4.16
13:57:55-042986 INFO     Torch parameters: backend=cuda device=cuda config=BF16 dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=pass optimization="Scaled-Dot-Product"

...

13:58:00-784404 WARNING  SDNQ Quantized MatMul requires a working Triton install. Disabling Quantized MatMul.
13:58:00-785331 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=uint4 matmul_dtype=auto matmul=False
                         group_size=0 svd_rank=32 svd_steps=8 use_svd=True quant_conv=False matmul_conv=False
                         dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cuda
                         device_map=gpu offload_mode=balanced non_blocking=False modules_to_not_convert=[]
                         modules_dtype_dict={}

```


```
PS C:\ai\sdnext> .\webui.bat --debug
Using VENV: C:\ai\sdnext\venv
13:57:19-167095 INFO     Starting SD.Next
13:57:19-169321 INFO     Logger: file="C:\ai\sdnext\sdnext.log" level=DEBUG host="SEB-PC" size=74 mode=create
13:57:19-170534 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\sdnext\venv\Scripts\python.exe"
                         venv="C:\ai\sdnext\venv"
13:57:19-487470 INFO     Version: app=sd.next updated=2026-01-10 commit=3dac59fd4 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev kanvas=main ui=dev
13:57:20-152817 TRACE    Repository branches: active=dev available=['dev', 'master', 'upstream']
13:57:20-442441 INFO     Version: app=sd.next latest=2026-01-10T11:56:42Z hash=a6a5b9ff branch=dev
13:57:20-455142 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26200-SP0 python=3.11.9 locale=('English_United States', '1250')
                         docker=False
13:57:20-456898 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
13:57:20-458959 INFO     Args: ['--debug']
13:57:20-459824 DEBUG    Setting environment tuning
13:57:20-460524 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
13:57:20-462517 INFO     Verifying torch installation
13:57:20-463013 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
13:57:20-482133 INFO     CUDA: nVidia toolkit detected
13:57:22-759804 INFO     Torch backend: version="2.8.0+cu128" type=CUDA CUDA=12.8 cuDNN=91002
13:57:22-762981 INFO     Torch detected: gpu="NVIDIA GeForce RTX 5090" vram=32607 arch=(12, 0) cores=170
13:57:22-969904 WARNING  Modified files: ['scripts/detect_extension.py', 'triton_test.py']
13:57:23-083342 INFO     Install: verifying requirements
13:57:23-134814 DEBUG    Timestamp repository update time: Sat Jan 10 09:19:54 2026
13:57:23-136342 INFO     Startup: standard
13:57:23-137119 INFO     Verifying submodules
13:57:26-541495 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-chainner" reattach=main
13:57:26-541999 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
13:57:26-681173 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
13:57:26-681848 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
13:57:26-818360 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-kanvas" reattach=main
13:57:26-819017 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main
13:57:26-992277 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=dev
13:57:26-993269 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
13:57:27-227539 DEBUG    Git detached head detected: folder="extensions-builtin/stable-diffusion-webui-rembg"
                         reattach=master
13:57:27-228044 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
13:57:27-360035 DEBUG    Git detached head detected: folder="wiki" reattach=master
13:57:27-361001 DEBUG    Git submodule: wiki / master
13:57:27-581117 DEBUG    Installed packages: 261
13:57:27-582558 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sdnext-kanvas',
                         'sdnext-modernui', 'stable-diffusion-webui-rembg']
13:57:28-150954 DEBUG    Extension installer: builtin=True
                         file="C:\ai\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py"
13:57:28-263413 DEBUG    Extensions all: ['canvas-zoom', 'sd-webui-openpose-editor']
13:57:28-264839 DEBUG    Extension installer: builtin=False file="C:\ai\sdnext\extensions\canvas-zoom\install.py"
13:57:34-438807 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sdnext-kanvas', 'sdnext-modernui', 'stable-diffusion-webui-rembg', 'canvas-zoom',
                         'sd-webui-openpose-editor']
13:57:34-551432 INFO     Install: verifying requirements
13:57:34-555208 DEBUG    Setup complete without errors: 1768046255
13:57:34-562538 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
13:57:34-563582 INFO     Installer time: total=21.87 canvas-zoom=6.06 git=4.62 submodules=4.34 torch=2.30 latest=1.27
                         branch=1.02 base=0.46 version=0.31 requirements=0.23 installed=0.23 files=0.21
                         sd-extension-system-info=0.12 sd-extension-chainner=0.11 stable-diffusion-webui-rembg=0.11
                         sdnext-modernui=0.11 sd-webui-openpose-editor=0.11 sdnext-kanvas=0.11 Lora=0.11
13:57:34-565114 INFO     Command line args: ['--debug'] args=[]
13:57:34-566313 DEBUG    Env flags: []
13:57:34-567382 DEBUG    Starting module: <module 'webui' from 'C:\\ai\\sdnext\\webui.py'>
13:57:34-569877 DEBUG    Initializing: libraries
13:57:49-102794 INFO     Torch: torch==2.8.0+cu128 torchvision==0.23.0+cu128
13:57:49-105667 INFO     Packages: diffusers==0.37.0.dev0 transformers==4.57.3 accelerate==1.12.0 gradio==3.43.2
                         pydantic==1.10.21 numpy==2.1.2 cv2==4.12.0
13:57:49-133745 DEBUG    Initializing: shared module
13:57:49-280353 DEBUG    Initializing: pipelines
13:57:50-683834 DEBUG    ONNX: version=1.23.2, available=['AzureExecutionProvider', 'CPUExecutionProvider']
13:57:50-710291 DEBUG    State initialized: id=2103177691920
13:57:50-799204 DEBUG    Initializing: default modes
13:57:50-800214 INFO     Device detect: memory=32.0 default=balanced optimization=highvram
13:57:50-802731 DEBUG    Initializing: settings
13:57:50-810349 DEBUG    Read: file="C:\ai\sdnext\config.json" json=42 bytes=1785 time=0.000 fn=<module>:load
13:57:50-812583 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
13:57:50-817776 DEBUG    Read: file="html\reference.json" json=152 bytes=72781 time=0.001
                         fn=_call_with_frames_removed:<module>
13:57:50-818780 DEBUG    Initializing: devices
13:57:50-819842 DEBUG    Torch cuDNN: benchmark=True
13:57:50-820349 DEBUG    Torch attention: type="sdpa" kernels=['Flash', 'Memory', 'Math'] overrides=[]
13:57:50-822357 DEBUG    Torch attention installed: flashattn=False sageattention=False
13:57:50-822859 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False
                         xla=False xformers=False
13:57:55-041862 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=4.16
13:57:55-042986 INFO     Torch parameters: backend=cuda device=cuda config=BF16 dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, True] fp16=pass
                         bf16=pass triton=pass optimization="Scaled-Dot-Product"
13:57:55-061873 DEBUG    Quantization: registered=SDNQ
13:57:55-123609 INFO     Device: device=NVIDIA GeForce RTX 5090 n=1 arch=sm_120 capability=(12, 0) cuda=12.8 cudnn=91002
                         driver=591.59
13:57:55-369823 DEBUG    Entering start sequence
13:57:55-374759 DEBUG    Initializing: modules
13:57:55-381957 DEBUG    Read: file="metadata.json" json=1342 bytes=1428112 time=0.006 fn=initialize:init_metadata
13:57:55-384480 DEBUG    Read: file="cache.json" json=2 bytes=6944 time=0.001 fn=initialize:init_cache
13:57:55-454012 INFO     Available VAEs: path="models\VAE" items=0
13:57:55-455619 INFO     Available UNets: path="models\UNET" items=1
13:57:55-456727 INFO     Available TEs: path="models\Text-encoder" items=4
13:57:55-482789 INFO     Available Models: safetensors="models\Stable-diffusion":22 diffusers="models\Diffusers":11
                         reference=152 items=33 time=0.02
13:57:55-532716 INFO     Available LoRAs: path="models\Lora" items=349 folders=3 time=0.04
13:57:55-551499 INFO     Available Styles: path="models\styles" items=288 time=0.02
13:57:55-665983 INFO     Available Detailer: path="models\yolo" items=15 downloaded=4
13:57:55-668098 DEBUG    Extensions: disabled=['Lora', 'sdnext-modernui']
13:57:55-668597 INFO     Load extensions
13:57:56-052731 DEBUG    Extensions init time: total=0.38 stable-diffusion-webui-rembg=0.13
13:57:56-314694 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.001 fn=__init__:__init__
13:57:56-316117 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=25 bytes=2830 time=0.000
                         fn=__init__:find_scalers
13:57:56-319952 DEBUG    Available chaiNNer: path="models\chaiNNer" defined=25 discovered=0 downloaded=10
13:57:56-327490 INFO     Available Upscalers: items=79 downloaded=24 user=3 time=0.27 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'WanUpscale', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN',
                         'SCUNet', 'Diffusion', 'SeedVR', 'SwinIR']
13:57:56-409069 INFO     Networks: type="video" engines=13 models=67 errors=0 time=0.07
13:57:56-413021 INFO     Huggingface: transfer=rust parallel=True direct=False token="hf_...UtOy"
                         cache="D:\huggingface\hub" init
13:57:56-674702 DEBUG    Huggingface: cache="D:\huggingface\hub" size=632714 MB
13:57:56-675542 DEBUG    UI start sequence
13:57:56-676594 DEBUG    UI image support: kanvas=main
13:57:56-688131 INFO     UI locale: name="Auto"
13:57:56-689188 INFO     UI theme: type=Standard name="black-teal" available=14
13:57:56-690823 DEBUG    UI theme: css="C:\ai\sdnext\javascript\black-teal.css" base="['sdnext.css', 'timesheet.css']"
                         user="None"
13:57:56-694072 DEBUG    UI initialize: tab=txt2img
13:57:56-862469 DEBUG    Read: file="html\reference.json" json=152 bytes=72781 time=0.002 fn=list_items:list_reference
13:57:56-902736 DEBUG    Networks: type="reference" items={'total': 152, 'ready': 1, 'hidden': 0, 'experimental': 0,
                         'base': 95, 'distilled': 18, 'quantized': 20, 'community': 15, 'cloud': 2}
13:57:56-926820 DEBUG    Networks: type="model" items=183 subfolders=8 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Reference', 'C:\\ai\\sdnext\\models\\Stable-diffusion'] list=0.21 thumb=0.02 desc=0.03
                         info=0.19 workers=12
13:57:56-937780 DEBUG    Networks: type="lora" items=349 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.21
                         thumb=0.05 desc=0.19 info=0.49 workers=12
13:57:56-948671 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.15 thumb=0.01 desc=0.00 info=0.00 workers=12
13:57:56-951842 DEBUG    Networks: type="wildcards" items=0 subfolders=1 tab=txt2img folders=['models\\wildcards']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=12
13:57:56-954058 DEBUG    Networks: type="embedding" items=13 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.11 thumb=0.07 desc=0.01 info=0.01 workers=12
13:57:56-956911 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=12
13:57:56-958738 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=12
13:57:57-185860 DEBUG    UI initialize: tab=img2img
13:57:57-621917 DEBUG    UI initialize: tab=control models="models\control"
13:57:58-027084 DEBUG    UI initialize: tab=video
13:57:58-185872 DEBUG    UI initialize: tab=process
13:57:58-247781 DEBUG    UI initialize: tab=caption
13:57:58-377436 DEBUG    UI initialize: tab=models
13:57:58-465003 DEBUG    UI initialize: tab=gallery
13:57:58-546439 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.001 fn=__init__:read_from_file
13:57:58-547465 DEBUG    UI initialize: tab=settings
13:57:58-968134 DEBUG    Settings: sections=24 settings=411/635 quicksettings=3
13:57:59-069458 DEBUG    UI initialize: tab=info
13:57:59-109727 DEBUG    UI initialize: tab=extensions
13:57:59-919435 DEBUG    Extension list: processed=412 installed=6 enabled=5 disabled=1 visible=412 hidden=0
13:58:00-154922 DEBUG    Root paths: ['C:\\ai\\sdnext', 'models']
13:58:00-501864 INFO     Local URL: http://127.0.0.1:7860/
13:58:00-502696 INFO     API docs: http://127.0.0.1:7860/docs
13:58:00-503228 INFO     API redocs: http://127.0.0.1:7860/redocs
13:58:00-505270 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
13:58:00-506267 DEBUG    API initialize
13:58:00-751316 DEBUG    Scripts setup: time=0.332 ['XYZ Grid:0.045', 'IP Adapters:0.036']
13:58:00-752504 DEBUG    Model metadata: file="metadata.json" no changes
13:58:00-753028 INFO     Model: autoload=True selected="black-forest-labs/FLUX.2-dev"
13:58:00-755322 DEBUG    Model requested: fn=threading.py:run:<lambda>
13:58:00-756475 DEBUG    Search model: name="black-forest-labs/FLUX.2-dev"
                         matched="models\Diffusers\models--black-forest-labs--FLUX.2-dev\snapshots\6aab690f8379b70adc89e
                         dfa6bb99b3537ba52a3" type=reference
13:58:00-757737 INFO     Load model: select="Diffusers\black-forest-labs/FLUX.2-dev [6aab690f83]"
13:58:00-777918 INFO     Autodetect model: detect="FLUX2" class=None
                         file="models\Diffusers\models--black-forest-labs--FLUX.2-dev\snapshots\6aab690f8379b70adc89edfa
                         6bb99b3537ba52a3"
13:58:00-778958 DEBUG    Cache clear
13:58:00-782476 DEBUG    Load model: type=Flux2 repo="black-forest-labs/FLUX.2-dev" config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'safety_checker': None,
                         'requires_safety_checker': False} offload=balanced dtype=torch.bfloat16 args={'torch_dtype':
                         torch.bfloat16}
13:58:00-784404 WARNING  SDNQ Quantized MatMul requires a working Triton install. Disabling Quantized MatMul.
13:58:00-785331 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=uint4 matmul_dtype=auto matmul=False
                         group_size=0 svd_rank=32 svd_steps=8 use_svd=True quant_conv=False matmul_conv=False
                         dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cuda
                         device_map=gpu offload_mode=balanced non_blocking=False modules_to_not_convert=[]
                         modules_dtype_dict={}
13:58:00-786436 DEBUG    Load model: transformer="black-forest-labs/FLUX.2-dev" cls=Flux2Transformer2DModel
                         subfolder=transformer quant="SDNQConfig" loader=default args={'torch_dtype': torch.bfloat16,
                         'device_map': device(type='cuda')}
Progress ?it/s ███████████████████████████████ 100% 7/7 00:00 ? Fetching 7 files
Progress 22.07s/it ██████████████ 100% 7/7 02:34 00:00 Loading checkpoint shards
14:00:41-779044 DEBUG    GC: current={'gpu': 1.83, 'ram': 36.11, 'oom': 0} prev={'gpu': 19.55, 'ram': 40.9} load={'gpu':
                         6, 'ram': 56} gc={'gpu': 17.72, 'py': 3388}
                         fn=postprocess_model:_process_model_after_weight_loading why=sdnq time=0.84
14:00:41-785891 DEBUG    Quantization: module="TE" type=sdnq mode=pre dtype=uint4 matmul_dtype=auto matmul=False
                         group_size=0 svd_rank=32 svd_steps=8 use_svd=True quant_conv=False matmul_conv=False
                         dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cuda
                         device_map=gpu offload_mode=balanced non_blocking=False modules_to_not_convert=[]
                         modules_dtype_dict={}
14:00:41-787525 DEBUG    Load model: text_encoder="black-forest-labs/FLUX.2-dev" cls=Mistral3ForConditionalGeneration
                         quant="SDNQConfig" loader=default shared=True
```

**Comment by vladmandic** [comment]
cc @Disty0

**Comment by Disty0** [comment]
Is dequantize compile option in sdnq settings disabled? Disabling that will force disable triton for sdnq.

**Comment by SAC020** [comment]
> Is dequantize compile option in sdnq settings disabled? Disabling that will force disable triton for sdnq.

Not sure. These are the settings in the UI. You mean I need to activate "dequantize using torch.compile"?


<img width="926" height="1609" alt="Image" src="https://github.com/user-attachments/assets/c3b1347c-6901-4a7d-94d7-480c1382adc3" />

**Comment by Disty0** [comment]
This setting:

<img width="419" height="69" alt="Image" src="https://github.com/user-attachments/assets/0fdae5ae-1b5c-4981-8323-f3cf1ddddc9a" />

You have it disabled right now.

**Comment by SAC020** [comment]
> This setting:
> 
> <img alt="Image" width="419" height="69" src="https://private-user-images.githubusercontent.com/47277141/534223122-0fdae5ae-1b5c-4981-8323-f3cf1ddddc9a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgwNTI3MTksIm5iZiI6MTc2ODA1MjQxOSwicGF0aCI6Ii80NzI3NzE0MS81MzQyMjMxMjItMGZkYWU1YWUtMWI1Yy00OTgxLTgzMjMtZjNjZjFkZGRkYzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTEwVDEzNDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOGUzZWU3MTZlZjg4MTkxYTA2MWI4NTI4ZjU2OTg0YTFlNjIyNTIwZjY4NTdkYmJkZjhkNGQ3MTc5OTljZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BCiaYUDujPHPBJHQQACiDiNjIWd0wVKV-QIPbAMHcnM">
> You have it disabled right now.


Ok, thank you. I enabled it and seems to be working now. But, honestly, these settings and the way they correlate (or not) are really cryptic.


```
15:38:09-764306 DEBUG    Load model: type=Flux2 repo="black-forest-labs/FLUX.2-dev" config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'safety_checker': None,
                         'requires_safety_checker': False} offload=balanced dtype=torch.bfloat16 args={'torch_dtype':
                         torch.bfloat16}
15:38:09-766482 DEBUG    Quantization: module="Model" type=sdnq mode=pre dtype=uint5 matmul_dtype=auto matmul=True
                         group_size=0 svd_rank=32 svd_steps=8 use_svd=True quant_conv=False matmul_conv=False
                         dequantize_fp32=False quantize_with_gpu=True quantization_device=cuda return_device=cuda
                         device_map=gpu offload_mode=balanced non_blocking=False modules_to_not_convert=[]
                         modules_dtype_dict={}
15:38:09-767895 DEBUG    Load model: transformer="black-forest-labs/FLUX.2-dev" cls=Flux2Transformer2DModel
                         subfolder=transformer quant="SDNQConfig" loader=default args={'torch_dtype': torch.bfloat16,
                         'device_map': device(type='cuda')}
```
