### ISSUE TITLE
[Issue]: SDXL render: detailer broken (weird washed lines)

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/sdnext#4643]
### Issue Description

Detailer just broke, it did work yesterday.

Reproduce:
- simple render 1024x1024, perfectdeliberate_v70.safetensors, 16 steps, DPM++ 2M
- no loras, no upscale, no HighDiffusion,

<img width="894" height="1235" alt="Image" src="https://github.com/user-attachments/assets/2894c6ac-5ef8-4dee-8373-70c016ebe5cd" />

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/ea7b2c97-af23-403a-9f3b-aa4ee79865d1" />

<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/57148b14-3178-467b-bfe2-dc05c7f6923b" />

### Version Platform Description

Win11, WSL2/Ubuntu, 3ee816888

### Relevant log output

```shell
Activate python venv: /home/tillerz/dev/venv
Launch: venv/bin/python3
09:29:58-450912 INFO     Starting SD.Next
09:29:58-453527 INFO     Logger: file="/home/tillerz/dev/sdnext.log" level=DEBUG host="sarah" size=72 mode=create
09:29:58-454157 INFO     Python: version=3.12.3 platform=Linux bin="/home/tillerz/dev/venv/bin/python3" venv="/home/tillerz/dev/venv"
09:29:58-535443 INFO     Version: app=sd.next updated=2026-02-11 commit=3ee816888 branch=dev
                         url=https://github.com/vladmandic/sdnext/tree/dev kanvas=main ui=dev
09:29:59-076764 TRACE    Repository branches: active=dev available=['dev', 'master', 'upstream']
09:29:59-462139 INFO     Version: app=sd.next latest=2026-02-12T07:40:10Z hash=88db926e branch=dev
09:29:59-472449 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.6.87.2-microsoft-standard-WSL2 python=3.12.3 locale=('C',
                         'UTF-8') docker=False
09:29:59-473395 DEBUG    Packages: prefix=venv site=['venv/lib/python3.12/site-packages']
09:29:59-474160 INFO     Args: []
09:29:59-474570 DEBUG    Setting environment tuning
09:29:59-475016 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
09:29:59-475834 INFO     Verifying torch installation
09:29:59-476217 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
09:29:59-590595 INFO     CUDA: nVidia toolkit detected
09:30:01-096020 INFO     Torch backend: version="2.8.0+cu128" type=CUDA CUDA=12.8 cuDNN=91002
09:30:01-135821 INFO     Torch detected: gpu="NVIDIA GeForce RTX 4090" vram=24564 arch=(8, 9) cores=128
09:30:01-295071 INFO     Install: verifying requirements
09:30:01-308730 DEBUG    Timestamp repository update time: Wed Feb 11 18:37:35 2026
09:30:01-309401 INFO     Startup: standard
09:30:01-309838 INFO     Verifying submodules
09:30:01-835882 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
09:30:01-859836 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
09:30:01-882736 DEBUG    Git submodule: extensions-builtin/sdnext-kanvas / main
09:30:01-905235 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
09:30:01-927882 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
09:30:01-949232 DEBUG    Git submodule: wiki / master
09:30:01-979421 DEBUG    Installed packages: 266
09:30:01-980106 DEBUG    Extensions all: ['stable-diffusion-webui-rembg', 'sdnext-modernui', 'sdnext-kanvas', 'sd-extension-system-info',
                         'sd-extension-chainner']
09:30:01-980739 DEBUG    Extension installer: builtin=True
                         file="/home/tillerz/dev/extensions-builtin/stable-diffusion-webui-rembg/install.py"
09:30:02-066684 DEBUG    Extensions all: []
09:30:02-067341 INFO     Extensions enabled: ['stable-diffusion-webui-rembg', 'sdnext-modernui', 'sdnext-kanvas',
                         'sd-extension-system-info', 'sd-extension-chainner']
09:30:02-086220 INFO     Install: verifying requirements
09:30:02-088219 DEBUG    Setup complete without errors: 1770885002
09:30:02-094117 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
09:30:02-094923 INFO     Installer time: total=4.91 torch=1.66 latest=1.01 git=0.81 submodules=0.65 base=0.25 files=0.14 branch=0.14
09:30:02-095774 INFO     Command line args: [] args=[]
09:30:02-096267 DEBUG    Flags: sd=[] ld=['LD_PRELOAD=libtcmalloc.so.4', 'LD_LIBRARYPATH=/usr/lib/wsl/lib:',
                         'LD_LIBRARY_PATH=:/home/tillerz/dev/venv/lib/']
09:30:02-096864 DEBUG    Starting module: <module 'webui' from '/home/tillerz/dev/webui.py'>
09:30:02-098623 DEBUG    Initializing: libraries
09:30:11-505141 DEBUG    System: cores=8 affinity=8 threads=4
09:30:11-507185 INFO     Torch: torch==2.8.0+cu128 torchvision==0.23.0+cu128
09:30:11-507716 INFO     Packages: diffusers==0.37.0.dev0 transformers==4.57.5 accelerate==1.12.0 gradio==3.43.2 pydantic==1.10.21
                         numpy==2.1.2 cv2==4.12.0
09:30:11-572269 DEBUG    Initializing: shared module
09:30:11-635859 DEBUG    Initializing: pipelines
09:30:12-349719 DEBUG    ONNX: version=1.23.2, available=['AzureExecutionProvider', 'CPUExecutionProvider']
09:30:12-369036 DEBUG    State initialized: id=131512848305904
09:30:12-559068 DEBUG    Initializing: default modes
09:30:12-559775 INFO     Device detect: memory=24.0 default=balanced optimization=highvram
09:30:12-561664 DEBUG    Initializing: settings
09:30:12-566303 DEBUG    Read: file="/home/tillerz/dev/config.json" json=86 bytes=3509 time=0.000 fn=__init__:load
09:30:12-566995 DEBUG    Setting validation: "sdnq_quantize_weights"="Video" default="[]" choices=['Model', 'TE', 'LLM', 'Control', 'VAE']
09:30:12-567516 DEBUG    Setting validation: "sdp_options"="Memory attention" default="['Flash', 'Memory', 'Math']" choices=['Flash',
                         'Memory', 'Math']
09:30:12-568095 DEBUG    Setting validation: "sdp_options"="Math attention" default="['Flash', 'Memory', 'Math']" choices=['Flash',
                         'Memory', 'Math']
09:30:12-568589 DEBUG    Setting validation: "prompt_attention"="Full parser" default="native" choices=['native', 'compel', 'xhinker',
                         'a1111', 'fixed']
09:30:12-569399 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
09:30:12-572954 DEBUG    Read: file="data/reference.json" json=101 bytes=50912 time=0.001 fn=_call_with_frames_removed:<module>
09:30:12-573537 DEBUG    Initializing: devices
09:30:12-573948 DEBUG    Torch cuDNN: deterministic=True
09:30:12-574342 DEBUG    Torch cuDNN: benchmark=True
09:30:12-574774 DEBUG    Torch attention: type="sdpa" kernels=['Memory attention', 'Math attention', 'Flash', 'Memory', 'Math'] overrides=[]
09:30:12-575447 DEBUG    Torch attention installed: flashattn=False sageattention=False
09:30:12-575865 DEBUG    Torch attention status: flash=False flash3=False aiter=False sage=False flex=True npu=False xla=False
                         xformers=False
09:30:13-903674 DEBUG    Triton: pass=True fn=<module>:set_cuda_params time=1.25
09:30:13-904441 INFO     Torch parameters: backend=cuda device=cuda config=BF16 dtype=torch.bfloat16 context=no_grad nohalf=False
                         nohalfvae=False upcast=False deterministic=True tunable=[False, True] fp16=pass bf16=pass triton=pass
                         optimization="Scaled-Dot-Product"
09:30:13-916615 DEBUG    Quantization: registered=SDNQ
09:30:13-961528 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_120 capability=(8, 9) cuda=12.8 cudnn=91002 driver=591.86
09:30:14-077423 DEBUG    Entering start sequence
09:30:14-083050 DEBUG    Initializing: modules
09:30:14-102679 DEBUG    Read: file="data/metadata.json" json=1215 bytes=3545847 time=0.019 fn=initialize:init_metadata
09:30:14-104118 DEBUG    Read: file="data/cache.json" json=2 bytes=33326 time=0.001 fn=initialize:init_cache
09:30:14-174130 INFO     Available VAEs: path="/mnt/sd/models/VAE" items=2
09:30:14-175696 INFO     Available UNets: path="/mnt/sd/models/UNET" items=1
09:30:14-177217 INFO     Available TEs: path="/mnt/sd/models/Text-encoder" items=6
09:30:14-224709 INFO     Available Models: safetensors="/mnt/sd/models/StableDiffusion":22 diffusers="/mnt/sd/models/Diffusers":4
                         reference=101 items=26 time=0.05
09:30:14-252463 INFO     Available LoRAs: path="/mnt/sd/models/Lora" items=67 folders=2 time=0.02
09:30:14-299537 INFO     Available Styles: path="/mnt/sd/models/styles" items=333 time=0.05
09:30:14-302120 INFO     Available Detailer: path="/mnt/sd/models/yolo" items=17 downloaded=14
09:30:14-302904 DEBUG    Extensions: disabled=[]
09:30:14-303346 INFO     Load extensions
09:30:14-775865 DEBUG    Extensions init time: total=0.47 stable-diffusion-webui-rembg=0.34
09:30:14-998685 DEBUG    Read: file="data/upscalers.json" json=4 bytes=2640 time=0.000 fn=__init__:__init__
09:30:15-000435 DEBUG    Read: file="extensions-builtin/sd-extension-chainner/models.json" json=25 bytes=2803 time=0.000
                         fn=__init__:find_scalers
09:30:15-007913 DEBUG    Available chaiNNer: path="/mnt/sd/models/chaiNNer" defined=25 discovered=0 downloaded=0
09:30:15-016286 INFO     Available Upscalers: items=82 downloaded=2 user=0 time=0.24 types=['None', 'Resize', 'Latent', 'AsymmetricVAE',
                         'WanUpscale', 'DCC', 'VIPS', 'HQX', 'ICBI', 'Spandrel', 'ChaiNNer', 'AuraSR', 'Diffusion', 'RealESRGAN', 'SCUNet',
                         'ESRGAN', 'SwinIR', 'SeedVR']
09:30:15-073351 INFO     Networks: type="video" engines=13 models=71 errors=0 time=0.05
09:30:15-076984 INFO     Huggingface: transfer=xet parallel=True direct=False token="hf_...GUeN" cache="/mnt/sd/models/huggingface/hub" init
09:30:15-682165 DEBUG    Huggingface: cache="/mnt/sd/models/huggingface/hub" size=149527 MB
09:30:15-683045 DEBUG    Temp folder: path="/home/tillerz/sdtemp/images"
09:30:15-683530 DEBUG    UI start sequence
09:30:15-683903 DEBUG    UI image support: kanvas=main
09:30:15-686386 INFO     UI locale: name="en: English"
09:30:15-686843 INFO     UI theme: type=Modern name="Default" available=38
09:30:15-687384 DEBUG    UI theme: css="extensions-builtin/sdnext-modernui/themes/Default.css" base="['base.css', 'timesheet.css']"
                         user="user.css"
09:30:15-689779 DEBUG    UI initialize: tab=txt2img
09:30:15-954945 DEBUG    Read: file="data/reference.json" json=101 bytes=50912 time=0.000 fn=list_items:list_reference
09:30:15-956317 DEBUG    Read: file="data/reference-quant.json" json=24 bytes=9140 time=0.000 fn=list_items:list_reference
09:30:15-957543 DEBUG    Read: file="data/reference-distilled.json" json=20 bytes=9775 time=0.000 fn=list_items:list_reference
09:30:15-958589 DEBUG    Read: file="data/reference-community.json" json=16 bytes=6400 time=0.000 fn=list_items:list_reference
09:30:15-959456 DEBUG    Read: file="data/reference-cloud.json" json=2 bytes=677 time=0.000 fn=list_items:list_reference
09:30:15-960519 DEBUG    Read: file="data/reference-nunchaku.json" json=18 bytes=7372 time=0.000 fn=list_items:list_reference
09:30:15-966091 DEBUG    Networks: type="reference" {'total': 181, 'ready': 5, 'hidden': 2, 'experimental': 0, 'base': 100, 'quantized': 24,
                         'community': 16, 'distilled': 19, 'cloud': 2, 'nunchaku': 16}
09:30:16-024041 DEBUG    Networks: type="wildcards" items=116 subfolders=8 tab=txt2img folders=['/mnt/sd/models/wildcards'] list=0.20
                         thumb=0.06 desc=0.00 info=0.00 workers=12
09:30:16-028938 DEBUG    Networks: type="style" items=333 subfolders=10 tab=txt2img folders=['/mnt/sd/models/styles', 'html'] list=0.15
                         thumb=0.06 desc=0.00 info=0.00 workers=12
09:30:16-031401 DEBUG    Networks: type="lora" items=67 subfolders=9 tab=txt2img folders=['/mnt/sd/models/Lora'] list=0.19 thumb=0.05
                         desc=0.12 info=1.04 workers=12
09:30:16-035686 DEBUG    Networks: type="model" items=203 subfolders=12 tab=txt2img folders=['/mnt/sd/models/StableDiffusion',
                         'models/Reference', '/mnt/sd/models/Stable-diffusion'] list=0.30 thumb=0.04 desc=0.06 info=0.50 workers=12
09:30:16-037289 DEBUG    Networks: type="embedding" items=24 subfolders=2 tab=txt2img folders=['/mnt/sd/models/embeddings'] list=0.32
                         thumb=0.00 desc=0.02 info=0.21 workers=12
09:30:16-214628 DEBUG    UI initialize: tab=img2img
09:30:16-412452 DEBUG    UI initialize: tab=control models="/mnt/sd/models/control"
09:30:16-602826 DEBUG    Script: fn="extensions-builtin/sd-extension-system-info/scripts/system-info.py" type=control skip
09:30:16-755871 DEBUG    UI initialize: tab=video
09:30:16-838222 DEBUG    UI initialize: tab=process
09:30:16-868752 DEBUG    UI initialize: tab=caption
09:30:16-945476 DEBUG    UI initialize: tab=models
09:30:16-993315 DEBUG    UI initialize: tab=gallery
09:30:17-018636 DEBUG    Read: file="ui-config.json" json=147 bytes=13902 time=0.000 fn=__init__:read_from_file
09:30:17-019327 DEBUG    UI initialize: tab=settings
09:30:17-309044 DEBUG    Settings: sections=22 settings=374/613 quicksettings=4
09:30:17-673005 DEBUG    UI initialize: tab=info
09:30:17-689130 DEBUG    UI initialize: tab=extensions
09:30:17-692505 INFO     Extension list: No information found. Refresh required.
09:30:17-794485 DEBUG    Extension list: processed=3 installed=3 enabled=3 disabled=0 visible=3 hidden=0
09:30:17-917713 DEBUG    Root paths: ['/home/tillerz/dev', 'models']
09:30:17-983080 INFO     Local URL: http://127.0.0.1:7860/
09:30:17-983637 INFO     API docs: http://127.0.0.1:7860/docs
09:30:17-984035 INFO     API redocs: http://127.0.0.1:7860/redocs
09:30:17-985367 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
09:30:17-985863 DEBUG    API initialize
09:30:18-129663 DEBUG    Scripts setup: time=0.345 []
09:30:18-130326 DEBUG    Model metadata: file="data/metadata.json" no changes
09:30:18-130791 INFO     Model: autoload=False selected="SDXL/perfectdeliberate_v70 [3d54af6f66]"
09:30:18-131890 DEBUG    Script init: ['system-info.py:app_started=0.06']
09:30:18-132567 INFO     Startup time: total=27.93 gradio=4.53 launch=4.08 loader=3.97 installer=3.97 torch=3.47 libraries=3.14
                         diffusers=0.75 cleanup=0.61 ui-networks=0.53 extensions=0.47 ui-extensions=0.44 ui-info=0.35 upscalers=0.24
                         ui-control=0.23 ui-img2img=0.17 ui-txt2img=0.16
09:30:18-135484 DEBUG    Save: file="/home/tillerz/dev/config.json" json=86 bytes=3509 time=0.004
09:30:21-511174 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 0.114
09:30:25-904793 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.003
09:30:26-393452 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/version 127.0.0.1 0.0007
09:30:26-485409 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
                         (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36
09:30:26-488175 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.004
09:30:27-747326 INFO     UI: ready time=6638
09:31:17-751536 DEBUG    Control: override resize mode=before
09:31:17-752452 DEBUG    Model requested: fn=ui_control.py:generate_click:control_run
09:31:17-753063 DEBUG    Search model: name="SDXL/perfectdeliberate_v70 [3d54af6f66]"
                         matched="/mnt/sd/models/StableDiffusion/SDXL/perfectdeliberate_v70.safetensors" type=alias
09:31:17-753625 INFO     Load model: select="SDXL/perfectdeliberate_v70 [3d54af6f66]"
09:31:17-756135 INFO     Autodetect model: detect="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="/mnt/sd/models/StableDiffusion/SDXL/perfectdeliberate_v70.safetensors"
09:31:17-757437 DEBUG    Cache clear
Progress  1.91it/s █████████ 100% 7/7 00:03 00:00 Loading pipeline components...
09:31:22-399205 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.bfloat16,
                         'load_connected_pipeline': True, 'extract_ema': False, 'config': 'configs/sdxl', 'use_safetensors': True,
                         'cache_dir': '/mnt/sd/models/huggingface/hub'}
09:31:26-188021 INFO     Network load: type=embeddings loaded=23 skipped=1 time=3.78
09:31:26-189158 DEBUG    Setting model: component=vae {'slicing': True, 'tiling': False}
09:31:26-189765 DEBUG    Setting model: attention="Scaled-Dot-Product"
09:31:26-190660 DEBUG    Load model: post_quant=sdnq
09:31:26-191111 DEBUG    Quantization: type=SDNQ modules=['Video'] dtype=uint4 dtype_te=Same as model offload=balanced pre_forward=True
09:31:26-191779 INFO     Quantization: type=SDNQ time=0.00
09:31:26-192437 INFO     Offload: type=balanced op=init watermark=0.2-0.8 gpu=4.80-19.20:24.00 cpu=39.000 limit=0.00
                         always=['T5EncoderModel', 'UMT5EncoderModel'] never=['CLIPTextModel', 'CLIPTextModelWithProjection',
                         'AutoencoderKL'] pre=True streams=False
09:31:26-210419 DEBUG    Module: name=unet cls=UNet2DConditionModel size=4.782 params=2567463684 quant=None
09:31:26-213126 DEBUG    Module: name=text_encoder_2 cls=CLIPTextModelWithProjection size=1.296 params=695731200 quant=None
09:31:26-214875 DEBUG    Module: name=text_encoder cls=CLIPTextModel size=0.230 params=123703296 quant=None
09:31:26-217005 DEBUG    Module: name=vae cls=AutoencoderKL size=0.156 params=83653863 quant=None
09:31:26-217779 INFO     Model class=StableDiffusionXLPipeline modules=4 size=6.464
09:31:26-220757 INFO     Load model: family=sdxl time={'total': 8.47, 'load': 4.65, 'embeddings': 3.78} native=1024 memory={'ram': {'total':
                         39.17, 'rss': 8.91, 'used': 9.53, 'free': 13.52, 'avail': 29.65, 'buffers': 0.03, 'cached': 16.6}, 'gpu': {'used':
                         1.6, 'total': 23.99, 'active': 0.0, 'peak': 0.43, 'retries': 0, 'oom': 0, 'swap': 0}, 'job': 'Load model'}
09:31:26-228087 DEBUG    Sampler: "DPM++ 2M" class=DPMSolverMultistepScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085,
                         'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'solver_order': 2, 'prediction_type': 'epsilon',
                         'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'algorithm_type': 'dpmsolver++', 'solver_type':
                         'midpoint', 'lower_order_final': True, 'flow_shift': 1.0, 'final_sigmas_type': 'zero', 'lambda_min_clipped': -inf,
                         'timestep_spacing': 'linspace', 'steps_offset': 0, 'time_shift_type': 'exponential'}
09:31:26-233093 INFO     Processing modifiers: apply
09:31:26-265534 DEBUG    Tokenizer: words=50245 file="configs/sdxl/tokenizer/vocab.json"
09:31:26-900491 INFO     Base: pipeline=StableDiffusionXLPipeline task=TEXT_2_IMAGE batch=1/1x1 set={'prompt_embeds': torch.Size([1, 231,
                         2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds': torch.Size([1, 231, 2048]),
                         'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[1608629606]',
                         'num_inference_steps': 16, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_end': None, 'output_type': 'latent',
                         'width': 1024, 'height': 1024, 'parser': 'Full parser'}
Progress  2.11s/it ██▏                                  6% 1/16 00:02 00:31 Base
09:31:29-153874 DEBUG    Decode: type="taesd" variant="TAESD 1.2 Chocolate-Dipped Shortbread"
                         fn="/mnt/sd/models/TAESD/taesd_12_decoder_sdxl.pth" layers=3 load
Progress  3.53it/s █████████████████████████████████ 100% 16/16 00:04 00:00 Base
09:31:31-441756 INFO     Processing modifiers: unapply
09:31:31-726093 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
09:31:34-182075 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 128, 128]:cuda:0
                         dtype=torch.bfloat16 time=2.456
09:31:34-201268 DEBUG    Pipeline class change: original=StableDiffusionXLPipeline target=StableDiffusionXLInpaintPipeline device=cuda:0
                         fn=detail:restore
09:31:34-202177 DEBUG    Detailer: models=['face-yolov8s', 'deepfashion2_yolov8s-seg']
09:31:34-295867 INFO     Load: type=Detailer name="face-yolov8s" model="/mnt/sd/models/yolo/face-yolov8s.pt" ultralytics=8.3.40
                         classes=['face']
09:31:34-796520 DEBUG    Detail: model="1:face-yolov8s" item=1/1 box=[390, 170, 637, 479] label="face" score=0.88 seg=True prompt="1woman,
                         solo, hentai, candid shot, looking away, (30-year-old 30yo adult mature woman, mature face, voluptuous woman
                         Laraine Day, Joni Mitchell she is of israeli heritage, with fair skin, black hair, straight bangs, japanese, dark
                         brown eyes, makeup, arabic_eyeliner:1.2), she is a prisoner and stands in a gothic prison drenched in golden
                         afternoon sunlight spilling from stained glass windows depicting biblical scenes, dusty air, lightshafts, god
                         rays,"
09:31:34-882953 DEBUG    Resize image: method=sharpfin source=564x564 target=1024x1024 kernel=ResizeKernel.MAGIC_KERNEL_SHARP_2021
                         device=cuda linearize=False fn=resize:resize
09:31:36-472903 DEBUG    Resize image: source=564:564 target=1024:1024 mode="Crop" upscaler="None" type=image time=1.60
                         fn=process_images_inner:init
09:31:36-483121 DEBUG    Resize image: method=sharpfin source=564x564 target=1024x1024 kernel=ResizeKernel.MAGIC_KERNEL_SHARP_2021
                         device=cuda linearize=False fn=resize:resize
09:31:36-401168 DEBUG    Resize image: source=564:564 target=1024:1024 mode="Fill" upscaler="None" type=image time=-0.08
                         fn=process_images_inner:init
09:31:36-403887 DEBUG    Sampler: "DPM++ 2M" class=DPMSolverMultistepScheduler config={'num_train_timesteps': 1000, 'beta_start': 0.00085,
                         'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'solver_order': 2, 'prediction_type': 'epsilon',
                         'dynamic_thresholding_ratio': 0.995, 'sample_max_value': 1.0, 'algorithm_type': 'dpmsolver++', 'solver_type':
                         'midpoint', 'lower_order_final': True, 'flow_shift': 1.0, 'final_sigmas_type': 'zero', 'lambda_min_clipped': -inf,
                         'timestep_spacing': 'linspace', 'steps_offset': 0, 'time_shift_type': 'exponential'}
09:31:36-405068 INFO     Processing modifiers: apply
09:31:36-651040 INFO     Detail: pipeline=StableDiffusionXLInpaintPipeline task=INPAINTING batch=1/1x1 set={'prompt_embeds': torch.Size([1,
                         154, 2048]), 'pooled_prompt_embeds': torch.Size([1, 1280]), 'negative_prompt_embeds': torch.Size([1, 154, 2048]),
                         'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6, 'generator': 'cuda:[27099527]',
                         'num_inference_steps': 67, 'eta': 1.0, 'guidance_rescale': 0, 'denoising_start': None, 'denoising_end': None,
                         'output_type': 'latent', 'image': [<PIL.Image.Image image mode=RGB size=1024x1024 at 0x779C155D5010>],
                         'mask_image': <PIL.Image.Image image mode=L size=1024x1024 at 0x779C19644F80>, 'strength': 0.3, 'height': 1024,
                         'width': 1024, 'parser': 'Full parser'}
Progress  5.28it/s ███████████████████████████████ 100% 20/20 00:03 00:00 Detail
09:31:42-124188 INFO     Processing modifiers: unapply
09:31:42-155508 DEBUG    Setting decode: component=vae {'slicing': True, 'tiling': False}
09:31:42-180901 DEBUG    Decode: vae="default" scale=8 upcast=False slicing=True tiling=False latents=[1, 4, 128, 128]:cuda:0
                         dtype=torch.bfloat16 time=0.025
09:31:42-354344 DEBUG    Resize image: method=sharpfin source=1024x1024 target=564x564 kernel=ResizeKernel.MAGIC_KERNEL_SHARP_2021
                         device=cuda linearize=False fn=resize:resize
09:31:42-627255 DEBUG    Resize image: source=1024:1024 target=564:564 mode="Crop" upscaler="None" type=image time=0.27
                         fn=process_samples:apply_overlay
09:31:42-636728 DEBUG    Pipeline class change: original=StableDiffusionXLInpaintPipeline target=StableDiffusionXLPipeline device=cuda:0
                         fn=restore:process_images_inner
09:31:42-637609 INFO     Processed: images=1 its=2.55 ops=['detailer', 'inpaint']
09:31:42-638151 DEBUG    Processed: timers={'total': 22.68, 'pipeline': 10.92, 'decode': 2.95, 'init': 2.21, 'preview': 2.01, 'onload':
                         1.82, 'prompt': 0.9, 'offload': 0.64, 'callback': 0.55, 'post': 0.31, 'move': 0.27}
09:31:42-639208 DEBUG    Processed: memory={'ram': {'total': 39.17, 'rss': 9.16, 'used': 9.79, 'free': 13.25, 'avail': 29.38, 'buffers':
                         0.03, 'cached': 16.6}, 'gpu': {'used': 13.72, 'total': 23.99, 'active': 6.63, 'peak': 11.34, 'retries': 0, 'oom':
                         0, 'swap': 0}, 'job': ''}
09:31:42-667874 INFO     Load: type=Detailer name="deepfashion2_yolov8s-seg" model="/mnt/sd/models/yolo/deepfashion2_yolov8s-seg.pt"
                         ultralytics=8.3.40 classes=['short_sleeved_shirt', 'long_sleeved_shirt', 'short_sleeved_outwear',
                         'long_sleeved_outwear', 'vest', 'sling', 'shorts', 'trousers', 'skirt', 'short_sleeved_dress',
                         'long_sleeved_dress', 'vest_dress', 'sling_dress']
WARNING ⚠️ Model does not support 'augment=True', reverting to single-scale prediction.
09:31:42-882048 INFO     Detailer: model="deepfashion2_yolov8s-seg" no items detected
09:31:42-885548 DEBUG    Pipeline class change: original=StableDiffusionXLInpaintPipeline target=StableDiffusionXLPipeline device=cuda:0
                         fn=process_images:process_images_inner
09:31:42-886576 INFO     Processed: images=1 its=0.96 ops=['detailer', 'txt2img']
09:31:42-887311 DEBUG    Processed: timers={'total': 45.6, 'pipeline': 10.92, 'decode': 2.95, 'init': 2.21, 'preview': 2.01, 'onload': 1.82,
                         'prompt': 0.9, 'offload': 0.64, 'post': 0.56, 'callback': 0.55, 'move': 0.27}
09:31:42-888467 DEBUG    Processed: memory={'ram': {'total': 39.17, 'rss': 9.17, 'used': 9.8, 'free': 13.24, 'avail': 29.37, 'buffers':
                         0.03, 'cached': 16.6}, 'gpu': {'used': 8.58, 'total': 23.99, 'active': 6.65, 'peak': 11.34, 'retries': 0, 'oom': 0,
                         'swap': 0}, 'job': ''}
09:31:43-413717 DEBUG    Save temp: image="/home/tillerz/sdtemp/images/tmpan4i7eir.png" width=1024 height=1024 size=1285728
```

### Operating system

Windows

### Compute

nVidia CUDA

### Interface

ModernUI

### Branch

Dev

### Model

StableDiffusion 1.5/2.1/XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i cant reproduce.
try settings -> postprocess -> resize -> set method to pil?

**Comment by Tillerz** [comment]
Right. That fixed it. But I never touched that setting, it was set to "Sharpfin MKS2021". If that was a default before, it will then break for everyone else, too?

**Comment by vladmandic** [comment]
that is a brand new resize method. i'll change default to be pil as usual as sharpfin is not sufficiently tested.
