### ISSUE TITLE
[Issue]: Installation issues

### ISSUE THREAD

**Issue by allardusdus** [vladmandic/sdnext#4878]
### Issue Description

I am trying to install sdnext, but I am running into some issues.

The issues might be caused by the fact that I've installed both 3.14 en 3.10 of python. As you can see in the error message I've tried to redirect the bat file so it uses 3.10, since

When running this code:
:: --------------------------------------------------------------------------------------------------------------
:: Do not make any changes to this file. Instead, create a shortcut to this file and add needed arguments there.
:: --------------------------------------------------------------------------------------------------------------

@echo off

if not defined PYTHON (set PYTHON=python)
if not defined VENV_DIR (set "VENV_DIR=%~dp0%venv")
set ERROR_REPORTING=FALSE
mkdir tmp 2>NUL

%PYTHON% -c "" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :check_pip
echo Cannot launch python
goto :show_stdout_stderr

:check_pip
%PYTHON% -mpip --help >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :start_venv
if "%PIP_INSTALLER_LOCATION%" == "" goto :show_stdout_stderr
%PYTHON% "%PIP_INSTALLER_LOCATION%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :start_venv
echo Cannot install pip
goto :show_stdout_stderr

:start_venv
if ["%VENV_DIR%"] == ["-"] goto :skip_venv
if ["%SKIP_VENV%"] == ["1"] goto :skip_venv

dir "%VENV_DIR%\Scripts\Python.exe" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv

for /f "delims=" %%i in ('CALL %PYTHON% -c "import sys; print(sys.executable)"') do set PYTHON_FULLNAME="%%i"
echo Using python: %PYTHON_FULLNAME%
echo Creating VENV: %VENV_DIR%
%PYTHON_FULLNAME% -m venv "%VENV_DIR%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv
echo Failed creating VENV: "%VENV_DIR%"
goto :show_stdout_stderr

:activate_venv
set PYTHON="%VENV_DIR%\Scripts\Python.exe"
echo Using VENV: %VENV_DIR%

:skip_venv
if [%ACCELERATE%] == ["True"] goto :accelerate
goto :launch

:accelerate
set ACCELERATE="%VENV_DIR%\Scripts\accelerate.exe"
if EXIST %ACCELERATE% goto :accelerate_launch

:launch
set PYTHON=C:\Users\USER\AppData\Local\Programs\Python\Python310\python.exe
%PYTHON% launch.py %*
pause
exit /b

:accelerate_launch
echo Using accelerate
%ACCELERATE% launch --num_cpu_threads_per_process=6 launch.py %*
pause
exit /b

:show_stdout_stderr

echo.
echo exit code: %errorlevel%

for /f %%i in ("tmp\stdout.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stdout:
type tmp\stdout.txt

:show_stderr
for /f %%i in ("tmp\stderr.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stderr:
type tmp\stderr.txt

:endofscript

echo.
echo Launch Failed
pause

I get this message:

Using VENV: C:\programs\sdnext\sdnext\venv
14:09:04-351135 INFO     Starting SD.Next
14:09:04-351135 INFO     Logger: file="C:\programs\sdnext\sdnext\sdnext.log" level=DEBUG host="C_USER" size=75
                         mode=append
14:09:04-351135 INFO     Python: version=3.10.0 platform=Windows
                         bin="C:\Users\USER\AppData\Local\Programs\Python\Python310\python.exe"
                         venv="C:\Users\USER\AppData\Local\Programs\Python\Python310"
14:09:04-351135 WARNING  Python: virtual environment not detected
14:09:04-351135 WARNING  Python: version=3.10.0 is not actively supported
14:09:04-374037 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.26200-SP0 python=3.10.0 locale=('Dutch_Netherlands', '1252')
                         setuptools=69.5.1 docker=False
14:09:04-643063 INFO     Version: app=sd.next updated=2026-05-14 commit=dedb130b2 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master kanvas=main ui=main
14:09:04-996319 TRACE    Repository branches: active=master available=['dev', 'feat/detailer-postprocess',
                         'feat/ltx-lora-and-condition', 'feat/native-transformer-loader', 'fix/sdnq-svd-dynamic-loop',
                         'master', 'pages']
14:09:05-200724 INFO     Version: app=sd.next latest=2026-05-14T19:08:08Z hash=dedb130b branch=master
14:09:05-202724 DEBUG    Packages: prefix=..\..\..\Users\USER\AppData\Local\Programs\Python\Python310
                         site=['..\\..\\..\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python310',
                         '..\\..\\..\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages']
14:09:05-203725 INFO     Args: []
14:09:05-204725 DEBUG    Setting environment tuning
14:09:05-204725 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
14:09:05-207724 INFO     Torch: verifying installation
14:09:05-207724 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
14:09:05-209724 INFO     CUDA: nVidia toolkit detected
C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py:180: UserWarning: cudaGetDeviceCount() returned cudaErrorNotSupported, likely using older driver or on CPU machine (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAFunctions.cpp:88.)
  return torch._C._cuda_getDeviceCount() > 0
14:09:07-031640 INFO     Update: package="transformers" current=5.6.0.dev0 hash=
                         target=380e3cc5d59912a48508cb6d4959a31cd460e12e
14:11:30-795161 INFO     Update: package="diffusers" current=0.39.0.dev0 hash=
                         target=015da50b40ee7a082ea8c17a8c43dff717c9653e
14:14:32-368937 WARNING  Modified files: ['webui.bat']
14:14:32-372937 INFO     Install: verifying requirements
14:14:32-528966 DEBUG    State: cached=True
14:14:32-528966 INFO     Startup: launch=quick
14:14:32-529966 INFO     Extensions: disabled=[]
14:14:32-530966 INFO     Extensions: path="extensions-builtin" enabled=['sd-extension-chainner', 'sdnext-kanvas', 'sdnext-modernui']
14:14:32-534964 INFO     Extensions: path="extensions" enabled=[]
14:14:32-539039 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
14:14:32-540042 INFO     Installer time: total=654.01 pip=325.20 diffusers=181.45 transformers=143.76 torch=1.82 latest=0.83 version=0.27 git=0.18
                         base=0.15 files=0.13
14:14:32-541173 INFO     Command line args: [] args=[]
14:14:32-542173 DEBUG    Flags: sd=[] ld=[]
14:14:32-543174 DEBUG    Starting module: <module 'webui' from 'C:\\programs\\sdnext\\sdnext\\webui.py'>
14:14:32-545175 DEBUG    Initializing: libraries
14:14:54-137574 INFO     Torch: torch==2.11.0+cu130 torchvision==0.26.0+cu130
14:14:54-140084 INFO     Packages: diffusers==0.39.0.dev0 transformers==5.6.0.dev0 accelerate==1.13.0 gradio==3.43.2 pydantic==2.12.5 numpy==2.1.2
                         cv2==4.12.0
14:14:54-166753 DEBUG    Initializing: shared module
14:14:54-303737 DEBUG    Initializing: pipelines
14:14:55-040420 DEBUG    State initialized: id=2800871536096
Press any key to continue . . .

I have tried fixing some stuff manualy, but while I advanced to further stages I always seem to get stuck with the fact that certain components (mostly huglibs) require diffent types of versions from other components. Which messes everything up.

I've deleted my venv folder and installer.json a few times along the way

Can anyone help?

Thanks in advance

### Relevant log output

```shell

```

### Operating system

Windows

### Compute

AMD ROCm

### Interface

ModernUI

### Branch

Master

### Model

StableDiffusion 1.5/2.1/XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
python 3.10 is too old, its no longer supported by python at all.
python 3.14 is too new and many tools dont exist for it yet.
if you have amd gpu, even python 3.13 is too new as amd does not build rocm for it.
recommended is to use python 3.12.

and you should not edit the script.
simply set env variable before starting the script.
for example:
`set PYTHON="C:\MyPath\python.exe"`

but....you said you have amd gpu? why is sdnext detecting nvidia? did you have it in the past? did you do full driver uninstall? google for `ddu` utility.

**Comment by Disty0** [comment]
I want to add to the Python version. Not only Python 3.10 is old but you are also using 3.10.0, aka the first ever version of the 3.10 line. This is very dangerous as that version has multiple vulnerabilities and bugs that got fixed in the later 3.10 sub-versions. If you still want to use 3.10 for some reason, then please use the latest sub-version from the 3.10 lineup instead of the first ever release of 3.10.

Also if you have an AMD GPU on Windows, then upgrade to the latest sub-version from the Python 3.12 line. Python 3.10 is not supported by ROCm PyTorch on Windows.

**Comment by allardusdus** [comment]
Thanks for the help. I am still running into issuess.

1:
I've installed 3.12

It ran with 3.14 standard so I did add a extra .bat file that started it on 3.12

That got me further but I got an error

2: 
I got an error for huggingface next that it didn't have the right version, so I reinstalled it manualy

venv\Scripts\activate

python -m pip uninstall huggingface_hub -y

python -m pip install "huggingface_hub<1.0,>=0.30.0"

3:
Using VENV: C:\programs\sdnext\venv
22:24:42-709198 INFO     Starting SD.Next
22:24:42-712197 INFO     Logger: file="C:\programs\sdnext\sdnext.log" level=DEBUG host="C_USER" size=75 mode=append
22:24:42-713199 INFO     Python: version=3.12.10 platform=Windows bin="C:\programs\sdnext\venv\Scripts\python.exe"
                         venv="C:\programs\sdnext\venv"
22:24:42-734348 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-11-10.0.26200-SP0 python=3.12.10 locale=('Dutch_Netherlands', '1252')
                         setuptools=69.5.1 docker=False
22:24:43-021296 INFO     Version: app=sd.next updated=2026-05-14 commit=dedb130b2 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master kanvas=main ui=main
22:24:43-644222 TRACE    Repository branches: active=master available=['dev', 'feat/detailer-postprocess',
                         'feat/ltx-lora-and-condition', 'feat/native-transformer-loader', 'fix/sdnq-svd-dynamic-loop',
                         'master', 'pages']
22:24:43-937059 INFO     Version: app=sd.next latest=2026-05-14T19:08:08Z hash=dedb130b branch=master
22:24:43-939063 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
22:24:43-940060 INFO     Args: []
22:24:43-940060 DEBUG    Setting environment tuning
22:24:43-941060 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
22:24:43-944059 INFO     Torch: verifying installation
22:24:43-944059 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=False
22:24:43-962653 INFO     CUDA: nVidia toolkit detected
22:24:45-549129 WARNING  Torch: version="2.4.1+cpu" CPU version installed and CUDA is available - consider reinstalling
22:24:45-563844 INFO     Update: package="transformers" current=4.52.4 hash=
                         target=380e3cc5d59912a48508cb6d4959a31cd460e12e
22:27:01-133032 INFO     Update: package="diffusers" current=0.39.0.dev0 hash=
                         target=015da50b40ee7a082ea8c17a8c43dff717c9653e
22:32:37-119499 INFO     Install: verifying requirements
22:32:37-176391 WARNING  Install: package="huggingface_hub" installed=1.16.4 required=1.14.0 updating...
22:32:41-113160 DEBUG    State: cached=True
22:32:41-114160 INFO     Startup: launch=quick
22:32:41-115160 INFO     Extensions: disabled=[]
22:32:41-116159 INFO     Extensions: path="extensions-builtin" enabled=['sd-extension-chainner', 'sdnext-kanvas',
                         'sdnext-modernui']
22:32:41-120197 INFO     Extensions: path="extensions" enabled=[]
22:32:41-125199 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
22:32:41-126197 INFO     Installer time: total=958.24 pip=475.25 diffusers=335.86 transformers=135.57 requirements=3.93
                         install=3.85 torch=1.61 latest=1.20 version=0.29 base=0.22 git=0.17 files=0.13 installed=0.13
22:32:41-127197 INFO     Command line args: [] args=[]
22:32:41-128346 DEBUG    Flags: sd=[] ld=[]
22:32:41-129345 DEBUG    Starting module: <module 'webui' from 'C:\\programs\\sdnext\\webui.py'>
22:32:41-130346 DEBUG    Initializing: libraries
22:32:51-829018 INFO     Torch: torch==2.4.1+cpu torchvision==0.19.1+cpu
22:32:51-832018 INFO     Packages: diffusers==0.39.0.dev0 transformers==5.6.0.dev0 accelerate==1.13.0 gradio==3.43.2
                         pydantic==2.12.5 numpy==2.1.2 cv2==4.12.0
22:32:51-895519 DEBUG    Initializing: shared module
22:32:52-069752 DEBUG    Initializing: pipelines
C:\programs\sdnext\venv\Lib\site-packages\diffusers\utils\import_utils.py:1031 in _get_module

  1030         try:
❱ 1031             return importlib.import_module("." + module_name, self.__name__)
  1032         except Exception as e:

C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:90 in import_module

   89             level += 1
❱  90     return _bootstrap._gcd_import(name[level:], package, level)
   91
in _gcd_import:1387
in _find_and_load:1360
in _find_and_load_unlocked:1310
in _call_with_frames_removed:488
in _gcd_import:1387
in _find_and_load:1360

                                                ... 8 frames hidden ...

C:\programs\sdnext\venv\Lib\site-packages\diffusers\models\unets\unet_2d.py:23 in <module>

   22 from ..modeling_utils import ModelMixin
❱  23 from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
   24

C:\programs\sdnext\venv\Lib\site-packages\diffusers\models\unets\unet_2d_blocks.py:36 in <module>

    35 )
❱   36 from ..transformers.dual_transformer_2d import DualTransformer2DModel
    37 from ..transformers.transformer_2d import Transformer2DModel

C:\programs\sdnext\venv\Lib\site-packages\diffusers\models\transformers\__init__.py:5 in <module>

   4 if is_torch_available():
❱  5     from .ace_step_transformer import AceStepTransformer1DModel
   6     from .auraflow_transformer_2d import AuraFlowTransformer2DModel

C:\programs\sdnext\venv\Lib\site-packages\diffusers\models\transformers\ace_step_transformer.py:26 in <module>

   25 from ..attention import AttentionMixin, AttentionModuleMixin
❱  26 from ..attention_dispatch import (
   27     AttentionBackendName,

C:\programs\sdnext\venv\Lib\site-packages\diffusers\models\attention_dispatch.py:748 in <module>

   747 # this but it was never merged: https://github.com/Dao-AILab/flash-attention/pull/1590
❱  748 @_custom_op("_diffusers_flash_attn_3::_flash_attn_forward", mutates_args=(), device_types="cuda")
   749 def _wrapped_flash_attn_3(

C:\programs\sdnext\venv\Lib\site-packages\torch\_library\custom_ops.py:119 in inner

  118
❱ 119             schema_str = torch._custom_op.impl.infer_schema(fn, mutates_args)
  120         else:

C:\programs\sdnext\venv\Lib\site-packages\torch\_library\infer_schema.py:42 in infer_schema

   41         if param.annotation not in SUPPORTED_PARAM_TYPES.keys():
❱  42             error_fn(
   43                 f"Parameter {name} has unsupported type {param.annotation}. "

C:\programs\sdnext\venv\Lib\site-packages\torch\_library\infer_schema.py:21 in error_fn

   20     def error_fn(what):
❱  21         raise ValueError(
   22             f"infer_schema(func): {what} " f"Got func with signature {sig})"
ValueError: infer_schema(func): Parameter q has unsupported type torch.Tensor. The valid types are: dict_keys([<class 'torch.Tensor'>, typing.Optional[torch.Tensor], typing.Sequence[torch.Tensor], typing.List[torch.Tensor], typing.Sequence[typing.Optional[torch.Tensor]], typing.List[typing.Optional[torch.Tensor]], <class 'int'>, typing.Optional[int], typing.Sequence[int], typing.List[int], typing.Optional[typing.Sequence[int]], typing.Optional[typing.List[int]], <class 'float'>, typing.Optional[float], typing.Sequence[float], typing.List[float], typing.Optional[typing.Sequence[float]], typing.Optional[typing.List[float]], <class 'bool'>, typing.Optional[bool], typing.Sequence[bool], typing.List[bool], typing.Optional[typing.Sequence[bool]], typing.Optional[typing.List[bool]], <class 'str'>, typing.Optional[str], typing.Union[int, float, bool], typing.Union[int, float, bool, NoneType], typing.Sequence[typing.Union[int, float, bool]], typing.List[typing.Union[int, float, bool]], <class 'torch.dtype'>, typing.Optional[torch.dtype], <class 'torch.device'>, typing.Optional[torch.device]]). Got func with signature (q: 'torch.Tensor', k: 'torch.Tensor', v: 'torch.Tensor', softmax_scale: 'float | None' = None, causal: 'bool' = False, qv: 'torch.Tensor | None' = None, q_descale: 'torch.Tensor | None' = None, k_descale: 'torch.Tensor | None' = None, v_descale: 'torch.Tensor | None' = None, attention_chunk: 'int' = 0, softcap: 'float' = 0.0, num_splits: 'int' = 1, pack_gqa: 'bool | None' = None, deterministic: 'bool' = False, sm_margin: 'int' = 0) -> 'tuple[torch.Tensor, torch.Tensor]')

The above exception was the direct cause of the following exception:

C:\programs\sdnext\venv\Lib\site-packages\diffusers\utils\import_utils.py:1031 in _get_module

  1030         try:
❱ 1031             return importlib.import_module("." + module_name, self.__name__)
  1032         except Exception as e:

C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:90 in import_module

   89             level += 1
❱  90     return _bootstrap._gcd_import(name[level:], package, level)
   91
in _gcd_import:1387
in _find_and_load:1360
in _find_and_load_unlocked:1331
in _load_unlocked:935
in exec_module:999
in _call_with_frames_removed:488

C:\programs\sdnext\venv\Lib\site-packages\diffusers\pipelines\pipeline_utils.py:48 in <module>

    47 from ..configuration_utils import ConfigMixin
❱   48 from ..models import AutoencoderKL
    49 from ..models.attention_processor import FusedAttnProcessor2_0
in _handle_fromlist:1412

C:\programs\sdnext\venv\Lib\site-packages\diffusers\utils\import_utils.py:1021 in __getattr__

  1020         elif name in self._class_to_module.keys():
❱ 1021             module = self._get_module(self._class_to_module[name])
  1022             value = getattr(module, name)

C:\programs\sdnext\venv\Lib\site-packages\diffusers\utils\import_utils.py:1033 in _get_module

  1032         except Exception as e:
❱ 1033             raise RuntimeError(
  1034                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
infer_schema(func): Parameter q has unsupported type torch.Tensor. The valid types are: dict_keys([<class 'torch.Tensor'>, typing.Optional[torch.Tensor], typing.Sequence[torch.Tensor], typing.List[torch.Tensor], typing.Sequence[typing.Optional[torch.Tensor]], typing.List[typing.Optional[torch.Tensor]], <class 'int'>, typing.Optional[int], typing.Sequence[int], typing.List[int], typing.Optional[typing.Sequence[int]], typing.Optional[typing.List[int]], <class 'float'>, typing.Optional[float], typing.Sequence[float], typing.List[float], typing.Optional[typing.Sequence[float]], typing.Optional[typing.List[float]], <class 'bool'>, typing.Optional[bool], typing.Sequence[bool], typing.List[bool], typing.Optional[typing.Sequence[bool]], typing.Optional[typing.List[bool]], <class 'str'>, typing.Optional[str], typing.Union[int, float, bool], typing.Union[int, float, bool, NoneType], typing.Sequence[typing.Union[int, float, bool]], typing.List[typing.Union[int, float, bool]], <class 'torch.dtype'>, typing.Optional[torch.dtype], <class 'torch.device'>, typing.Optional[torch.device]]). Got func with signature (q: 'torch.Tensor', k: 'torch.Tensor', v: 'torch.Tensor', softmax_scale: 'float | None' = None, causal: 'bool' = False, qv: 'torch.Tensor | None' = None, q_descale: 'torch.Tensor | None' = None, k_descale: 'torch.Tensor | None' = None, v_descale: 'torch.Tensor | None' = None, attention_chunk: 'int' = 0, softcap: 'float' = 0.0, num_splits: 'int' = 1, pack_gqa: 'bool | None' = None, deterministic: 'bool' = False, sm_margin: 'int' = 0) -> 'tuple[torch.Tensor, torch.Tensor]')

The above exception was the direct cause of the following exception:

C:\programs\sdnext\launch.py:356 in <module>

  355 if __name__ == "__main__":
❱ 356     main()
  357

C:\programs\sdnext\launch.py:317 in main

  316
❱ 317     uv, instance = start_server(immediate=True, server=None)
  318     t_server = time.time()

C:\programs\sdnext\launch.py:212 in start_server

  211     log.debug(f'Starting module: {server}')
❱ 212     module_spec.loader.exec_module(server)
  213
in exec_module:999
in _call_with_frames_removed:488

C:\programs\sdnext\webui.py:20 in <module>

   19 import modules.migrate
❱  20 from modules import shared
   21 from modules.call_queue import queue_lock, wrap_queued_call, wrap_gradio_gpu_call # pylint: disable=unused-import

C:\programs\sdnext\modules\shared.py:24 in <module>

   23 log.debug('Initializing: pipelines')
❱  24 from modules import shared_items # pylint: disable=unused-import
   25 from modules.caption.openclip import get_clip_models, refresh_clip_models # pylint: disable=unused-import

C:\programs\sdnext\modules\shared_items.py:7 in <module>

    6     'Autodetect': None,
❱   7     'Custom Diffusers Pipeline': getattr(diffusers, 'DiffusionPipeline', None),
    8

C:\programs\sdnext\venv\Lib\site-packages\diffusers\utils\import_utils.py:1022 in __getattr__

  1021             module = self._get_module(self._class_to_module[name])
❱ 1022             value = getattr(module, name)
  1023         else:

C:\programs\sdnext\venv\Lib\site-packages\diffusers\utils\import_utils.py:1021 in __getattr__

  1020         elif name in self._class_to_module.keys():
❱ 1021             module = self._get_module(self._class_to_module[name])
  1022             value = getattr(module, name)

C:\programs\sdnext\venv\Lib\site-packages\diffusers\utils\import_utils.py:1033 in _get_module

  1032         except Exception as e:
❱ 1033             raise RuntimeError(
  1034                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
infer_schema(func): Parameter q has unsupported type torch.Tensor. The valid types are: dict_keys([<class 'torch.Tensor'>, typing.Optional[torch.Tensor], typing.Sequence[torch.Tensor], typing.List[torch.Tensor], typing.Sequence[typing.Optional[torch.Tensor]], typing.List[typing.Optional[torch.Tensor]], <class 'int'>, typing.Optional[int], typing.Sequence[int], typing.List[int], typing.Optional[typing.Sequence[int]], typing.Optional[typing.List[int]], <class 'float'>, typing.Optional[float], typing.Sequence[float], typing.List[float], typing.Optional[typing.Sequence[float]], typing.Optional[typing.List[float]], <class 'bool'>, typing.Optional[bool], typing.Sequence[bool], typing.List[bool], typing.Optional[typing.Sequence[bool]], typing.Optional[typing.List[bool]], <class 'str'>, typing.Optional[str], typing.Union[int, float, bool], typing.Union[int, float, bool, NoneType], typing.Sequence[typing.Union[int, float, bool]], typing.List[typing.Union[int, float, bool]], <class 'torch.dtype'>, typing.Optional[torch.dtype], <class 'torch.device'>, typing.Optional[torch.device]]). Got func with signature (q: 'torch.Tensor', k: 'torch.Tensor', v: 'torch.Tensor', softmax_scale: 'float | None' = None, causal: 'bool' = False, qv: 'torch.Tensor | None' = None, q_descale: 'torch.Tensor | None' = None, k_descale: 'torch.Tensor | None' = None, v_descale: 'torch.Tensor | None' = None, attention_chunk: 'int' = 0, softcap: 'float' = 0.0, num_splits: 'int' = 1, pack_gqa: 'bool | None' = None, deterministic: 'bool' = False, sm_margin: 'int' = 0) -> 'tuple[torch.Tensor, torch.Tensor]')
Press any key to continue . . .

-

Any tip on what I should try next?
Thanks again

**Comment by vladmandic** [comment]
your python crashed, so sdnext had ni chance to log anything. check windows event viewer for that exact time.

**Comment by Suhani-prog-alt** [comment]
It looks like the issue is coming from a mismatched environment rather than SD.Next itself.

A few things stand out from the logs:

* Python 3.12 is correct, but the environment still seems inconsistent.
* `torch==2.4.1+cpu` is installed, meaning CPU-only PyTorch got installed while SD.Next is trying to detect GPU support.
* There are mixed signals about GPU detection (**AMD ROCm** selected but **nVidia toolkit detected**), which may indicate leftover NVIDIA drivers or an incorrect setup.
* Manual package changes (like reinstalling **huggingface_hub**) may have created dependency conflicts between **torch**, **diffusers**, and **transformers**.

Suggested clean fix:

1. Restore original **webui.bat** (avoid editing it directly).
2. Delete **venv**, **installer.json**, and any temporary files.
3. Use only Python 3.12.
4. Recreate the venv using:
   **set PYTHON=C:\Path\To\Python312\python.exe**
   then run **webui.bat**.
5. If using AMD GPU, check for leftover NVIDIA drivers (DDU may help) and let SD.Next install compatible Torch packages automatically instead of manual pip changes.

The **infer_schema(torch.Tensor)** error usually points to a Torch/Diffusers version mismatch caused by a broken or mixed environment.

**Comment by allardusdus** [comment]
I got it to work.

I reinstalled my drivers for AMD
I then updated my torch to a different version

Then it worked. Thanks for the help
